### ISSUE TITLE
quic-go v0.12.1 client can not correct to caddy v2.0.0-beta6

### ISSUE THREAD

**Issue by keycodingyfq** [caddyserver/caddy#2825]
**my Caddyfile**
```
{
 http_port 81
 https_port 8686
 experimental_http3
}

h3.test.com:8686 {
    reverse_proxy / 127.0.0.1:8088 
    tls /etc/nginx/ssl/server.crt /etc/nginx/ssl/server.key
}
```
**i run caddy** 
./caddy run -config=/data/caddy/cmd/caddy/Caddyfile -adapter caddyfile

**i run quic-go v0.12.1 client**
 go run /data/quic-go/example/client/main.go  -v -insecure https://h3.test.com:8686/

**client show me the error**
```
GET https://h3.test.com:8686/
client Starting new connection to h3.test.com ([::]:60057 -> 127.0.0.1:8686), source connection ID (empty), destination connection ID 0xa36ede80221795b4ec1facf93b, version QUIC WG draft-22
client -> Sending packet 0x0 (1200 bytes) for connection (empty), Initial
client  Long Header{Type: Initial, DestConnectionID: 0xa36ede80221795b4ec1facf93b, SrcConnectionID: (empty), Token: (empty), PacketNumber: 0x0, PacketNumberLen: 4, Length: 1177, Version: QUIC WG draft-22}
client  -> &wire.CryptoFrame{Offset: 0x0, Data length: 0x152, Offset + Data length: 0x152}
client  Long Header{Type: Retry, DestConnectionID: (empty), SrcConnectionID: 0x120bc6d6, Token: 0x9c6786985f90d5a8cfcf67dd26b98d2e10337c8dc293e8ea9ac40094d0f6fdb5a978fd786c7285d2c1418236e1df084f9b217f586f0b344bd55e886bc42f2412872903a1d75ee9e7b8f0aeaf8c7a90ccfd68f2e6a3689abbe330a3d301c83f28c2, OrigDestConnectionID: 0xa36ede80221795b4ec1facf93b, Version: QUIC WG draft-22}
client <- Received Retry
client Switching destination connection ID to: 0x120bc6d6
client Queueing packet 0x0 for retransmission.
client Dequeueing retransmission for packet 0x0 (Initial)
client Skipping packet number 0x0
client -> Sending packet 0x1 (1200 bytes) for connection (empty), Initial
client  Long Header{Type: Initial, DestConnectionID: 0x120bc6d6, SrcConnectionID: (empty), Token: 0x9c6786985f90d5a8cfcf67dd26b98d2e10337c8dc293e8ea9ac40094d0f6fdb5a978fd786c7285d2c1418236e1df084f9b217f586f0b344bd55e886bc42f2412872903a1d75ee9e7b8f0aeaf8c7a90ccfd68f2e6a3689abbe330a3d301c83f28c2, PacketNumber: 0x1, PacketNumberLen: 4, Length: 1088, Version: QUIC WG draft-22}
client  -> &wire.CryptoFrame{Offset: 0x0, Data length: 0x152, Offset + Data length: 0x152}
client <- Reading packet 0x0 (165 bytes) for connection (empty), Initial
client  Long Header{Type: Initial, DestConnectionID: (empty), SrcConnectionID: 0x526b8f82, Token: (empty), PacketNumber: 0x0, PacketNumberLen: 4, Length: 151, Version: QUIC WG draft-22}
client Received first packet. Switching destination connection ID to: 0x526b8f82
client  <- &wire.AckFrame{LargestAcked: 0x1, LowestAcked: 0x1, DelayTime: 0s}
client  updated RTT: 1.674104ms (σ: 837.052µs)
client  newly acked packets (1): [0x1]
client  <- &wire.CryptoFrame{Offset: 0x0, Data length: 0x7a, Offset + Data length: 0x7a}
client Received ServerHello message (122 bytes, encryption level: Initial)
client Installed Handshake Write keys
client Installed Handshake Read keys
client Handled crypto frame at level Initial. encLevelChanged: true
client  Queueing ACK because the first packet should be acknowledged.
client -> Sending packet 0x2 (1200 bytes) for connection (empty), Initial
client  Long Header{Type: Initial, DestConnectionID: 0x526b8f82, SrcConnectionID: (empty), Token: 0x9c6786985f90d5a8cfcf67dd26b98d2e10337c8dc293e8ea9ac40094d0f6fdb5a978fd786c7285d2c1418236e1df084f9b217f586f0b344bd55e886bc42f2412872903a1d75ee9e7b8f0aeaf8c7a90ccfd68f2e6a3689abbe330a3d301c83f28c2, PacketNumber: 0x2, PacketNumberLen: 4, Length: 1088, Version: QUIC WG draft-22}
client  -> &wire.AckFrame{LargestAcked: 0x0, LowestAcked: 0x0, DelayTime: 0s}
client <- Reading packet 0x0 (37 bytes) for connection (empty), Handshake
client  Long Header{Type: Handshake, DestConnectionID: (empty), SrcConnectionID: 0x526b8f82, PacketNumber: 0x0, PacketNumberLen: 4, Length: 25, Version: QUIC WG draft-22}
client  <- &wire.ConnectionCloseFrame{IsApplicationError:false, ErrorCode:0x178, ReasonPhrase:""}
client Peer closed session with error: CRYPTO_ERROR: tls: no application protocol
client  Queueing ACK because the first packet should be acknowledged.
client -> Sending packet 0x0 (37 bytes) for connection (empty), Handshake
client  Long Header{Type: Handshake, DestConnectionID: 0x526b8f82, SrcConnectionID: (empty), PacketNumber: 0x0, PacketNumberLen: 4, Length: 25, Version: QUIC WG draft-22}
client  -> &wire.AckFrame{LargestAcked: 0x0, LowestAcked: 0x0, DelayTime: 0s}
client Connection (empty) closed.
muxer received a packet with an unexpected connection ID (empty)
panic: Get https://h3.test.com:8686/: CRYPTO_ERROR: tls: no application protocol

goroutine 6 [running]:
main.main.func1(0xc0000b9500, 0x95b800, 0xc0000b8c00, 0xc000026601, 0xc000026980, 0x7ffc8dd2f879, 0x19)
        /data/yfq/quic-go/example/client/main.go:50 +0x434
created by main.main
        /data/yfq/quic-go/example/client/main.go:47 +0x462
exit status 2
```

**Comment by keycodingyfq** [comment]
when i use caddy v2.0.0-beta4 and quic-go use the version v0.7.1-0.20190908032346-fc962d18373a caddy can response correct

**Comment by marten-seemann** [comment]
That explains it. v0.7.1 is **really** old.

**Comment by mholt** [comment]
Yeah, that's an old beta version too; Caddy 2 beta 6 has been out for a while now, which uses quic-go v0.12.1: https://github.com/caddyserver/caddy/blob/bc738991b6234bf334855e1396919e79ef9791b8/go.mod#L16

I believe just using the latest beta should fix things up... if not, let us know.

**Comment by keycodingyfq** [comment]
i use caddy 2 beta 6 and the client is quic-go v0.12.1,it can't work too

**Comment by keycodingyfq** [comment]
> Yeah, that's an old beta version too; Caddy 2 beta 6 has been out for a while now, which uses quic-go v0.12.1:
> 
> https://github.com/caddyserver/caddy/blob/bc738991b6234bf334855e1396919e79ef9791b8/go.mod#L16
> 
> I believe just using the latest beta should fix things up... if not, let us know.

**Comment by keycodingyfq** [comment]
> Yeah, that's an old beta version too; Caddy 2 beta 6 has been out for a while now, which uses quic-go v0.12.1:
> 
> https://github.com/caddyserver/caddy/blob/bc738991b6234bf334855e1396919e79ef9791b8/go.mod#L16
> 
> I believe just using the latest beta should fix things up... if not, let us know.

i use caddy 2 beta 6 and the client is quic-go v0.12.1,it can't work too

**Comment by keycodingyfq** [comment]
> Yeah, that's an old beta version too; Caddy 2 beta 6 has been out for a while now, which uses quic-go v0.12.1:
> 
> https://github.com/caddyserver/caddy/blob/bc738991b6234bf334855e1396919e79ef9791b8/go.mod#L16
> 
> I believe just using the latest beta should fix things up... if not, let us know.

i test quic-go v0.12.1 only, use the example it work correct,but when i use caddy 2 beta6 as the server it can't work,the client print the message below
client Starting new connection to h3.test.com ([::]:60057 -> 127.0.0.1:8686), source connection ID (empty), destination connection ID 0xa36ede80221795b4ec1facf93b, version QUIC WG draft-22
client -> Sending packet 0x0 (1200 bytes) for connection (empty), Initial
client  Long Header{Type: Initial, DestConnectionID: 0xa36ede80221795b4ec1facf93b, SrcConnectionID: (empty), Token: (empty), PacketNumber: 0x0, PacketNumberLen: 4, Length: 1177, Version: QUIC WG draft-22}
client  -> &wire.CryptoFrame{Offset: 0x0, Data length: 0x152, Offset + Data length: 0x152}
client  Long Header{Type: Retry, DestConnectionID: (empty), SrcConnectionID: 0x120bc6d6, Token: 0x9c6786985f90d5a8cfcf67dd26b98d2e10337c8dc293e8ea9ac40094d0f6fdb5a978fd786c7285d2c1418236e1df084f9b217f586f0b344bd55e886bc42f2412872903a1d75ee9e7b8f0aeaf8c7a90ccfd68f2e6a3689abbe330a3d301c83f28c2, OrigDestConnectionID: 0xa36ede80221795b4ec1facf93b, Version: QUIC WG draft-22}
client <- Received Retry
client Switching destination connection ID to: 0x120bc6d6
client Queueing packet 0x0 for retransmission.
client Dequeueing retransmission for packet 0x0 (Initial)
client Skipping packet number 0x0
client -> Sending packet 0x1 (1200 bytes) for connection (empty), Initial
client  Long Header{Type: Initial, DestConnectionID: 0x120bc6d6, SrcConnectionID: (empty), Token: 0x9c6786985f90d5a8cfcf67dd26b98d2e10337c8dc293e8ea9ac40094d0f6fdb5a978fd786c7285d2c1418236e1df084f9b217f586f0b344bd55e886bc42f2412872903a1d75ee9e7b8f0aeaf8c7a90ccfd68f2e6a3689abbe330a3d301c83f28c2, PacketNumber: 0x1, PacketNumberLen: 4, Length: 1088, Version: QUIC WG draft-22}
client  -> &wire.CryptoFrame{Offset: 0x0, Data length: 0x152, Offset + Data length: 0x152}
client <- Reading packet 0x0 (165 bytes) for connection (empty), Initial
client  Long Header{Type: Initial, DestConnectionID: (empty), SrcConnectionID: 0x526b8f82, Token: (empty), PacketNumber: 0x0, PacketNumberLen: 4, Length: 151, Version: QUIC WG draft-22}
client Received first packet. Switching destination connection ID to: 0x526b8f82
client  <- &wire.AckFrame{LargestAcked: 0x1, LowestAcked: 0x1, DelayTime: 0s}
client  updated RTT: 1.674104ms (σ: 837.052µs)
client  newly acked packets (1): [0x1]
client  <- &wire.CryptoFrame{Offset: 0x0, Data length: 0x7a, Offset + Data length: 0x7a}
client Received ServerHello message (122 bytes, encryption level: Initial)
client Installed Handshake Write keys
client Installed Handshake Read keys
client Handled crypto frame at level Initial. encLevelChanged: true
client  Queueing ACK because the first packet should be acknowledged.
client -> Sending packet 0x2 (1200 bytes) for connection (empty), Initial
client  Long Header{Type: Initial, DestConnectionID: 0x526b8f82, SrcConnectionID: (empty), Token: 0x9c6786985f90d5a8cfcf67dd26b98d2e10337c8dc293e8ea9ac40094d0f6fdb5a978fd786c7285d2c1418236e1df084f9b217f586f0b344bd55e886bc42f2412872903a1d75ee9e7b8f0aeaf8c7a90ccfd68f2e6a3689abbe330a3d301c83f28c2, PacketNumber: 0x2, PacketNumberLen: 4, Length: 1088, Version: QUIC WG draft-22}
client  -> &wire.AckFrame{LargestAcked: 0x0, LowestAcked: 0x0, DelayTime: 0s}
client <- Reading packet 0x0 (37 bytes) for connection (empty), Handshake
client  Long Header{Type: Handshake, DestConnectionID: (empty), SrcConnectionID: 0x526b8f82, PacketNumber: 0x0, PacketNumberLen: 4, Length: 25, Version: QUIC WG draft-22}
client  <- &wire.ConnectionCloseFrame{IsApplicationError:false, ErrorCode:0x178, ReasonPhrase:""}
client Peer closed session with error: CRYPTO_ERROR: tls: no application protocol
client  Queueing ACK because the first packet should be acknowledged.
client -> Sending packet 0x0 (37 bytes) for connection (empty), Handshake
client  Long Header{Type: Handshake, DestConnectionID: 0x526b8f82, SrcConnectionID: (empty), PacketNumber: 0x0, PacketNumberLen: 4, Length: 25, Version: QUIC WG draft-22}
client  -> &wire.AckFrame{LargestAcked: 0x0, LowestAcked: 0x0, DelayTime: 0s}
client Connection (empty) closed.
muxer received a packet with an unexpected connection ID (empty)
panic: Get https://h3.test.com:8686/: CRYPTO_ERROR: tls: no application protocol

goroutine 6 [running]:
main.main.func1(0xc0000b9500, 0x95b800, 0xc0000b8c00, 0xc000026601, 0xc000026980, 0x7ffc8dd2f879, 0x19)
        /data/yfq/quic-go/example/client/main.go:50 +0x434
created by main.main
        /data/yfq/quic-go/example/client/main.go:47 +0x462
exit status 2

**Comment by keycodingyfq** [comment]
> Yeah, that's an old beta version too; Caddy 2 beta 6 has been out for a while now, which uses quic-go v0.12.1:
> 
> https://github.com/caddyserver/caddy/blob/bc738991b6234bf334855e1396919e79ef9791b8/go.mod#L16
> 
> I believe just using the latest beta should fix things up... if not, let us know.

i test quic-go v0.12.1 only, use the example it work correct,but when i use caddy 2 beta6 as the server it can't work,the client print the message below

```
client Starting new connection to h3.test.com ([::]:60057 -> 127.0.0.1:8686), source connection ID (empty), destination connection ID 0xa36ede80221795b4ec1facf93b, version QUIC WG draft-22
client -> Sending packet 0x0 (1200 bytes) for connection (empty), Initial
client Long Header{Type: Initial, DestConnectionID: 0xa36ede80221795b4ec1facf93b, SrcConnectionID: (empty), Token: (empty), PacketNumber: 0x0, PacketNumberLen: 4, Length: 1177, Version: QUIC WG draft-22}
client -> &wire.CryptoFrame{Offset: 0x0, Data length: 0x152, Offset + Data length: 0x152}
client Long Header{Type: Retry, DestConnectionID: (empty), SrcConnectionID: 0x120bc6d6, Token: 0x9c6786985f90d5a8cfcf67dd26b98d2e10337c8dc293e8ea9ac40094d0f6fdb5a978fd786c7285d2c1418236e1df084f9b217f586f0b344bd55e886bc42f2412872903a1d75ee9e7b8f0aeaf8c7a90ccfd68f2e6a3689abbe330a3d301c83f28c2, OrigDestConnectionID: 0xa36ede80221795b4ec1facf93b, Version: QUIC WG draft-22}
client <- Received Retry
client Switching destination connection ID to: 0x120bc6d6
client Queueing packet 0x0 for retransmission.
client Dequeueing retransmission for packet 0x0 (Initial)
client Skipping packet number 0x0
client -> Sending packet 0x1 (1200 bytes) for connection (empty), Initial
client Long Header{Type: Initial, DestConnectionID: 0x120bc6d6, SrcConnectionID: (empty), Token: 0x9c6786985f90d5a8cfcf67dd26b98d2e10337c8dc293e8ea9ac40094d0f6fdb5a978fd786c7285d2c1418236e1df084f9b217f586f0b344bd55e886bc42f2412872903a1d75ee9e7b8f0aeaf8c7a90ccfd68f2e6a3689abbe330a3d301c83f28c2, PacketNumber: 0x1, PacketNumberLen: 4, Length: 1088, Version: QUIC WG draft-22}
client -> &wire.CryptoFrame{Offset: 0x0, Data length: 0x152, Offset + Data length: 0x152}
client <- Reading packet 0x0 (165 bytes) for connection (empty), Initial
client Long Header{Type: Initial, DestConnectionID: (empty), SrcConnectionID: 0x526b8f82, Token: (empty), PacketNumber: 0x0, PacketNumberLen: 4, Length: 151, Version: QUIC WG draft-22}
client Received first packet. Switching destination connection ID to: 0x526b8f82
client <- &wire.AckFrame{LargestAcked: 0x1, LowestAcked: 0x1, DelayTime: 0s}
client updated RTT: 1.674104ms (σ: 837.052µs)
client newly acked packets (1): [0x1]
client <- &wire.CryptoFrame{Offset: 0x0, Data length: 0x7a, Offset + Data length: 0x7a}
client Received ServerHello message (122 bytes, encryption level: Initial)
client Installed Handshake Write keys
client Installed Handshake Read keys
client Handled crypto frame at level Initial. encLevelChanged: true
client Queueing ACK because the first packet should be acknowledged.
client -> Sending packet 0x2 (1200 bytes) for connection (empty), Initial
client Long Header{Type: Initial, DestConnectionID: 0x526b8f82, SrcConnectionID: (empty), Token: 0x9c6786985f90d5a8cfcf67dd26b98d2e10337c8dc293e8ea9ac40094d0f6fdb5a978fd786c7285d2c1418236e1df084f9b217f586f0b344bd55e886bc42f2412872903a1d75ee9e7b8f0aeaf8c7a90ccfd68f2e6a3689abbe330a3d301c83f28c2, PacketNumber: 0x2, PacketNumberLen: 4, Length: 1088, Version: QUIC WG draft-22}
client -> &wire.AckFrame{LargestAcked: 0x0, LowestAcked: 0x0, DelayTime: 0s}
client <- Reading packet 0x0 (37 bytes) for connection (empty), Handshake
client Long Header{Type: Handshake, DestConnectionID: (empty), SrcConnectionID: 0x526b8f82, PacketNumber: 0x0, PacketNumberLen: 4, Length: 25, Version: QUIC WG draft-22}
client <- &wire.ConnectionCloseFrame{IsApplicationError:false, ErrorCode:0x178, ReasonPhrase:""}
client Peer closed session with error: CRYPTO_ERROR: tls: no application protocol
client Queueing ACK because the first packet should be acknowledged.
client -> Sending packet 0x0 (37 bytes) for connection (empty), Handshake
client Long Header{Type: Handshake, DestConnectionID: 0x526b8f82, SrcConnectionID: (empty), PacketNumber: 0x0, PacketNumberLen: 4, Length: 25, Version: QUIC WG draft-22}
client -> &wire.AckFrame{LargestAcked: 0x0, LowestAcked: 0x0, DelayTime: 0s}
client Connection (empty) closed.
muxer received a packet with an unexpected connection ID (empty)
panic: Get https://h3.test.com:8686/: CRYPTO_ERROR: tls: no application protocol

goroutine 6 [running]:
main.main.func1(0xc0000b9500, 0x95b800, 0xc0000b8c00, 0xc000026601, 0xc000026980, 0x7ffc8dd2f879, 0x19)
/data/yfq/quic-go/example/client/main.go:50 +0x434
created by main.main
/data/yfq/quic-go/example/client/main.go:47 +0x462
exit status 2
```

**Comment by keycodingyfq** [comment]
> Yeah, that's an old beta version too; Caddy 2 beta 6 has been out for a while now, which uses quic-go v0.12.1:
> 
> https://github.com/caddyserver/caddy/blob/bc738991b6234bf334855e1396919e79ef9791b8/go.mod#L16
> 
> I believe just using the latest beta should fix things up... if not, let us know.

the caddy server write log below
```
2019/10/23 16:53:29 Caddy 2 admin endpoint listening on localhost:2019
2019/10/23 16:53:29 [INFO][cache:0xc000155a90] Started certificate maintenance routine
2019/10/23 16:53:30 [WARNING] Stapling OCSP: no OCSP stapling for [*.miguvideo.com miguvideo.com]: parsing OCSP response: ocsp: error from server: unauthorized
2019/10/23 16:53:30 [INFO][miguvideo.com] Skipping automatic certificate management because one or more matching certificates are already loaded
2019/10/23 16:53:30 [INFO] Enabling automatic TLS certificate management for []
2019/10/23 16:53:30 [INFO] Enabling automatic HTTP->HTTPS redirects for [miguvideo.com]
2019/10/23 16:53:30 [INFO] Enabling experimental HTTP/3 listener on :8991
2019/10/23 16:53:30 server Listening for udp connections on [::]:8991
2019/10/23 16:53:30 [INFO] tls: Cleaned up storage unit(s)
2019/10/23 16:53:30 Caddy 2 serving initial configuration
2019/10/23 16:53:34 server <- Received Initial packet.
2019/10/23 16:53:34 server      Long Header{Type: Initial, DestConnectionID: 0x0054029502394a15e6, SrcConnectionID: (empty), Token: (empty), PacketNumber: 0x0, PacketNumberLen: 0, Length: 1181, Version: QUIC WG draft-22}
2019/10/23 16:53:34 server Changing connection ID to 0x255c6fc4.
2019/10/23 16:53:34 server -> Sending Retry
2019/10/23 16:53:34 server      Long Header{Type: Retry, DestConnectionID: (empty), SrcConnectionID: 0x255c6fc4, Token: 0x2189e9ff7b39d494416606c7434554b50dd4c4db0c339bb02bbe475c7b54d3db2c46fc17af4d5776e93ed3a96fd8c77bba4cba58bd4a5c68401e2babcc34a83633839cae59efead06635361a161c73f5fe8fb05374cf47c096e0863d1b, OrigDestConnectionID: 0x0054029502394a15e6, Version: QUIC WG draft-22}
2019/10/23 16:53:34 server <- Received Initial packet.
2019/10/23 16:53:34 server Changing connection ID to 0x7ca0320c.
2019/10/23 16:53:34 server <- Reading packet 0x1 (1200 bytes) for connection 0x255c6fc4, Initial
2019/10/23 16:53:34 server      Long Header{Type: Initial, DestConnectionID: 0x255c6fc4, SrcConnectionID: (empty), Token: 0x2189e9ff7b39d494416606c7434554b50dd4c4db0c339bb02bbe475c7b54d3db2c46fc17af4d5776e93ed3a96fd8c77bba4cba58bd4a5c68401e2babcc34a83633839cae59efead06635361a161c73f5fe8fb05374cf47c096e0863d1b, PacketNumber: 0x1, PacketNumberLen: 4, Length: 1092, Version: QUIC WG draft-22}
2019/10/23 16:53:34 server      <- &wire.CryptoFrame{Offset: 0x0, Data length: 0x166, Offset + Data length: 0x166}
2019/10/23 16:53:34 server Received ClientHello message (358 bytes, encryption level: Initial)
2019/10/23 16:53:34 server Received Transport Parameters: &handshake.TransportParameters{OriginalConnectionID: (empty), InitialMaxStreamDataBidiLocal: 0x80000, InitialMaxStreamDataBidiRemote: 0x80000, InitialMaxStreamDataUni: 0x80000, InitialMaxData: 0xc0000, MaxBidiStreamNum: 0, MaxUniStreamNum: 100, IdleTimeout: 30s, AckDelayExponent: 3, MaxAckDelay: 26ms}
2019/10/23 16:53:34 server Installed Handshake Read keys
2019/10/23 16:53:34 server Installed Handshake Write keys
2019/10/23 16:53:34 server Handled crypto frame at level Initial. encLevelChanged: false
2019/10/23 16:53:34 server Closing session with error: CRYPTO_ERROR: ALPN negotiation failed
2019/10/23 16:53:34 server      Queueing ACK because the first packet should be acknowledged.
2019/10/23 16:53:34 server -> Sending packet 0x0 (165 bytes) for connection 0x7ca0320c, Initial
2019/10/23 16:53:34 server      Long Header{Type: Initial, DestConnectionID: (empty), SrcConnectionID: 0x7ca0320c, Token: (empty), PacketNumber: 0x0, PacketNumberLen: 4, Length: 151, Version: QUIC WG draft-22}
2019/10/23 16:53:34 server      -> &wire.AckFrame{LargestAcked: 0x1, LowestAcked: 0x1, DelayTime: 0s}
2019/10/23 16:53:34 server      -> &wire.CryptoFrame{Offset: 0x0, Data length: 0x7a, Offset + Data length: 0x7a}
2019/10/23 16:53:34 server -> Sending packet 0x0 (37 bytes) for connection 0x7ca0320c, Handshake
2019/10/23 16:53:34 server      Long Header{Type: Handshake, DestConnectionID: (empty), SrcConnectionID: 0x7ca0320c, PacketNumber: 0x0, PacketNumberLen: 4, Length: 25, Version: QUIC WG draft-22}
2019/10/23 16:53:34 server      -> &wire.ConnectionCloseFrame{IsApplicationError:false, ErrorCode:0x178, ReasonPhrase:""}
2019/10/23 16:53:34 server Connection 0x7ca0320c closed.
2019/10/23 16:53:34 server Received 1 packets after sending CONNECTION_CLOSE. Retransmitting.
2019/10/23 16:53:34 server Received 2 packets after sending CONNECTION_CLOSE. Retransmitting.

```

**Comment by keycodingyfq** [comment]
> Yeah, that's an old beta version too; Caddy 2 beta 6 has been out for a while now, which uses quic-go v0.12.1:
> 
> https://github.com/caddyserver/caddy/blob/bc738991b6234bf334855e1396919e79ef9791b8/go.mod#L16
> 
> I believe just using the latest beta should fix things up... if not, let us know.

i think i had found the problem
in quic-go v0.12.1 the tlsConfig is init below
```
func (s *Server) ListenAndServeTLS(certFile, keyFile string) error {
	var err error
	certs := make([]tls.Certificate, 1)
	certs[0], err = tls.LoadX509KeyPair(certFile, keyFile)
	if err != nil {
		return err
	}
	// We currently only use the cert-related stuff from tls.Config,
	// so we don't need to make a full copy.
	config := &tls.Config{
		Certificates: certs,
	}
	return s.serveImpl(config, nil)
}
```

but in caddy v2 beta6 the tlsConfig is init below,may be this was caddy's bug?
```
unc (cp ConnectionPolicies) TLSConfig(ctx caddy.Context) (*tls.Config, error) {
	// set up each of the connection policies
	for i, pol := range cp {
		// matc
		for modName, rawMsg := range pol.Matchers {
			val, err := ctx.LoadModule("tls.handshake_match."+modName, rawMsg)
			if err != nil {
				return nil, fmt.Errorf("loading handshake matcher module '%s': %s", modName, err)
			}
			cp[i].matchers = append(cp[i].matchers, val.(ConnectionMatcher))
		}
		cp[i].Matchers = nil // allow GC to deallocate

		// certificate selector
		if pol.CertSelection != nil {
			val, err := ctx.LoadModuleInline("policy", "tls.certificate_selection", pol.CertSelection)
			if err != nil {
				return nil, fmt.Errorf("loading certificate selection module: %s", err)
			}
			cp[i].certSelector = val.(certmagic.CertificateSelector)
			cp[i].CertSelection = nil // allow GC to deallocate
		}
	}

	// pre-build standard TLS configs so we don't have to at handshake-time
	for i := range cp {
		err := cp[i].buildStandardTLSConfig(ctx)
		if err != nil {
			return nil, fmt.Errorf("connection policy %d: building standard TLS config: %s", i, err)
		}
	}

	// using ServerName to match policies is extremely common, especially in configs
	// with lots and lots of different policies; we can fast-track those by indexing
	// them by SNI, so we don't have to iterate potentially thousands of policies
	indexedBySNI := make(map[string]ConnectionPolicies)
	if len(cp) > 30 {
		for _, p := range cp {
			for _, m := range p.matchers {
				if sni, ok := m.(MatchServerName); ok {
					for _, sniName := range sni {
						indexedBySNI[sniName] = append(indexedBySNI[sniName], p)
					}
				}
			}
		}
	}

	return &tls.Config{
		GetConfigForClient: func(hello *tls.ClientHelloInfo) (*tls.Config, error) {
			// filter policies by SNI first, if possible, to speed things up
			// when there may be lots of policies
			possiblePolicies := cp
			if indexedPolicies, ok := indexedBySNI[hello.ServerName]; ok {
				possiblePolicies = indexedPolicies
			}

		policyLoop:
			for _, pol := range possiblePolicies {
				for _, matcher := range pol.matchers {
					if !matcher.Match(hello) {
						continue policyLoop
					}
				}
				return pol.stdTLSConfig, nil
			}

			return nil, fmt.Errorf("no server TLS configuration available for ClientHello: %+v", hello)
		},
	}, nil
}
```

**Comment by keycodingyfq** [comment]
finally i found caddy as http3 server can work correct too,it was my client not set the right alpn

**Comment by mholt** [comment]
Great, thanks for following up!
