### ISSUE TITLE
V2: "Secure Connection Failed" on reverse-proxying to Golang webservers on non-TLS ports

### ISSUE THREAD

**Issue by AbdelmalekIhdene** [caddyserver/caddy#2883]
### 1. My Caddy version (`caddy -version`):

7ff02f37b6cbdf8e73a47d94604672ca2f1f1aa7

### 2. How I run Caddy:

`caddy start --config ~/Caddyfile --adapter caddyfile `

#### a. System environment:

```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ admin@proxy: sudo ufw status
Status: active
To                         Action      From
--                         ------      ----
22/tcp                     ALLOW       Anywhere                  
80/tcp                     ALLOW       Anywhere                  
443/tcp                    ALLOW       Anywhere                  
22/tcp (v6)                ALLOW       Anywhere (v6)             
80/tcp (v6)                ALLOW       Anywhere (v6)             
443/tcp (v6)               ALLOW       Anywhere (v6)    
$ admin@node-one: sudo ufw status
Status: active
To                         Action      From
--                         ------      ----
22/tcp                     ALLOW       Anywhere                  
8080                       ALLOW       proxy           
22/tcp (v6)                ALLOW       Anywhere (v6)        
$ admin@node-one: curl -i localhost:8080
HTTP/1.1 200 OK
Date: Sat, 16 Nov 2019 23:43:36 GMT
Content-Length: 13
Content-Type: text/plain; charset=utf-8

Hello, World!
$ admin@proxy: curl -i node-one:8080
HTTP/1.1 200 OK
Date: Sat, 16 Nov 2019 23:44:09 GMT
Content-Length: 13
Content-Type: text/plain; charset=utf-8

Hello, World!
$ personal-laptop: curl -i https://mywebsite.com
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
```

#### b. Command:
N/A
#### c. Service/unit/compose file:
N/A
#### d. My complete Caddyfile:

```
mywebsite.com
reverse_proxy / {
	to node-one:8080 node-two:8080
	health_path /health
	health_status 200
	lb_policy random_choose 2
	transport http {
		read_buffer 4096
		tls
	}
}
```

### 3. The problem I'm having:

I have a reverse-proxy server running Caddy 2 and two nodes behind said proxy. I am trying to get load balancing to work. I am portforwarding TLS to 8080 but I get a protocol error for some odd reason also, Caddy is panicking. I also have health checks and they work. Moreover, I can curl from the proxy and get an answer back from the nodes.  Caddy is also proxying to port 33498 instead of port 8080 for some odd reason.

### 4. Error messages and/or full log output:
```
2019/11/16 23:48:32.219	INFO	http.log.access	handled request	{"request": {"method": "GET", "uri": "/", "proto": "HTTP/2.0", "remote_addr": "node-one:33498", "host": "mywebsite.com", "headers": {"Accept": ["*/*"], "User-Agent": ["curl/7.58.0"]}, "tls": {"resumed": false, "version": 772, "resumed": 4865, "proto": "h2", "proto_mutual": true, "server_name": "mywebsite.com"}}, "common_log": "node-one - - [16/Nov/2019:18:48:32 -0500] \"GET / HTTP/2.0\" 0 0", "latency": 0.00001644, "size": 0, "status": 0}
2019/11/16 18:48:32 http2: panic serving node-one:33498: invalid argument to Intn
goroutine 38 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc000010e68, 0xc000141f67, 0xc000211080)
	/usr/lib/go-1.13/src/net/http/h2_bundle.go:5706 +0x16b
panic(0xcc19e0, 0xf4d990)
	/usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b2
math/rand.(*Rand).Intn(0xc000092150, 0x0, 0x2)
	/usr/lib/go-1.13/src/math/rand/rand.go:169 +0x9c
math/rand.Intn(...)
	/usr/lib/go-1.13/src/math/rand/rand.go:329
github.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.RandomChoiceSelection.Select(0x2, 0xc0001bb460, 0x2, 0x4, 0xc0000db000, 0x443866d9d521e)
	/home/admin/caddy/modules/caddyhttp/reverseproxy/selectionpolicies.go:135 +0xb9
github.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.(*Handler).ServeHTTP(0xc0001b4b40, 0x7fef74ba5b98, 0xc0001bf5c0, 0xc0000db000, 0xf61400, 0xe588b0, 0x0, 0x0)
	/home/admin/caddy/modules/caddyhttp/reverseproxy/reverseproxy.go:242 +0x2e1
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1(0x7fef74ba5b98, 0xc0001bf5c0, 0xc0000db000, 0x0, 0x0)
	/home/admin/caddy/modules/caddyhttp/routes.go:151 +0x62
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0002a8020, 0x7fef74ba5b98, 0xc0001bf5c0, 0xc0000db000, 0xf61400, 0xc0002a8020)
	/home/admin/caddy/modules/caddyhttp/caddyhttp.go:532 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc0001bb040, 0x7fef74ba5b98, 0xc0001bf5c0, 0xc0000db000, 0xf61400, 0xe588b0, 0xc0000e1530, 0x0)
	/home/admin/caddy/modules/caddyhttp/subroute.go:71 +0x80
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1(0x7fef74ba5b98, 0xc0001bf5c0, 0xc0000db000, 0x0, 0x8)
	/home/admin/caddy/modules/caddyhttp/routes.go:151 +0x62
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00024bfc0, 0x7fef74ba5b98, 0xc0001bf5c0, 0xc0000db000, 0x203000, 0x203000)
	/home/admin/caddy/modules/caddyhttp/caddyhttp.go:532 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).enforcementHandler(0xc0001a7930, 0x7fef74ba5b98, 0xc0001bf5c0, 0xc0000db000, 0xf61400, 0xc00024bfc0, 0x40e698, 0x20)
	/home/admin/caddy/modules/caddyhttp/server.go:237 +0x9b
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).wrapPrimaryRoute.func1(0x7fef74ba5b98, 0xc0001bf5c0, 0xc0000db000, 0xd5ce20, 0xc00024bfe0)
	/home/admin/caddy/modules/caddyhttp/server.go:213 +0x5a
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00024bfe0, 0x7fef74ba5b98, 0xc0001bf5c0, 0xc0000db000, 0xc00024bfe0, 0xc00024bfc0)
	/home/admin/caddy/modules/caddyhttp/caddyhttp.go:532 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).executeCompositeRoute(0xc0001a7930, 0x7fef74ba5b98, 0xc0001bf5c0, 0xc0000db000, 0xc00000c1e0, 0x1, 0x4, 0xc000276900, 0xc000200e00)
	/home/admin/caddy/modules/caddyhttp/server.go:198 +0xff
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc0001a7930, 0x7fef74ba5b98, 0xc0001bf5c0, 0xc0000db000)
	/home/admin/caddy/modules/caddyhttp/server.go:135 +0x73d
net/http.serverHandler.ServeHTTP(0xc000100540, 0xf712a0, 0xc000010e68, 0xc0000dae00)
	/usr/lib/go-1.13/src/net/http/server.go:2802 +0xa4
net/http.initNPNRequest.ServeHTTP(0xf74360, 0xc000276060, 0xc000200e00, 0xc000100540, 0xf712a0, 0xc000010e68, 0xc0000dae00)
	/usr/lib/go-1.13/src/net/http/server.go:3365 +0x8d
net/http.(*http2serverConn).runHandler(0xc000211080, 0xc000010e68, 0xc0000dae00, 0xc00024be60)
	/usr/lib/go-1.13/src/net/http/h2_bundle.go:5713 +0x9f
created by net/http.(*http2serverConn).processHeaders
	/usr/lib/go-1.13/src/net/http/h2_bundle.go:5447 +0x4eb
```

### 5. What I already tried:
N/A
### 6. Links to relevant resources:
N/A
Thank you for your help and bless you for the work you are doing.

**Comment by mholt** [comment]
Thank you for the report! And thank you very much for trying Caddy 2 while it is still in beta! This is exactly why it is still in beta :)

The panic is because I stupidly forgot that in a call to `rand.Intn(i)`, `i` cannot be <= 0, and `i` is zero because it is used in a `for...range` loop, which of course starts at 0: https://github.com/caddyserver/caddy/blob/9fe54e1c6025a45cdd531c093bb94d193a8b91a0/modules/caddyhttp/reverseproxy/selectionpolicies.go#L131-L135

For the rest of this, though:

> I have a reverse-proxy server running Caddy 2 and two nodes behind said proxy. I am trying to get load balancing to work. I am portforwarding TLS to 8080 but I get a protocol error for some odd reason also, Caddy is panicking. I also have health checks and they work. Moreover, I can curl from the proxy and get an answer back from the nodes. Caddy is also proxying to port 33498 instead of port 8080 for some odd reason.

Can you please provide more details? How can I reproduce what you are seeing? (other than the panic, which I know how to fix)

**Comment by AbdelmalekIhdene** [comment]
Removing `lb_policy random_choose 2` fixed the error above, but now I am getting
```
2019/11/17 14:05:38.044	ERROR	http.log.error	tls: first record does not look like a TLS handshake	{"request": {"method": "GET", "uri": "/", "proto": "HTTP/2.0", "remote_addr": "node-one:54056", "host": "mywebsite.com", "headers": {"Accept-Encoding": ["gzip, deflate, br"], "Upgrade-Insecure-Requests": ["1"], "Te": ["trailers"], "User-Agent": ["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"], "Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"], "Accept-Language": ["en-CA,en-US;q=0.7,en;q=0.3"]}, "tls": {"resumed": false, "version": 772, "resumed": 4865, "proto": "h2", "proto_mutual": true, "server_name": "mywebsite.com"}}, "status": 502, "err_id": "e8gjvzdsm", "err_trace": "reverseproxy.(*Handler).ServeHTTP (reverseproxy.go:304)"}
2019/11/17 14:05:38.045	ERROR	http.log.access	handled request	{"request": {"method": "GET", "uri": "/", "proto": "HTTP/2.0", "remote_addr": "node-one:54056", "host": "mywebsite.com", "headers": {"Te": ["trailers"], "User-Agent": ["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"], "Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"], "Accept-Language": ["en-CA,en-US;q=0.7,en;q=0.3"], "Accept-Encoding": ["gzip, deflate, br"], "Upgrade-Insecure-Requests": ["1"]}, "tls": {"resumed": false, "version": 772, "resumed": 4865, "proto": "h2", "proto_mutual": true, "server_name": "mywebsite.com"}}, "common_log": "node-one - - [17/Nov/2019:09:05:38 -0500] \"GET / HTTP/2.0\" 502 0", "latency": 0.004899409, "size": 0, "status": 502}
2019/11/17 14:05:38.127	INFO	http.log.access	handled request	{"request": {"method": "GET", "uri": "/favicon.ico", "proto": "HTTP/2.0", "remote_addr": "node-one:54056", "host": "mywebsite.com", "headers": {"User-Agent": ["Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"], "Accept": ["image/webp,*/*"], "Accept-Language": ["en-CA,en-US;q=0.7,en;q=0.3"], "Accept-Encoding": ["gzip, deflate, br"], "Te": ["trailers"]}, "tls": {"resumed": false, "version": 772, "resumed": 4865, "proto": "h2", "proto_mutual": true, "server_name": "mywebsite.com"}}, "common_log": "node-one - - [17/Nov/2019:09:05:38 -0500] \"GET /favicon.ico HTTP/2.0\" 0 0", "latency": 0.00009264, "size": 0, "status": 0}
```
I am not getting a "Hello, World!" but I am getting this error
```
The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.
```
I will be trying to re-create this locally, but I'm pretty sure you need a domain to get TLS certificates so this is a tricky one.

**Comment by mholt** [comment]
@AbdelmalekIhdene This error message:

```
http.log.error	tls: first record does not look like a TLS handshake
```

Means that the backend (`node-one:8080` or `node-two:8080`) is not serving TLS. But your proxy transport is configured to use TLS:

```
transport http {
	tls
}
```

Hence, it doesn't work. You'll either need to enable TLS on the backend or disable it in your HTTP transport config.

**Comment by mholt** [comment]
Can you elaborate on the rest of your comments here? I guess, specifically this part:

> Caddy is also proxying to port 33498 instead of port 8080 for some odd reason.

**Comment by AbdelmalekIhdene** [comment]
Everything works properly now, no issues anymore.

**Comment by mholt** [comment]
Okay. Thanks for confirming. Sounds like it was simply a misconfiguration then.
