### ISSUE TITLE
v2: crash when matching a simple wildcard in header directive

### ISSUE THREAD

**Issue by gilbsgilbs** [caddyserver/caddy#3060]
Hi,

It is not possible to use a single wildcard in `header` directive to just test the presence of a given header:

```
@matcher {
    header foo *
}
respond @matcher "hello"
```

```
2020/02/19 18:51:34 http: panic serving [::1]:35788: runtime error: slice bounds out of range [1:0]
goroutine 52 [running]:
net/http.(*conn).serve.func1(0xc0001c21e0)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x1025cc0, 0xc00003a3a0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/caddyserver/caddy/v2/modules/caddyhttp.MatchHeader.Match(0xc0001fc240, 0xc000565c00, 0xc000110038)
	/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.14/modules/caddyhttp/matchers.go:376 +0x680
github.com/caddyserver/caddy/v2/modules/caddyhttp.MatcherSet.Match(0xc0005f2f90, 0x1, 0x1, 0xc000565c00, 0x0)
	/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.14/modules/caddyhttp/routes.go:270 +0x68
github.com/caddyserver/caddy/v2/modules/caddyhttp.MatcherSets.AnyMatch(0xc000103360, 0x1, 0x1, 0xc000565c00, 0x0)
	/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.14/modules/caddyhttp/routes.go:291 +0x75
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1(0x12b9380, 0xc00027c1c0, 0xc000565c00, 0x1, 0x1)
	/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.14/modules/caddyhttp/routes.go:202 +0x68
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000113140, 0x12b9380, 0xc00027c1c0, 0xc000565c00, 0x11574f0, 0x12a65e0)
	/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.14/modules/caddyhttp/caddyhttp.go:388 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc000103120, 0x12b9380, 0xc00027c1c0, 0xc000565c00, 0x12a65e0, 0x11574f0, 0xfda120, 0xa53d01)
	/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.14/modules/caddyhttp/subroute.go:74 +0x8a
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1(0x12b9380, 0xc00027c1c0, 0xc000565c00, 0x12a46a0, 0xc000103120)
	/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.14/modules/caddyhttp/routes.go:256 +0x5f
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0003c4090, 0x12b9380, 0xc00027c1c0, 0xc000565c00, 0x1, 0x1)
	/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.14/modules/caddyhttp/caddyhttp.go:388 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1(0x12b9380, 0xc00027c1c0, 0xc000565c00, 0xc0004774e8, 0x40c226)
	/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.14/modules/caddyhttp/routes.go:231 +0x121
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000103580, 0x12b9380, 0xc00027c1c0, 0xc000565c00, 0x7, 0x2)
	/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.14/modules/caddyhttp/caddyhttp.go:388 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).enforcementHandler(0xc00019e380, 0x12b9380, 0xc00027c1c0, 0xc000565c00, 0x12a65e0, 0xc000103580, 0xc0004775b0, 0x7ce53e)
	/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.14/modules/caddyhttp/server.go:261 +0x9b
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).wrapPrimaryRoute.func1(0x12b9380, 0xc00027c1c0, 0xc000565c00, 0xc0003c4060, 0xc000526540)
	/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.14/modules/caddyhttp/server.go:237 +0x5a
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0001035a0, 0x12b9380, 0xc00027c1c0, 0xc000565c00, 0xc000526500, 0xc000565b00)
	/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.14/modules/caddyhttp/caddyhttp.go:388 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc00019e380, 0x12b9380, 0xc00027c1c0, 0xc000565c00)
	/Users/matt/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.0.0-beta.14/modules/caddyhttp/server.go:192 +0x771
net/http.serverHandler.ServeHTTP(0xc00019e540, 0x12b9380, 0xc00027c1c0, 0xc000565a00)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0001c21e0, 0x12bc700, 0xc000116900)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384
```

An easy workaround is to use `**` instead of `*`, but that doesn't look very natural:

```
@matcher {
    header foo **
}
respond @matcher "hello"
```

**Comment by mholt** [comment]
Thanks for the report! I'm pretty busy this week with some things, but would you be able to perhaps look into this along with #3059? It should be a pretty simple fix. Probably just another condition here, or something: https://github.com/caddyserver/caddy/blob/0b09b070e54bca82ba399f43062c689a3d921f24/modules/caddyhttp/matchers.go#L381
