### ISSUE TITLE
v2: http2: panic at Single Let's Encrypt domain

### ISSUE THREAD

**Issue by Henrocker** [caddyserver/caddy#3248]
# My system
* Debian 10 amd64
* Caddy Version: `v2.0.0-rc.2 h1:7NOaxYrsnQ5D3rcLGn2UnLZHLfBpgrfM/JNTLhjCJ1c=` (binary taken from Release (https://github.com/caddyserver/caddy/releases/download/v2.0.0-rc.2/caddy_2.0.0-rc.2_linux_amd64.tar.gz)). I also tried master and built Caddy with go1.14.2, but same issue as below.

# Caddy startup command
```
rm ~/.config/caddy/autosave.json && /etc/caddy/caddy run --config /etc/caddy/CaddyfileTEST --adapter caddyfile
```

# Caddyfile content
```
harmoniks.de, www.harmoniks.de {
        tls my@mail.address
        root * /etc/caddy/html/harmoniks.de
        encode zstd gzip
        php_fastcgi unix//run/php/php7.4-fpm.sock
        try_files {path} {path}/index.php /index.php?{query}
        file_server
}
```

# Issue
Everytime I visit my website harmoniks.de, it gets served correctly, but http2 panics as seen in Caddy's logs:
```
$ /etc/caddy/caddy run --config /etc/caddy/CaddyfileTEST --adapter caddyfile
2020/04/10 09:46:38.869 INFO    using provided configuration    {"config_file": "/etc/caddy/CaddyfileTEST", "config_adapter": "caddyfile"}
2020/04/10 09:46:38.873 INFO    admin   admin endpoint started  {"address": "localhost:2019", "enforce_origin": false, "origins": ["localhost:2019"]}
2020/04/10 09:46:38.874 INFO    http    server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS {"server_name": "srv0", "https_port": 443}
2020/04/10 11:46:38 [INFO][cache:0xc00053eb90] Started certificate maintenance routine
2020/04/10 09:46:38.874 INFO    http    enabling automatic HTTP->HTTPS redirects        {"server_name": "srv0"}
2020/04/10 09:46:38.913 INFO    tls     cleaned up storage units
2020/04/10 09:46:38.914 INFO    http    enabling automatic TLS certificate management   {"domains": ["harmoniks.de", "www.harmoniks.de"]}
2020/04/10 09:46:38.932 INFO    autosaved config        {"file": "/root/.config/caddy/autosave.json"}
2020/04/10 09:46:38.932 INFO    serving initial configuration
2020/04/10 11:46:45 http2: panic serving [2001:470:1f0b:1de:5960:84f0:3453:34df]:50070: runtime error: invalid memory address or nil pointer dereference
goroutine 12 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc000a877c0, 0xc0009e7f8e, 0xc00023d800)
        net/http/h2_bundle.go:5713 +0x16b
panic(0x144d380, 0x2470800)
        runtime/panic.go:969 +0x166
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc0005c3560, 0x192e1e0, 0xc000a877c0, 0xc00010ac00)
        github.com/caddyserver/caddy/v2@v2.0.0-rc.2/modules/caddyhttp/server.go:203 +0x932
net/http.serverHandler.ServeHTTP(0xc0001ee620, 0x192e1e0, 0xc000a877c0, 0xc00010aa00)
        net/http/server.go:2807 +0xa3
net/http.initALPNRequest.ServeHTTP(0x19335a0, 0xc00086ce10, 0xc00087e700, 0xc0001ee620, 0x192e1e0, 0xc000a877c0, 0xc00010aa00)
        net/http/server.go:3381 +0x8d
net/http.(*http2serverConn).runHandler(0xc00023d800, 0xc000a877c0, 0xc00010aa00, 0xc00044a8c0)
        net/http/h2_bundle.go:5720 +0x8b
created by net/http.(*http2serverConn).processHeaders
        net/http/h2_bundle.go:5454 +0x4e1
```

**Comment by mholt** [comment]
Thanks for the report; fixed in 999ab22. Please try it from that commit to confirm! Build artifacts will be available shortly.
