### ISSUE TITLE
Cannot run Caddy (arm64) on Nvidia Tegra

### ISSUE THREAD

**Issue by hawkeye64** [caddyserver/caddy#3655]
```bash
SIGILL: illegal instruction
PC=0x427e70 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
github.com/klauspost/cpuid.getProcFeatures(0xfaafa0, 0x400007db00, 0x11dabff, 0xc, 0x400006be18, 0x421ea4, 0x216e6c0, 0x421ea0, 0x400006be28, 0x51a5c, ...)
	github.com/klauspost/cpuid@v1.3.0/cpuid_arm64.s:15 fp=0x400006bdd0 sp=0x400006bdd0 pc=0x427e70
github.com/klauspost/cpuid.addInfo(0x216e6c0)
	github.com/klauspost/cpuid@v1.3.0/detect_arm64.go:42 +0x20 fp=0x400006be00 sp=0x400006bdd0 pc=0x4231a0
github.com/klauspost/cpuid.Detect()
	github.com/klauspost/cpuid@v1.3.0/cpuid.go:289 +0x70 fp=0x400006be20 sp=0x400006be00 pc=0x421f30
github.com/klauspost/cpuid.init.0()
	github.com/klauspost/cpuid@v1.3.0/cpuid.go:272 +0x24 fp=0x400006be30 sp=0x400006be20 pc=0x421ea4
runtime.doInit(0x20d4720)
	runtime/proc.go:5420 +0x9c fp=0x400006be70 sp=0x400006be30 pc=0x51a5c
runtime.doInit(0x20e9620)
	runtime/proc.go:5415 +0x58 fp=0x400006beb0 sp=0x400006be70 pc=0x51a18
runtime.doInit(0x20e6820)
	runtime/proc.go:5415 +0x58 fp=0x400006bef0 sp=0x400006beb0 pc=0x51a18
runtime.doInit(0x20e6940)
	runtime/proc.go:5415 +0x58 fp=0x400006bf30 sp=0x400006bef0 pc=0x51a18
runtime.doInit(0x20d3a60)
	runtime/proc.go:5415 +0x58 fp=0x400006bf70 sp=0x400006bf30 pc=0x51a18
runtime.main()
	runtime/proc.go:190 +0x1b8 fp=0x400006bfd0 sp=0x400006bf70 pc=0x44828
runtime.goexit()
	runtime/asm_arm64.s:1148 +0x4 fp=0x400006bfd0 sp=0x400006bfd0 pc=0x74604

r0      0x216e6c0
r1      0x400006a380
r2      0x400006be00
r3      0x4
r4      0xfaafa0
r5      0x0
r6      0x11dabff
r7      0x59
r8      0xf
r9      0x4
r10     0x0
r11     0xd
r12     0x1
r13     0x802aaaa00aaaa
r14     0xf8
r15     0x0
r16     0x34
r17     0x68
r18     0x0
r19     0xd0
r20     0x400006bca8
r21     0x40001603a0
r22     0x4000002000
r23     0x0
r24     0x0
r25     0x0
r26     0x20d4748
r27     0x216e748
r28     0x4000000180
r29     0x400006bdc8
lr      0x4231a0
sp      0x400006bdd0
pc      0x427e70
fault   0x0
```
Error appears to come from `github.com/klauspost/cpuid.getProcFeatures` (see above)

```bash
$ lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               1
Model name:          Cortex-A57
Stepping:            r1p1
CPU max MHz:         1479.0000
CPU min MHz:         102.0000
BogoMIPS:            38.40
L1d cache:           32K
L1i cache:           48K
L2 cache:            2048K
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32
```
Running: https://github.com/fwessels/investigate-arm64

```bash
$ go test -v
=== RUN   TestMidr
SIGILL: illegal instruction
PC=0xe6410 m=0 sigcode=1

goroutine 18 [running]:
_/home/intelliview/investigate-arm64-master.getMidr(0x44200ba090, 0xb22fb, 0x1b26a0, 0x1b26e0, 0xf, 0x359d4, 0x27, 0x2d2, 0xb22e0, 0x4420088180, ...)
	/home/intelliview/investigate-arm64-master/cpuid_arm64.s:9 fp=0x442002cec0 sp=0x442002cec0 pc=0xe6410
_/home/intelliview/investigate-arm64-master.dumpMidr()
	/home/intelliview/investigate-arm64-master/detect_arm64.go:13 +0x18 fp=0x442002cf90 sp=0x442002cec0 pc=0xe5f38
_/home/intelliview/investigate-arm64-master.TestMidr(0x44200b80f0)
	/home/intelliview/investigate-arm64-master/detect_arm64_test.go:8 +0x18 fp=0x442002cfa0 sp=0x442002cf90 pc=0xe6318
testing.tRunner(0x44200b80f0, 0x13e970)
	/usr/lib/go-1.10/src/testing/testing.go:777 +0xb0 fp=0x442002cfc0 sp=0x442002cfa0 pc=0xb2390
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_arm64.s:1037 +0x4 fp=0x442002cfc0 sp=0x442002cfc0 pc=0x5f7f4
created by testing.(*T).Run
	/usr/lib/go-1.10/src/testing/testing.go:824 +0x25c

goroutine 1 [chan receive]:
testing.(*T).Run(0x44200b8000, 0x136485, 0x8, 0x13e970, 0x5f36b424)
	/usr/lib/go-1.10/src/testing/testing.go:825 +0x270
testing.runTests.func1(0x44200b8000)
	/usr/lib/go-1.10/src/testing/testing.go:1063 +0x54
testing.tRunner(0x44200b8000, 0x4420045dd0)
	/usr/lib/go-1.10/src/testing/testing.go:777 +0xb0
testing.runTests(0x442008a040, 0x1e3fe0, 0x3, 0x3, 0x5aa40)
	/usr/lib/go-1.10/src/testing/testing.go:1061 +0x27c
testing.(*M).Run(0x44200b6000, 0x0)
	/usr/lib/go-1.10/src/testing/testing.go:978 +0x14c
main.main()
	_testmain.go:46 +0x174

r0      0xe6300
r1      0x442002cb70
r2      0x442002cf40
r3      0x44200b80f0
r4      0x0
r5      0x21f06122
r6      0x0
r7      0x2d1
r8      0x71
r9      0xffffffffffffffff
r10     0x600e4
r11     0x0
r12     0x0
r13     0x441fffa2f8
r14     0x442009c080
r15     0x0
r16     0x442002cfa0
r17     0x442002cf60
r18     0x0
r19     0x0
r20     0x0
r21     0x0
r22     0x0
r23     0x0
r24     0x0
r25     0x0
r26     0x13e970
r27     0x203830
r28     0x4420088180
r29     0x0
lr      0xe5f38
sp      0x442002cec0
pc      0xe6410
fault   0x0
exit status 2
FAIL	_/home/intelliview/investigate-arm64-master	0.009s
```
and
```bash
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
Forgot to mention `caddy version` also gives same error, but it's 2.1.1 - downloaded from download page

**Comment by hawkeye64** [comment]
I downloaded https://github.com/caddyserver/caddy/releases/download/v2.2.0-rc.1/caddy_2.2.0-rc.1_linux_arm64.tar.gz and tested and appears to work properly.

**Comment by francislavoie** [comment]
> /usr/lib/go-1.10/src/testing/testing.go:824 +0x25c

Odd, it looks like that was built with Go 1.10? Caddy requires Go 1.14+

**Comment by hawkeye64** [comment]
@francislavoie No idea. This was downloaded from https://caddyserver.com/download, the above link is from that page

**Comment by mholt** [comment]
This is a duplicate of #3537 - which we fixed by downgrading for now.
