### ISSUE TITLE
lb_policy random_choose may failed when some upsteam are down

### ISSUE THREAD

**Issue by d-masson** [caddyserver/caddy#3810]
## Caddy version:
```
./caddy_linux_amd64 version
v2.2.1 h1:Q62GWHMtztnvyRU+KPOpw6fNfeCD3SkwH7SfT1Tgt2c=
```

### Caddyfile:
```
{
 debug
 admin localhost:2010
 auto_https disable_redirects
}

http://localhost:8443 {
    respond "ok"
}
http://localhost:8444 {
    respond "ok"
}

http://localhost:8442 {
    reverse_proxy /* {
        to http://localhost:8445 http://localhost:8443 http://localhost:8444
        lb_policy random_choose 2
        health_interval 1s
        health_path /
    }
}
```

### Run caddy:

```
./caddy_linux_amd64 run --config Caddyfile
```

### Test:

```
curl  -v http://localhost:8442
* About to connect() to localhost port 8442 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 8442 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8442
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

### Log ouput:
```
2020/10/19 10:36:50.774 INFO    http.handlers.reverse_proxy.health_checker.active       HTTP request failed     {"host": "localhost:8445", "error": "Get \"http://localhost:8445/\": dial tcp [::1]:8445: connect: connection refused"}
2020/10/19 10:36:51.105 DEBUG   http.stdlib     http: panic serving [::1]:45622: runtime error: invalid memory address or nil pointer dereference
goroutine 137 [running]:
net/http.(*conn).serve.func1(0xc00047cfa0)
        net/http/server.go:1800 +0x139
panic(0x1515b20, 0x25de6d0)
        runtime/panic.go:975 +0x3e3
github.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.leastRequests(0xc0001c6190, 0x2, 0x2, 0xc0001c6190)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/reverseproxy/selectionpolicies.go:402 +0x8b
github.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.RandomChoiceSelection.Select(0x2, 0xc0008560a0, 0x3, 0x4, 0xc0001ccf00, 0x75c2b21f5ca)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/reverseproxy/selectionpolicies.go:152 +0x11e
github.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.(*Handler).ServeHTTP(0xc00054e1e0, 0x7f4f9fa650e8, 0xc0008e50e0, 0xc0001ccf00, 0x1a18d40, 0x17d2d50, 0x0, 0x0)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/reverseproxy/reverseproxy.go:371 +0x3d4
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc0008562e0, 0x7f4f9fa650e8, 0xc0008e5020, 0xc0001ccf00, 0x1a18d40, 0x17d2d50, 0x0, 0x0)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/metrics.go:133 +0x537
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1(0x7f4f9fa650e8, 0xc0008e5020, 0xc0001ccf00, 0xc0005128e0, 0xc0008562e0)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/routes.go:259 +0x5a
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0005128e0, 0x7f4f9fa650e8, 0xc0008e5020, 0xc0001ccf00, 0x1, 0x0)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/caddyhttp.go:58 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1(0x7f4f9fa650e8, 0xc0008e5020, 0xc0001ccf00, 0x1, 0x1)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/routes.go:231 +0x121
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0005128c0, 0x7f4f9fa650e8, 0xc0008e5020, 0xc0001ccf00, 0x17d2d50, 0x1a18d40)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/caddyhttp.go:58 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc000821b80, 0x7f4f9fa650e8, 0xc0008e5020, 0xc0001ccf00, 0x1a18d40, 0x17d2d50, 0xffffffffffffff01, 0x1)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/subroute.go:74 +0x8a
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc000856340, 0x1a32820, 0xc0008d0620, 0xc0001ccf00, 0x1a18d40, 0x17d2d50, 0x0, 0x0)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/metrics.go:133 +0x537
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1(0x1a32820, 0xc0008d0620, 0xc0001ccf00, 0xc0005128a0, 0xc000856340)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/routes.go:259 +0x5a
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0005128a0, 0x1a32820, 0xc0008d0620, 0xc0001ccf00, 0x1, 0x1)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/caddyhttp.go:58 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1(0x1a32820, 0xc0008d0620, 0xc0001ccf00, 0xc00090d498, 0x40c976)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/routes.go:231 +0x121
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000856360, 0x1a32820, 0xc0008d0620, 0xc0001ccf00, 0x7, 0x2)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/caddyhttp.go:58 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).enforcementHandler(0xc0008030e0, 0x1a32820, 0xc0008d0620, 0xc0001ccf00, 0x1a18d40, 0xc000856360, 0x75c2b2190c6, 0x641e4ab)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/server.go:287 +0x9b
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).wrapPrimaryRoute.func1(0x1a32820, 0xc0008d0620, 0xc0001ccf00, 0xc00641e4ab, 0x75c2b2190c6)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/server.go:263 +0x5a
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000856380, 0x1a32820, 0xc0008d0620, 0xc0001ccf00, 0xc000251100, 0xc0001ccf00)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/caddyhttp.go:58 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc0008030e0, 0x1a32820, 0xc0008d0620, 0xc0001ccf00)
        github.com/caddyserver/caddy/v2@v2.2.1/modules/caddyhttp/server.go:204 +0x4b3
net/http.serverHandler.ServeHTTP(0xc0006ec000, 0x1a32820, 0xc0008d0620, 0xc0001ccd00)
        net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc00047cfa0, 0x1a390e0, 0xc0005eb380)
        net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
        net/http/server.go:2962 +0x35c
2020/10/19 10:36:51.769 INFO    http.handlers.reverse_proxy.health_checker.active       HTTP request failed     {"host": "localhost:8445", "error": "Get \"http://localhost:8445/\": dial tcp [::1]:8445: connect: connection refused"}
```

See Pull Request: https://github.com/caddyserver/caddy/pull/3811

**Comment by mholt** [comment]
Thanks for the fix!
