### ISSUE TITLE
Unable to use caching library when running caddy module

### ISSUE THREAD

**Issue by circa10a** [caddyserver/caddy#4421]
Hi, I'm trying to consume one my go libraries([go-geofence](https://github.com/circa10a/go-geofence/)) which uses [go-cache](https://github.com/patrickmn/go-cache/) under the covers. Seems caddy panics when go-caches attempts [set a mutex lock](https://github.com/patrickmn/go-cache/blob/master/cache.go#L121). I'm using this library in other places and works fine when running standalone. I'm not sure what's going on with caddy under the covers that would cause this. I've added logs, my caddy module and my caddyfile below.

OS: MacOS `12.0.1`
Go: `1.17.2`

FWIW, this is my first time writing a caddy module 😄 

**stack trace using `xcaddy`**

```log
2021/11/14 20:40:08 [INFO] Running [./caddy run]

2021/11/15 02:40:08.961 INFO    using adjacent Caddyfile
2021/11/15 02:40:09.121 WARN    input is not formatted with 'caddy fmt' {"adapter": "caddyfile", "file": "Caddyfile", "line": 2}
2021/11/15 02:40:09.122 INFO    admin   admin endpoint started  {"address": "tcp/localhost:2019", "enforce_origin": false, "origins": ["localhost:2019", "[::1]:2019", "127.0.0.1:2019"]}
2021/11/15 02:40:09.123 INFO    http    server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server {"server_name": "srv0", "http_port": 80}
2021/11/15 02:40:09.123 INFO    tls.cache.maintenance   started background certificate maintenance      {"cache": "0xc000398700"}
2021/11/15 02:40:09.123 DEBUG   http    starting server loop    {"address": "[::]:80", "http3": false, "tls": false}
2021/11/15 02:40:09.123 INFO    tls     cleaning storage unit   {"description": "FileStorage:/Users/circa10a/Library/Application Support/Caddy"}
2021/11/15 02:40:09.124 INFO    tls     finished cleaning storage units
2021/11/15 02:40:09.124 INFO    autosaved config (load with --resume flag)      {"file": "/Users/circa10a/Library/Application Support/Caddy/autosave.json"}
2021/11/15 02:40:09.124 INFO    serving initial configuration
2021/11/15 02:40:09.686 DEBUG   http.stdlib     http: panic serving [::1]:61003: runtime error: invalid memory address or nil pointer dereference
goroutine 81 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1801 +0xb9
panic({0x20bd5a0, 0x3098b60})
        runtime/panic.go:1047 +0x266
github.com/patrickmn/go-cache.(*cache).Get(0x0, {0x22b3d64, 0xc000026aa0})
        github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:121 +0x27
github.com/circa10a/go-geofence.(*Geofence).IsIPAddressNear(0xc00022ee10, {0x22b3d64, 0xe})
        github.com/circa10a/go-geofence@v0.1.2/geofence.go:121 +0x94
github.com/circa10a/caddy-geofence.CaddyGeofence.ServeHTTP({0x45d964b800, {0xc000123180, 0x20}, 0x3, 0xc00022ee10}, {0xae24058, 0xc0000e4330}, 0xc000026c18, {0x2565be0, 0xc0006a3f80})
        github.com/circa10a/caddy-geofence@v0.0.0-00010101000000-000000000000/main.go:129 +0x77
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc0006a3cc0, {0xae24058, 0xc0000e41e0}, 0xc000322500, {0x2565be0, 0xc0006a3f80})
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/metrics.go:133 +0x51f
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0xae24058, 0xc0000e41e0}, 0x2565be0)
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/routes.go:272 +0x3b
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x2565be0, {0xae24058, 0xc0000e41e0}, 0x0)
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/caddyhttp.go:58 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0xae24058, 0xc0000e41e0}, 0xc000322500)
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/routes.go:244 +0x322
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00012c6c0, {0xae24058, 0xc0000e41e0}, 0x2565be0)
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/caddyhttp.go:58 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc0006a3a00, {0xae24058, 0xc0000e41e0}, 0x6, {0x2565be0, 0xc0006a3f80})
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/subroute.go:74 +0x6d
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc0006a3ce0, {0xae24058, 0xc0000e4120}, 0xc000322500, {0x2565be0, 0xc0006a3f80})
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/metrics.go:133 +0x51f
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0xae24058, 0xc0000e4120}, 0x2565be0)
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/routes.go:272 +0x3b
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x2565be0, {0xae24058, 0xc0000e4120}, 0x0)
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/caddyhttp.go:58 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0xae24058, 0xc0000e4120}, 0xc000322500)
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/routes.go:244 +0x322
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00012c480, {0xae24058, 0xc0000e4120}, 0x2565be0)
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/caddyhttp.go:58 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc0006a37c0, {0xae24058, 0xc0000e4120}, 0x6, {0x2565be0, 0x23828b0})
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/subroute.go:74 +0x6d
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc0006a3dc0, {0x25797a8, 0xc0005b6380}, 0xc000322500, {0x2565be0, 0x23828b0})
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/metrics.go:133 +0x51f
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x25797a8, 0xc0005b6380}, 0x2565be0)
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/routes.go:272 +0x3b
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x2565be0, {0x25797a8, 0xc0005b6380}, 0x2)
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/caddyhttp.go:58 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x25797a8, 0xc0005b6380}, 0xc000322500)
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/routes.go:244 +0x322
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x1344b66, {0x25797a8, 0xc0005b6380}, 0x228a6ea)
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/caddyhttp.go:58 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).enforcementHandler(0xc00022ff80, {0x25797a8, 0xc0005b6380}, 0xc000027458, {0x2565be0, 0xc0006a3de0})
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/server.go:298 +0x252
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).wrapPrimaryRoute.func1({0x25797a8, 0xc0005b6380}, 0x1096a77)
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/server.go:274 +0x3b
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00025f080, {0x25797a8, 0xc0005b6380}, 0xc000322500)
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/caddyhttp.go:58 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc0002b79e0, {0x25797a8, 0xc0005b6380}, 0xc000322500)
        github.com/caddyserver/caddy/v2@v2.4.6/modules/caddyhttp/server.go:210 +0x846
net/http.serverHandler.ServeHTTP({0xc00022f6b0}, {0x25797a8, 0xc0005b6380}, 0xc000322300)
        net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc0006b2460, {0x25864f8, 0xc000408060})
        net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
        net/http/server.go:3033 +0x4e8
```

**my `Caddyfile`**

```
{
        debug
        order geofence before respond
}
localhost:80
respond /api/test 200
route /* {
        geofence {
                cache_ttl 5m
                ip_stack_api_token redacted
                sensitivity 3
        }
}
```

**my caddy module**

```go
package caddygeofence

import (
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/caddyserver/caddy/v2"
	"github.com/caddyserver/caddy/v2/caddyconfig/caddyfile"
	"github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile"
	"github.com/caddyserver/caddy/v2/modules/caddyhttp"
	"github.com/circa10a/go-geofence"
)

// CaddyGeofence
type CaddyGeofence struct {
	CacheTTL        time.Duration `json:"cache_ttl,omitempty"`
	IPStackAPIToken string        `json:"ip_stack_api_token,omitempty"`
	Sensitivity     int           `json:"sensitivity,omitempty"`
	GeofenceClient  *geofence.Geofence
}

func init() {
	caddy.RegisterModule(CaddyGeofence{})
	httpcaddyfile.RegisterHandlerDirective("geofence", parseCaddyfile)
}

// CaddyModule returns the Caddy module information.
func (CaddyGeofence) CaddyModule() caddy.ModuleInfo {
	return caddy.ModuleInfo{
		ID:  "http.handlers.geofence",
		New: func() caddy.Module { return new(CaddyGeofence) },
	}
}

// isPrivateAddress checks if remote address is from known private ip space
func isPrivateAddress(addr string) bool {
	return strings.HasPrefix(addr, "192.") ||
		strings.HasPrefix(addr, "172.") ||
		strings.HasPrefix(addr, "10.") ||
		strings.HasPrefix(addr, "[::1]")
}

// Provision implements caddy.Provisioner.
func (cg *CaddyGeofence) Provision(ctx caddy.Context) error {
	if cg.IPStackAPIToken == "" {
		return fmt.Errorf("IP Stack API token not set")
	}
	// Set cache to never expire if not specified
	if cg.CacheTTL == 0 {
		cg.CacheTTL = -1
	}
	// Set sensitivity to mid range if not set
	if cg.Sensitivity == 0 {
		cg.Sensitivity = 3
	}
	return nil
}

// Validate validates that the module has a usable config.
func (cg CaddyGeofence) Validate() error {
	return nil
}

// UnmarshalCaddyfile implements caddyfile.Unmarshaler.
func (cg *CaddyGeofence) UnmarshalCaddyfile(d *caddyfile.Dispenser) error {
	for d.Next() {
		if d.NextArg() {
			return d.ArgErr()
		}
		// Validate args
		for nesting := d.Nesting(); d.NextBlock(nesting); {
			switch d.Val() {
			case "cache_ttl":
				if !d.NextArg() {
					return d.ArgErr()
				}
				// Setup cache
				cacheTTL, err := time.ParseDuration(d.Val())
				if err != nil {
					return err
				}
				cg.CacheTTL = cacheTTL
			case "ip_stack_api_token":
				if !d.NextArg() {
					return d.ArgErr()
				}
				cg.IPStackAPIToken = d.Val()
			case "sensitivity":
				if !d.NextArg() {
					return d.ArgErr()
				}
				sensitivity, err := strconv.Atoi(d.Val())
				if err != nil {
					return err
				}
				cg.Sensitivity = sensitivity
			}
		}
	}
	// Setup client
	geofenceClient, err := geofence.New("", cg.IPStackAPIToken, cg.Sensitivity)
	if err != nil {
		return err
	}
	cg.GeofenceClient = geofenceClient
	// Setup cache
	cg.GeofenceClient.CreateCache(cg.CacheTTL)
	return nil
}

// parseCaddyfile unmarshals tokens from h into a new Middleware.
func parseCaddyfile(h httpcaddyfile.Helper) (caddyhttp.MiddlewareHandler, error) {
	var cg CaddyGeofence
	err := cg.UnmarshalCaddyfile(h.Dispenser)
	return cg, err
}

// ServeHTTP implements caddyhttp.MiddlewareHandler.
func (cg CaddyGeofence) ServeHTTP(w http.ResponseWriter, r *http.Request, next caddyhttp.Handler) error {
	//remoteAddr := r.RemoteAddr
	// If known private ip, skip
	// if isPrivateAddress(remoteAddr) {
	// 	return next.ServeHTTP(w, r)
	// }
	// Check if address is nearby
	isAddressNear, err := cg.GeofenceClient.IsIPAddressNear("8.8.8.8")
	if err != nil {
		return err
	}
	// If remote address is not nearby, reject the request
	if !isAddressNear {
		return caddyhttp.Error(http.StatusForbidden, nil)
	}
	return next.ServeHTTP(w, r)
}

// Interface guards
var (
	_ caddy.Provisioner           = (*CaddyGeofence)(nil)
	_ caddy.Validator             = (*CaddyGeofence)(nil)
	_ caddyhttp.MiddlewareHandler = (*CaddyGeofence)(nil)
	_ caddyfile.Unmarshaler       = (*CaddyGeofence)(nil)
)
```

**Comment by circa10a** [comment]
Not sure if related, but I skip the cache creation, my module produces this error when `ServeHTTP()` executes:

```
2021/11/15 02:48:57.208 ERROR   http.log.error  Incorrect internal state        {"request": {"remote_addr": "[::1]:61049", "proto": "HTTP/1.1", "method": "GET", "host": "localhost", "uri": "/", "headers": {"User-Agent": ["curl/7.77.0"], "Accept": ["*/*"]}}, "duration": 0.00003107}
```

**Comment by francislavoie** [comment]
You should not do any runtime setup of your module in `UnmarshalCaddyfile`. The job of `UnmarshalCaddyfile` is to fill the struct such that the JSON tagged struct fields can be exported to JSON, a.k.a. adapting the config to JSON.

Your setup needs to happen in `Provision` instead, which is when Caddy actually prepares the module to run.

Caddy _actually_ runs from a JSON config, not directly from the Caddyfile.

https://caddyserver.com/docs/architecture

**Comment by circa10a** [comment]
Thank you for the quick response!
