### ISSUE TITLE
Using a .contains() expression matcher with {tls_client_subject} causes a panic

### ISSUE THREAD

**Issue by other-ryan** [caddyserver/caddy#4832]
Hello,

I seem to have stumbled upon a bug where trying to use a `.contains()` with `{tls_client_subject}` matcher in my Caddyfile causes caddy to panic. I'd like to be able to do a validation on the client cert--if the client certificate subject contains a string I'm looking for, then let the request through.

Here's an example Caddfyfile:
```caddyfile
{
    debug
}

https://caddy.localhost {
    tls caddy.pem caddy.key {
        client_auth {
            mode                   require_and_verify
            trusted_ca_cert_file   myCA.pem
        }
    }
    @trusted {
		expression {tls_client_subject}.contains("CN=permitted_client.localhost")
    }
    route {
		respond @trusted "Hello {tls_client_subject}"
    }
}
```

The client certificate being presented during the request has the Subject: `CN=permitted_client.localhost,L=San Francisco,ST=California,C=US`

This results in a panic:
```
2022/06/08 22:15:45.056 DEBUG   tls.handshake   choosing certificate    {"identifier": "caddy.localhost", "num_choices": 1}
2022/06/08 22:15:45.056 DEBUG   tls.handshake   custom certificate selection results    {"identifier": "caddy.localhost", "subjects": ["caddy.localhost"], "managed": false, "issuer_key": "", "hash": "fbe046e2b1bbe024a057908b1df62bce9488e27d4db7a9aed5761fe20002d2f6"}
2022/06/08 22:15:45.056 DEBUG   tls.handshake   matched certificate in cache    {"subjects": ["caddy.localhost"], "managed": false, "expiration": "2022/07/08 21:24:51.000", "hash": "fbe046e2b1bbe024a057908b1df62bce9488e27d4db7a9aed5761fe20002d2f6"}
2022/06/08 22:15:45.059 DEBUG   http.stdlib     http2: panic serving 127.0.0.1:52772: runtime error: invalid memory address or nil pointer dereference
goroutine 51 [running]:
net/http.(*http2serverConn).runHandler.func1()
        net/http/h2_bundle.go:5896 +0x120
panic({0x101f72d40, 0x102d05f50})
        runtime/panic.go:838 +0x204
github.com/caddyserver/caddy/v2/modules/caddyhttp.MatchExpression.Match({{0x1400014f7c0, 0x48}, {0x14000180230, 0x63}, {0x102175bb8, 0x14000911380}, {0x10217a818, 0x102d71c50}}, 0x1400027a100)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/celmatcher.go:143 +0xb4
github.com/caddyserver/caddy/v2/modules/caddyhttp.MatcherSet.Match(...)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/routes.go:286
github.com/caddyserver/caddy/v2/modules/caddyhttp.MatcherSets.AnyMatch({0x14000995d28?, 0x1, 0x0?}, 0x0?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/routes.go:307 +0xd4
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x10a4a8c98, 0x140001b7c50}, 0x1400027a100)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/routes.go:202 +0x60
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x14000339440?, {0x10a4a8c98?, 0x140001b7c50?}, 0x10217a4d8?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/caddyhttp.go:57 +0x3c
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0x140007bf820, {0x10a4a8c98, 0x140001b7c50}, 0x6?, {0x10217a4d8, 0x10216dad0})
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/subroute.go:74 +0x70
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0x14000921c40, {0x10a4a8c98?, 0x140001b77a0}, 0x1400027a100, {0x10217a4d8, 0x10216dad0})
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/metrics.go:132 +0x4b4
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x10a4a8c98?, 0x140001b77a0?}, 0x14000921c40?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/routes.go:272 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x10217a4d8?, {0x10a4a8c98?, 0x140001b77a0?}, 0x0?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/caddyhttp.go:57 +0x3c
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x10a4a8c98, 0x140001b77a0}, 0x1400027a100)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/routes.go:244 +0x320
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x14000339200?, {0x10a4a8c98?, 0x140001b77a0?}, 0x10217a4d8?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/caddyhttp.go:57 +0x3c
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0x140007bf760, {0x10a4a8c98, 0x140001b77a0}, 0x6?, {0x10217a4d8, 0x10216dad0})
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/subroute.go:74 +0x70
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0x14000921c80, {0x102183ec0?, 0x140002c0020}, 0x1400027a100, {0x10217a4d8, 0x10216dad0})
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/metrics.go:132 +0x4b4
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x102183ec0?, 0x140002c0020?}, 0x14000921c80?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/routes.go:272 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x10217a4d8?, {0x102183ec0?, 0x140002c0020?}, 0x100cd4854?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/caddyhttp.go:57 +0x3c
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x102183ec0, 0x140002c0020}, 0x1400027a100)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/routes.go:244 +0x320
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x14000524120?, {0x102183ec0?, 0x140002c0020?}, 0x102165ac0?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/caddyhttp.go:57 +0x3c
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).enforcementHandler(0x0?, {0x102183ec0?, 0x140002c0020?}, 0x1400027a100?, {0x10217a4d8?, 0x14000921ca0?})
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/server.go:318 +0x1ac
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).wrapPrimaryRoute.func1({0x102183ec0?, 0x140002c0020?}, 0x140002de578?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/server.go:294 +0x44
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x1400015bc30?, {0x102183ec0?, 0x140002c0020?}, 0x1400027a100?)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/caddyhttp.go:57 +0x3c
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0x14000274000, {0x102183ec0, 0x140002c0020}, 0x1400027a100)
        github.com/caddyserver/caddy/v2@v2.5.1/modules/caddyhttp/server.go:230 +0x840
net/http.serverHandler.ServeHTTP({0x0?}, {0x102183ec0, 0x140002c0020}, 0x140000e6300)
        net/http/server.go:2916 +0x3fc
net/http.initALPNRequest.ServeHTTP({{0x102185790?, 0x140002781b0?}, 0x14000114000?, {0x140001477a0?}}, {0x102183ec0, 0x140002c0020}, 0x140000e6300)
        net/http/server.go:3523 +0x1f8
net/http.(*http2serverConn).runHandler(0x0?, 0x0?, 0x0?, 0x0?)
        net/http/h2_bundle.go:5903 +0x74
created by net/http.(*http2serverConn).processHeaders
        net/http/h2_bundle.go:5633 +0x514
```

If I change the matcher to use `==`, the request goes through as expected:
```caddyfile
expression {tls_client_subject} == "CN=permitted_client.localhost,L=San Francisco,ST=California,C=US"
```

```
$ curl --key permitted_client.key --cert permitted_client.pem https://caddy.localhost
  Hello CN=permitted_client.localhost,L=San Francisco,ST=California,C=US
```

One curious "workaround" I stumbled on is if I add a second expression to the named matcher, the request works as expected!
This example adds `expression {method} != ""`
```caddyfile
https://caddy.localhost {
    tls CA/caddy.pem CA/caddy.key {
        client_auth {
            mode                   require_and_verify
            trusted_ca_cert_file   CA/myCA.pem
        }
    }
    @trusted {
		expression {tls_client_subject}.contains("CN=permitted_client.localhost")
		expression {method} != ""
    }
    route {
		respond @trusted "Hello {tls_client_subject}"
    }
}
```
results in:
```
$ curl --key permitted_client.key --cert permitted_client.pem https://caddy.localhost
  Hello CN=permitted_client.localhost,L=San Francisco,ST=California,C=US
```

I'm seeing this on caddy version v2.5.1

**Comment by mholt** [comment]
Oh, I guess that's what we get for ignoring the error here:

https://github.com/caddyserver/caddy/blob/7f9b1f43c9f8c7d0f4ca9271090cae92103232c7/modules/caddyhttp/celmatcher.go#L140-L143

Not sure if we did that on purpose, but if so I would expect a comment explaining why.

Off-hand, though, I am not sure as to the pecularities of the behavior you're observing.

**Comment by mholt** [comment]
I assume commit 1498132 will fix the panic, but I can't really explain why you're getting one in the first place without digging more.

**Comment by other-ryan** [comment]
@mholt thanks for taking a look. I just built caddy off that commit and I'm now properly getting an error message in the logs:

```
2022/06/08 23:25:38.784 ERROR   http.matchers.expression        evaluating expression   {"error": "internal error: interface conversion: caddyhttp.celPkixName is not traits.Receiver: missing method Receive"}
```

It is curious that adding a second matcher gets this to work properly.

**Comment by other-ryan** [comment]
Oh. I think i just realized why adding a second expression in the matcher "fixes" it, the first expression is being ignored I'm guessing so this is still broken. Is `{tls_client_subject}.contains("CN=permitted_client.localhost")` actually supposed to be supported?

**Comment by mholt** [comment]
Thanks for testing it!

I think you're the first person to try this. Looks like we need to implement a Receiver interface for that type so it can receive a method call.

**Comment by other-ryan** [comment]
@mholt thanks a bunch for that clue. That lit a lightbulb up in my head that I could easily do this with `map`:

```
map {tls_client_subject} {client} {
    ~^CN=permitted_client[.]localhost.+ "trusted"
    default "not_trusted"
}

@trusted {
    expression {client} == "trusted"
}

route {
    respond @trusted "Hello {tls_client_subject}"
}
```

This works rather well! Cheers!

**Comment by francislavoie** [comment]
Nice! Clever solution.

FYI you can save a couple lines by using the single-line matcher syntax.

```
@trusted expression {client} == "trusted"
```

**Comment by mholt** [comment]
Here's a condensed version:

```
map {tls_client_subject} {client} {
    ~^CN=permitted_client[.]localhost.+ "trusted"
    default "not_trusted"
}

@trusted vars client "trusted"
respond @trusted "Hello {tls_client_subject}"
```

Ref: https://caddyserver.com/docs/caddyfile/matchers#vars

(Although, having tested this, and upon re-reading the docs, I feel like it should work more like what the docs show, with the variable name in placeholder braces, i.e. `{client}` not `client`... will have to look into that... hmm.)

**Comment by other-ryan** [comment]
Neat. Thanks for the tips!
