### ISSUE TITLE
Error renewing TLS certificate via dns-01 (Azure DNS)

### ISSUE THREAD

**Issue by pascalgn** [caddyserver/caddy#4881]
I am getting the following error in Caddy, it fails to renew the certificates:

```
2022/07/12 16:43:44 panic: certificate worker: runtime error: slice bounds out of range [:-10]
goroutine 53 [running]:
github.com/caddyserver/certmagic.(*jobManager).worker.func1()
	github.com/caddyserver/certmagic@v0.15.2/async.go:58 +0x65
panic({0x15e53a0, 0xc000211428})
	runtime/panic.go:1038 +0x215
github.com/libdns/azure.generateRecordSetName(...)
	github.com/libdns/azure@v0.1.0/client.go:153
github.com/libdns/azure.(*Provider).createOrUpdateRecord(0xc00007dd40, {0x19ab778, 0xc000115920}, {0xc000813120, 0x19}, {{0x0, 0x0}, {0x16989dc, 0x3}, {0xc000041c80, ...}, ...}, ...)
	github.com/libdns/azure@v0.1.0/client.go:137 +0x618
github.com/libdns/azure.(*Provider).createRecord(...)
	github.com/libdns/azure@v0.1.0/client.go:79
```

The config used:

```
  "apps": {
    "http": {
      "http_port": 8008,
      "https_port": 8443,
      "servers": {
        "server-1": {
          "listen": [":8443"],
          "routes": [
            {
              "match": [
                {
                  "host": [
                    "sub.my-domain.com",
                    "*.sub.my-domain.com"
                  ]
                }
              ],
```

Full logs, after I enabled DEBUG logging:

```
{"level":"info","ts":1657644222.8169122,"msg":"using provided configuration","config_file":"/etc/caddy/caddy.json","config_adapter":""}
{"level":"info","ts":1657644222.8186846,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
{"level":"info","ts":1657644222.8206086,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"server-1"}
{"level":"info","ts":1657644222.8209085,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00037c8c0"}
{"level":"debug","ts":1657644222.822209,"logger":"http","msg":"starting server loop","address":"[::]:8443","http3":false,"tls":true}
{"level":"debug","ts":1657644222.8223045,"logger":"http","msg":"starting server loop","address":"[::]:8008","http3":false,"tls":false}
{"level":"info","ts":1657644222.8235946,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["sub.my-domain.com","*.sub.my-domain.com"]}
{"level":"warn","ts":1657644223.1221344,"logger":"tls","msg":"stapling OCSP","error":"no OCSP stapling for [sub.my-domain.com]: parsing OCSP response: ocsp: error from server: unauthorized"}
{"level":"debug","ts":1657644223.1221895,"logger":"tls.cache","msg":"added certificate to cache","subjects":["sub.my-domain.com"],"expiration":1657607897,"managed":true,"issuer_key":"acme-v02.api.letsencrypt.org-directory","hash":"b95461cf76c7e60b19910c941c90994834a8dfe3f094fbea06918ac53be25066","cache_size":1,"cache_capacity":10000}
{"level":"info","ts":1657644223.2597196,"logger":"tls.renew","msg":"acquiring lock","identifier":"sub.my-domain.com"}
{"level":"info","ts":1657644223.308029,"logger":"tls.renew","msg":"lock acquired","identifier":"sub.my-domain.com"}
{"level":"info","ts":1657644223.354255,"logger":"tls.renew","msg":"renewing certificate","identifier":"sub.my-domain.com","remaining":-36326.35425076}
{"level":"warn","ts":1657644223.411424,"logger":"tls","msg":"stapling OCSP","error":"no OCSP stapling for [*.sub.my-domain.com]: parsing OCSP response: ocsp: error from server: unauthorized"}
{"level":"debug","ts":1657644223.411468,"logger":"tls.cache","msg":"added certificate to cache","subjects":["*.sub.my-domain.com"],"expiration":1657607891,"managed":true,"issuer_key":"acme-v02.api.letsencrypt.org-directory","hash":"9ab31c6b99e25bea416b8bfd6fc0f7849dffdda9e868102d7ef8e2445dde7aa2","cache_size":2,"cache_capacity":10000}
{"level":"error","ts":1657644223.4117227,"msg":"unable to autosave config","file":"/config/caddy/autosave.json","error":"open /config/caddy/autosave.json: permission denied"}
{"level":"info","ts":1657644223.4117808,"msg":"serving initial configuration"}
{"level":"info","ts":1657644223.4118085,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/var/caddy_storage"}
{"level":"info","ts":1657644223.5391138,"logger":"tls.renew","msg":"acquiring lock","identifier":"*.sub.my-domain.com"}
{"level":"info","ts":1657644223.597876,"logger":"tls.renew","msg":"lock acquired","identifier":"*.sub.my-domain.com"}
{"level":"info","ts":1657644223.662691,"logger":"tls.renew","msg":"renewing certificate","identifier":"*.sub.my-domain.com","remaining":-36332.662687383}
{"level":"info","ts":1657644223.6941898,"logger":"tls.issuance.acme","msg":"waiting on internal rate limiter","identifiers":["sub.my-domain.com"],"ca":"https://acme-v02.api.letsencrypt.org/directory","account":""}
{"level":"info","ts":1657644223.6942225,"logger":"tls.issuance.acme","msg":"done waiting on internal rate limiter","identifiers":["sub.my-domain.com"],"ca":"https://acme-v02.api.letsencrypt.org/directory","account":""}
{"level":"info","ts":1657644223.8568635,"logger":"tls.issuance.acme","msg":"waiting on internal rate limiter","identifiers":["*.sub.my-domain.com"],"ca":"https://acme-v02.api.letsencrypt.org/directory","account":""}
{"level":"info","ts":1657644223.8569117,"logger":"tls.issuance.acme","msg":"done waiting on internal rate limiter","identifiers":["*.sub.my-domain.com"],"ca":"https://acme-v02.api.letsencrypt.org/directory","account":""}
{"level":"info","ts":1657644223.8802624,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"debug","ts":1657644224.1592486,"logger":"tls.issuance.acme.acme_client","msg":"http request","method":"GET","url":"https://acme-v02.api.letsencrypt.org/directory","headers":{"User-Agent":["Caddy/2.4.6 CertMagic acmez (linux; amd64)"]},"response_headers":{"Cache-Control":["public, max-age=0, no-cache"],"Content-Length":["658"],"Content-Type":["application/json"],"Date":["Tue, 12 Jul 2022 16:43:44 GMT"],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]},"status_code":200}
{"level":"debug","ts":1657644224.2986534,"logger":"tls.issuance.acme.acme_client","msg":"http request","method":"HEAD","url":"https://acme-v02.api.letsencrypt.org/acme/new-nonce","headers":{"User-Agent":["Caddy/2.4.6 CertMagic acmez (linux; amd64)"]},"response_headers":{"Cache-Control":["public, max-age=0, no-cache"],"Date":["Tue, 12 Jul 2022 16:43:44 GMT"],"Link":["<https://acme-v02.api.letsencrypt.org/directory>;rel=\"index\""],"Replay-Nonce":["01020O3aotkqeuzn59v0xXmKFqlHiftTt6NdWxPOuaUJdYQ"],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]},"status_code":200}
{"level":"debug","ts":1657644224.524305,"logger":"tls.issuance.acme.acme_client","msg":"http request","method":"POST","url":"https://acme-v02.api.letsencrypt.org/acme/new-order","headers":{"Content-Type":["application/jose+json"],"User-Agent":["Caddy/2.4.6 CertMagic acmez (linux; amd64)"]},"response_headers":{"Boulder-Requester":["113050068"],"Cache-Control":["public, max-age=0, no-cache"],"Content-Length":["349"],"Content-Type":["application/json"],"Date":["Tue, 12 Jul 2022 16:43:44 GMT"],"Link":["<https://acme-v02.api.letsencrypt.org/directory>;rel=\"index\""],"Location":["https://acme-v02.api.letsencrypt.org/acme/order/113050068/106113910026"],"Replay-Nonce":["0102tirzsN-U2ZmNMWMiyvLRYkTB3TBXwSk0B0xpAr7Q7E4"],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]},"status_code":201}
{"level":"debug","ts":1657644224.6147797,"logger":"tls.issuance.acme.acme_client","msg":"http request","method":"HEAD","url":"https://acme-v02.api.letsencrypt.org/acme/new-nonce","headers":{"User-Agent":["Caddy/2.4.6 CertMagic acmez (linux; amd64)"]},"response_headers":{"Cache-Control":["public, max-age=0, no-cache"],"Date":["Tue, 12 Jul 2022 16:43:44 GMT"],"Link":["<https://acme-v02.api.letsencrypt.org/directory>;rel=\"index\""],"Replay-Nonce":["0001GMCDedyzyCdDvVm2EssThZW-3uayc-p9rsYTw2lmcKQ"],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]},"status_code":200}
{"level":"debug","ts":1657644224.6977396,"logger":"tls.issuance.acme.acme_client","msg":"http request","method":"POST","url":"https://acme-v02.api.letsencrypt.org/acme/authz-v3/129755593806","headers":{"Content-Type":["application/jose+json"],"User-Agent":["Caddy/2.4.6 CertMagic acmez (linux; amd64)"]},"response_headers":{"Boulder-Requester":["113050068"],"Cache-Control":["public, max-age=0, no-cache"],"Content-Length":["808"],"Content-Type":["application/json"],"Date":["Tue, 12 Jul 2022 16:43:44 GMT"],"Link":["<https://acme-v02.api.letsencrypt.org/directory>;rel=\"index\""],"Replay-Nonce":["0102wBUPWWEYCYm5NI2k7EunBZCfbbqXKWvG7cMJFA-Z_T0"],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]},"status_code":200}
{"level":"debug","ts":1657644224.6979387,"logger":"tls.issuance.acme.acme_client","msg":"no solver configured","challenge_type":"tls-alpn-01"}
{"level":"debug","ts":1657644224.6979518,"logger":"tls.issuance.acme.acme_client","msg":"no solver configured","challenge_type":"http-01"}
{"level":"info","ts":1657644224.697958,"logger":"tls.issuance.acme.acme_client","msg":"trying to solve challenge","identifier":"sub.my-domain.com","challenge_type":"dns-01","ca":"https://acme-v02.api.letsencrypt.org/directory"}
{"level":"debug","ts":1657644224.7755122,"logger":"tls.issuance.acme.acme_client","msg":"http request","method":"POST","url":"https://acme-v02.api.letsencrypt.org/acme/new-order","headers":{"Content-Type":["application/jose+json"],"User-Agent":["Caddy/2.4.6 CertMagic acmez (linux; amd64)"]},"response_headers":{"Boulder-Requester":["113050068"],"Cache-Control":["public, max-age=0, no-cache"],"Content-Length":["351"],"Content-Type":["application/json"],"Date":["Tue, 12 Jul 2022 16:43:44 GMT"],"Link":["<https://acme-v02.api.letsencrypt.org/directory>;rel=\"index\""],"Location":["https://acme-v02.api.letsencrypt.org/acme/order/113050068/106113910546"],"Replay-Nonce":["0001BKesP28OZVF2v6aJIyXQjdN1WdOh-sUMBAND4tqRlBo"],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]},"status_code":201}
{"level":"error","ts":1657644224.7922163,"logger":"tls.issuance.acme.acme_client","msg":"cleaning up solver","identifier":"sub.my-domain.com","challenge_type":"dns-01","error":"no memory of presenting a DNS record for sub.my-domain.com (probably OK if presenting failed)"}
{"level":"info","ts":1657644224.7922497,"logger":"tls.renew","msg":"releasing lock","identifier":"sub.my-domain.com"}
2022/07/12 16:43:44 panic: certificate worker: runtime error: slice bounds out of range [:-10]
goroutine 53 [running]:
github.com/caddyserver/certmagic.(*jobManager).worker.func1()
	github.com/caddyserver/certmagic@v0.15.2/async.go:58 +0x65
panic({0x15e53a0, 0xc000211428})
	runtime/panic.go:1038 +0x215
github.com/libdns/azure.generateRecordSetName(...)
	github.com/libdns/azure@v0.1.0/client.go:153
github.com/libdns/azure.(*Provider).createOrUpdateRecord(0xc00007dd40, {0x19ab778, 0xc000115920}, {0xc000813120, 0x19}, {{0x0, 0x0}, {0x16989dc, 0x3}, {0xc000041c80, ...}, ...}, ...)
	github.com/libdns/azure@v0.1.0/client.go:137 +0x618
github.com/libdns/azure.(*Provider).createRecord(...)
	github.com/libdns/azure@v0.1.0/client.go:79
github.com/libdns/azure.(*Provider).AppendRecords(0xc00053d180, {0x19ab778, 0xc000115920}, {0xc000813120, 0x19}, {0xc00053d180, 0x1, 0x1})
	github.com/libdns/azure@v0.1.0/provider.go:34 +0x1b2
github.com/caddyserver/certmagic.(*DNS01Solver).Present(0xc00053ce10, {0x19ab778, 0xc000115920}, {{0xc000811410, 0x6}, {0xc0006deb90, 0x46}, {0xc000811416, 0x7}, {0x0, ...}, ...})
	github.com/caddyserver/certmagic@v0.15.2/solvers.go:283 +0x463
github.com/caddyserver/certmagic.solverWrapper.Present({{0x1999858, 0xc00053ce10}}, {0x19ab778, 0xc000115920}, {{0xc000811410, 0x6}, {0xc0006deb90, 0x46}, {0xc000811416, 0x7}, ...})
	github.com/caddyserver/certmagic@v0.15.2/solvers.go:664 +0x22d
github.com/mholt/acmez.(*Client).presentForNextChallenge(0xc000202528, {0x19ab778, 0xc000115920}, 0xc0001f0d00)
	github.com/mholt/acmez@v1.0.1/client.go:400 +0x7ee
github.com/mholt/acmez.(*Client).solveChallenges(_, {_, _}, {{0xc000048ff0, 0x5}, {0x0, 0x0, 0x0}, 0x1, {0x0, ...}, ...}, ...)
	github.com/mholt/acmez@v1.0.1/client.go:351 +0x277
github.com/mholt/acmez.(*Client).ObtainCertificateUsingCSR(0xc000202528, {0x19ab778, 0xc000115920}, {{0xc000048ff0, 0x5}, {0x0, 0x0, 0x0}, 0x1, {0x0, ...}, ...}, ...)
	github.com/mholt/acmez@v1.0.1/client.go:127 +0x498
github.com/caddyserver/certmagic.(*ACMEManager).doIssue(0xc000115920, {0x19ab778, 0xc000115920}, 0xc0000ea000, 0x0)
	github.com/caddyserver/certmagic@v0.15.2/acmemanager.go:315 +0x19c
github.com/caddyserver/certmagic.(*ACMEManager).Issue(0xc0000ea400, {0x19ab778, 0xc000115920}, 0x0)
	github.com/caddyserver/certmagic@v0.15.2/acmemanager.go:244 +0xa9
github.com/caddyserver/caddy/v2/modules/caddytls.(*ACMEIssuer).Issue(0xc00053b7c0, {0x19ab778, 0xc000115920}, 0xc00004ad80)
	github.com/caddyserver/caddy/v2@v2.4.6/modules/caddytls/acmeissuer.go:231 +0xb8
github.com/caddyserver/certmagic.(*Config).renewCert.func2({0x19ab778, 0xc000115920})
	github.com/caddyserver/certmagic@v0.15.2/config.go:739 +0xd73
github.com/caddyserver/certmagic.doWithRetry({0x19ab6d0, 0xc00003b700}, 0xc00067f6e0, 0xc0007a7c88)
	github.com/caddyserver/certmagic@v0.15.2/async.go:106 +0x1cc
github.com/caddyserver/certmagic.(*Config).renewCert(0xc00053b7c0, {0x19ab6d0, 0xc00003b700}, {0xc000211608, 0x18}, 0x0, 0x0)
	github.com/caddyserver/certmagic@v0.15.2/config.go:788 +0x598
github.com/caddyserver/certmagic.(*Config).RenewCertAsync(...)
	github.com/caddyserver/certmagic@v0.15.2/config.go:643
github.com/caddyserver/certmagic.(*Config).manageOne.func2()
	github.com/caddyserver/certmagic@v0.15.2/config.go:368 +0x72
github.com/caddyserver/certmagic.(*jobManager).worker(0x24d2fe0)
	github.com/caddyserver/certmagic@v0.15.2/async.go:73 +0x112
created by github.com/caddyserver/certmagic.(*jobManager).Submit
	github.com/caddyserver/certmagic@v0.15.2/async.go:50 +0x288
{"level":"debug","ts":1657644224.9241257,"logger":"tls.issuance.acme.acme_client","msg":"http request","method":"POST","url":"https://acme-v02.api.letsencrypt.org/acme/authz-v3/129755594556","headers":{"Content-Type":["application/jose+json"],"User-Agent":["Caddy/2.4.6 CertMagic acmez (linux; amd64)"]},"response_headers":{"Boulder-Requester":["113050068"],"Cache-Control":["public, max-age=0, no-cache"],"Content-Length":["398"],"Content-Type":["application/json"],"Date":["Tue, 12 Jul 2022 16:43:44 GMT"],"Link":["<https://acme-v02.api.letsencrypt.org/directory>;rel=\"index\""],"Replay-Nonce":["0001T6UuObU9TMzjqgpnrBbhwyckeNKH3YZ5aYZ58_2GcA4"],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]},"status_code":200}
{"level":"info","ts":1657644224.9242563,"logger":"tls.issuance.acme.acme_client","msg":"trying to solve challenge","identifier":"*.sub.my-domain.com","challenge_type":"dns-01","ca":"https://acme-v02.api.letsencrypt.org/directory"}
{"level":"error","ts":1657644224.9246325,"logger":"tls.issuance.acme.acme_client","msg":"cleaning up solver","identifier":"*.sub.my-domain.com","challenge_type":"dns-01","error":"no memory of presenting a DNS record for sub.my-domain.com (probably OK if presenting failed)"}
{"level":"info","ts":1657644224.9247282,"logger":"tls.renew","msg":"releasing lock","identifier":"*.sub.my-domain.com"}
2022/07/12 16:43:44 panic: certificate worker: runtime error: slice bounds out of range [:-10]
goroutine 55 [running]:
github.com/caddyserver/certmagic.(*jobManager).worker.func1()
	github.com/caddyserver/certmagic@v0.15.2/async.go:58 +0x65
panic({0x15e53a0, 0xc000211578})
	runtime/panic.go:1038 +0x215
github.com/libdns/azure.generateRecordSetName(...)
	github.com/libdns/azure@v0.1.0/client.go:153
github.com/libdns/azure.(*Provider).createOrUpdateRecord(0xc00007dd40, {0x19ab778, 0xc0001a2180}, {0xc000813120, 0x19}, {{0x0, 0x0}, {0x16989dc, 0x3}, {0xc00023e3c0, ...}, ...}, ...)
	github.com/libdns/azure@v0.1.0/client.go:137 +0x618
github.com/libdns/azure.(*Provider).createRecord(...)
	github.com/libdns/azure@v0.1.0/client.go:79
github.com/libdns/azure.(*Provider).AppendRecords(0xc00053d4a0, {0x19ab778, 0xc0001a2180}, {0xc000813120, 0x19}, {0xc00053d4a0, 0x1, 0x1})
	github.com/libdns/azure@v0.1.0/provider.go:34 +0x1b2
github.com/caddyserver/certmagic.(*DNS01Solver).Present(0xc00053ce10, {0x19ab778, 0xc0001a2180}, {{0xc00081176a, 0x6}, {0xc0006df0e0, 0x46}, {0xc000811770, 0x7}, {0x0, ...}, ...})
	github.com/caddyserver/certmagic@v0.15.2/solvers.go:283 +0x463
github.com/caddyserver/certmagic.solverWrapper.Present({{0x1999858, 0xc00053ce10}}, {0x19ab778, 0xc0001a2180}, {{0xc00081176a, 0x6}, {0xc0006df0e0, 0x46}, {0xc000811770, 0x7}, ...})
	github.com/caddyserver/certmagic@v0.15.2/solvers.go:664 +0x22d
github.com/mholt/acmez.(*Client).presentForNextChallenge(0xc00036b458, {0x19ab778, 0xc0001a2180}, 0xc0001f0ea0)
	github.com/mholt/acmez@v1.0.1/client.go:400 +0x7ee
github.com/mholt/acmez.(*Client).solveChallenges(_, {_, _}, {{0xc0000194b8, 0x5}, {0x0, 0x0, 0x0}, 0x1, {0x0, ...}, ...}, ...)
	github.com/mholt/acmez@v1.0.1/client.go:351 +0x277
github.com/mholt/acmez.(*Client).ObtainCertificateUsingCSR(0xc00036b458, {0x19ab778, 0xc0001a2180}, {{0xc0000194b8, 0x5}, {0x0, 0x0, 0x0}, 0x1, {0x0, ...}, ...}, ...)
	github.com/mholt/acmez@v1.0.1/client.go:127 +0x498
github.com/caddyserver/certmagic.(*ACMEManager).doIssue(0xc0001a2180, {0x19ab778, 0xc0001a2180}, 0xc000245000, 0x0)
	github.com/caddyserver/certmagic@v0.15.2/acmemanager.go:315 +0x19c
github.com/caddyserver/certmagic.(*ACMEManager).Issue(0xc000245100, {0x19ab778, 0xc0001a2180}, 0x0)
	github.com/caddyserver/certmagic@v0.15.2/acmemanager.go:244 +0xa9
github.com/caddyserver/caddy/v2/modules/caddytls.(*ACMEIssuer).Issue(0xc00053b7c0, {0x19ab778, 0xc0001a2180}, 0xc00067c710)
	github.com/caddyserver/caddy/v2@v2.4.6/modules/caddytls/acmeissuer.go:231 +0xb8
github.com/caddyserver/certmagic.(*Config).renewCert.func2({0x19ab778, 0xc0001a2180})
	github.com/caddyserver/certmagic@v0.15.2/config.go:739 +0xd73
github.com/caddyserver/certmagic.doWithRetry({0x19ab6d0, 0xc00003b700}, 0xc00067e4e0, 0xc000845c88)
	github.com/caddyserver/certmagic@v0.15.2/async.go:106 +0x1cc
github.com/caddyserver/certmagic.(*Config).renewCert(0xc00053b7c0, {0x19ab6d0, 0xc00003b700}, {0xc0004fd500, 0x1a}, 0x0, 0x0)
	github.com/caddyserver/certmagic@v0.15.2/config.go:788 +0x598
github.com/caddyserver/certmagic.(*Config).RenewCertAsync(...)
	github.com/caddyserver/certmagic@v0.15.2/config.go:643
github.com/caddyserver/certmagic.(*Config).manageOne.func2()
	github.com/caddyserver/certmagic@v0.15.2/config.go:368 +0x72
github.com/caddyserver/certmagic.(*jobManager).worker(0x24d2fe0)
	github.com/caddyserver/certmagic@v0.15.2/async.go:73 +0x112
created by github.com/caddyserver/certmagic.(*jobManager).Submit
	github.com/caddyserver/certmagic@v0.15.2/async.go:50 +0x288
```

Any ideas? 🤔

**Comment by mholt** [comment]
That looks like a bug in [libdns/azure](https://github.com/libdns/azure) based on the stack trace. I would file an issue there so the maintainer ([@kurokobo](https://github.com/libdns/azure/commits?author=kurokobo)) can take a look. Thanks!

**Comment by kurokobo** [comment]
@mholt
Thanks for forwarding, will check on this.
