### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by dtelyukh** [caddyserver/caddy#4959]
### 1a. Operating system and version

```
Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-122-generic x86_64)
```

### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
2.5.2
```

### 1c. Go version (if building Caddy from source; run `go version`)

```
1.18.5
```

## 2. Description

Fatal error with data race. It is similar to https://github.com/caddyserver/caddy/issues/1045
It is hard to understand which condition is causing this error. I tried run Caddy with/without http/3 enabled - the result is the same.

<details><summary>Without enabling data race detector</summary>

```
2022-08-15T08:53:20.804145716Z fatal error: concurrent map iteration and map write
2022-08-15T08:53:20.809615541Z 
2022-08-15T08:53:20.809633701Z goroutine 110840 [running]:
2022-08-15T08:53:20.810740240Z runtime.throw({0x2a91b6d?, 0x83?})
2022-08-15T08:53:20.810763727Z 	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc01686ece8 sp=0xc01686ecb8 pc=0x43dbf1
2022-08-15T08:53:20.811020706Z runtime.mapiternext(0x83?)
2022-08-15T08:53:20.811034026Z 	/usr/local/go/src/runtime/map.go:871 +0x4eb fp=0xc01686ed58 sp=0xc01686ece8 pc=0x4155cb
2022-08-15T08:53:20.811039699Z runtime.mapiterinit(0xc013202bd0?, 0xc00e3119b0?, 0x4ae919?)
2022-08-15T08:53:20.811044379Z 	/usr/local/go/src/runtime/map.go:861 +0x228 fp=0xc01686ed78 sp=0xc01686ed58 pc=0x415088
2022-08-15T08:53:20.811049437Z github.com/caddyserver/caddy/v2/modules/caddyhttp.computeApproximateRequestSize(0xc013209300)
2022-08-15T08:53:20.811054290Z 	/go/src/caddy-fork/modules/caddyhttp/metrics.go:164 +0x8e fp=0xc01686ee08 sp=0xc01686ed78 pc=0x1b5892e
2022-08-15T08:53:20.811567018Z github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc00fce1420, {0x7fa48f233238?, 0xc00f2e0f30}, 0xc013209300, {0x2f56880, 0xc
0130f6ba0})
2022-08-15T08:53:20.811610618Z 	/go/src/caddy-fork/modules/caddyhttp/metrics.go:149 +0x6ff fp=0xc01686ef38 sp=0xc01686ee08 pc=0x1b5853f
2022-08-15T08:53:20.811815102Z github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x7fa48f233238?, 0xc00f2e0f30?}, 0x2f56880?)
2022-08-15T08:53:20.813431312Z 	/go/src/caddy-fork/modules/caddyhttp/routes.go:272 +0x3b fp=0xc01686ef78 sp=0xc01686ef38 pc=0x1b5e21b
2022-08-15T08:53:20.813449121Z github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x2f56880?, {0x7fa48f233238?, 0xc00f2e0f30?}, 0x0?)
2022-08-15T08:53:20.813454943Z 	/go/src/caddy-fork/modules/caddyhttp/caddyhttp.go:57 +0x2f fp=0xc01686efa0 sp=0xc01686ef78 pc=0x1b472ef
2022-08-15T08:53:20.813459819Z github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x7fa48f233238, 0xc00f2e0f30}, 0xc013209300)
2022-08-15T08:53:20.813464476Z 	/go/src/caddy-fork/modules/caddyhttp/routes.go:244 +0x322 fp=0xc01686f010 sp=0xc01686efa0 pc=0x1b5df62
2022-08-15T08:53:20.813469407Z github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00066ab40?, {0x7fa48f233238?, 0xc00f2e0f30?}, 0x2f56880?)
2022-08-15T08:53:20.813474034Z 	/go/src/caddy-fork/modules/caddyhttp/caddyhttp.go:57 +0x2f fp=0xc01686f038 sp=0xc01686f010 pc=0x1b472ef
2022-08-15T08:53:20.813478734Z github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc000062ea0, {0x7fa48f233238, 0xc00f2e0f30}, 0x6?, {0x2f56880, 0x2b546a0})
2022-08-15T08:53:20.813483369Z 	/go/src/caddy-fork/modules/caddyhttp/subroute.go:74 +0x6d fp=0xc01686f078 sp=0xc01686f038 pc=0x1b6378d
2022-08-15T08:53:20.813488147Z github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc00fce1460, {0x7fa48f233238?, 0xc00f2e0de0}, 0xc013209300, {0x2f56880, 0x2
b546a0})
2022-08-15T08:53:20.813503452Z 	/go/src/caddy-fork/modules/caddyhttp/metrics.go:132 +0x53b fp=0xc01686f1a8 sp=0xc01686f078 pc=0x1b5837b
2022-08-15T08:53:20.813508783Z github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x7fa48f233238?, 0xc00f2e0de0?}, 0x2f56880?)
2022-08-15T08:53:20.813513403Z 	/go/src/caddy-fork/modules/caddyhttp/routes.go:272 +0x3b fp=0xc01686f1e8 sp=0xc01686f1a8 pc=0x1b5e21b
2022-08-15T08:53:20.813518102Z github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x2f56880?, {0x7fa48f233238?, 0xc00f2e0de0?}, 0x0?)
2022-08-15T08:53:20.813522668Z 	/go/src/caddy-fork/modules/caddyhttp/caddyhttp.go:57 +0x2f fp=0xc01686f210 sp=0xc01686f1e8 pc=0x1b472ef
2022-08-15T08:53:20.813527330Z github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x7fa48f233238, 0xc00f2e0de0}, 0xc013209300)
2022-08-15T08:53:20.813532081Z 	/go/src/caddy-fork/modules/caddyhttp/routes.go:244 +0x322 fp=0xc01686f280 sp=0xc01686f210 pc=0x1b5df62
2022-08-15T08:53:20.813536804Z github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00066a900?, {0x7fa48f233238?, 0xc00f2e0de0?}, 0x2f56880?)
2022-08-15T08:53:20.813542302Z 	/go/src/caddy-fork/modules/caddyhttp/caddyhttp.go:57 +0x2f fp=0xc01686f2a8 sp=0xc01686f280 pc=0x1b472ef
2022-08-15T08:53:20.813547330Z github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP(0xc00013b340, {0x7fa48f233238, 0xc00f2e0de0}, 0x6?, {0x2f56880, 0x2b546a0})
2022-08-15T08:53:20.813552144Z 	/go/src/caddy-fork/modules/caddyhttp/subroute.go:74 +0x6d fp=0xc01686f2e8 sp=0xc01686f2a8 pc=0x1b6378d
2022-08-15T08:53:20.813556848Z github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc00fce14a0, {0x2f65858?, 0xc01309fa40}, 0xc013209300, {0x2f56880, 0x2b546a
0})
2022-08-15T08:53:20.813561528Z 	/go/src/caddy-fork/modules/caddyhttp/metrics.go:132 +0x53b fp=0xc01686f418 sp=0xc01686f2e8 pc=0x1b5837b
2022-08-15T08:53:20.813566202Z github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x2f65858?, 0xc01309fa40?}, 0x2f56880?)
2022-08-15T08:53:20.813570850Z 	/go/src/caddy-fork/modules/caddyhttp/routes.go:272 +0x3b fp=0xc01686f458 sp=0xc01686f418 pc=0x1b5e21b
2022-08-15T08:53:20.813575539Z github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x2f56880?, {0x2f65858?, 0xc01309fa40?}, 0xc01309fbc0?)
2022-08-15T08:53:20.813580162Z 	/go/src/caddy-fork/modules/caddyhttp/caddyhttp.go:57 +0x2f fp=0xc01686f480 sp=0xc01686f458 pc=0x1b472ef
2022-08-15T08:53:20.813584842Z github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x2f65858, 0xc01309fa40}, 0xc013209300)
2022-08-15T08:53:20.813589491Z 	/go/src/caddy-fork/modules/caddyhttp/routes.go:244 +0x322 fp=0xc01686f4f0 sp=0xc01686f480 pc=0x1b5df62
2022-08-15T08:53:20.813594148Z github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x2?, {0x2f65858?, 0xc01309fa40?}, 0x7fa4e021bf18?)
2022-08-15T08:53:20.813598777Z 	/go/src/caddy-fork/modules/caddyhttp/caddyhttp.go:57 +0x2f fp=0xc01686f518 sp=0xc01686f4f0 pc=0x1b472ef
2022-08-15T08:53:20.813607906Z github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).enforcementHandler(0x412f27?, {0x2f65858?, 0xc01309fa40?}, 0x1?, {0x2f56880?, 0xc0121439e0?})
2022-08-15T08:53:20.813613090Z 	/go/src/caddy-fork/modules/caddyhttp/server.go:318 +0x252 fp=0xc01686f5f0 sp=0xc01686f518 pc=0x1b60832
2022-08-15T08:53:20.813617841Z github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).wrapPrimaryRoute.func1({0x2f65858?, 0xc01309fa40?}, 0x4a1497?)
2022-08-15T08:53:20.813622455Z 	/go/src/caddy-fork/modules/caddyhttp/server.go:294 +0x3b fp=0xc01686f630 sp=0xc01686f5f0 pc=0x1b6059b
2022-08-15T08:53:20.813627586Z github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc0004b8420?, {0x2f65858?, 0xc01309fa40?}, 0xc013209300?)
2022-08-15T08:53:20.813632357Z 	/go/src/caddy-fork/modules/caddyhttp/caddyhttp.go:57 +0x2f fp=0xc01686f658 sp=0xc01686f630 pc=0x1b472ef
2022-08-15T08:53:20.813637093Z github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc00060c120, {0x2f65858, 0xc01309fa40}, 0xc013209300)
2022-08-15T08:53:20.813641712Z 	/go/src/caddy-fork/modules/caddyhttp/server.go:230 +0xac6 fp=0xc01686fd40 sp=0xc01686f658 pc=0x1b5f246
2022-08-15T08:53:20.813646439Z github.com/lucas-clemente/quic-go/http3.(*Server).handleRequest.func2(0x2f68738?, 0xc00f2e07e0?, {0x2f4f220?, 0xc00060c120?}, 0x27913a0?, 0xc00f2e0840?)
2022-08-15T08:53:20.813651132Z 	/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.28.0/http3/server.go:588 +0x7d fp=0xc01686fd98 sp=0xc01686fd40 pc=0xa1d57d
2022-08-15T08:53:20.813655888Z github.com/lucas-clemente/quic-go/http3.(*Server).handleRequest(0xc010741ce0, {0x2f790c0?, 0xc0128b8000}, {0x7fa48f233100, 0xc012f74b40}, 0x747315052f6d6f63?, 0xc0132
1c978)
2022-08-15T08:53:20.813660557Z 	/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.28.0/http3/server.go:589 +0xbd0 fp=0xc01686ff30 sp=0xc01686fd98 pc=0xa1d130
2022-08-15T08:53:20.813665319Z github.com/lucas-clemente/quic-go/http3.(*Server).handleConn.func1()
2022-08-15T08:53:20.813669862Z 	/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.28.0/http3/server.go:432 +0xfd fp=0xc01686ffe0 sp=0xc01686ff30 pc=0xa1bb5d
2022-08-15T08:53:20.813674622Z runtime.goexit()
2022-08-15T08:53:20.813679013Z 	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc01686ffe8 sp=0xc01686ffe0 pc=0x4713c1
2022-08-15T08:53:20.813683716Z created by github.com/lucas-clemente/quic-go/http3.(*Server).handleConn
2022-08-15T08:53:20.813688271Z 	/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.28.0/http3/server.go:431 +0x1d7

....
too many strings there
```

</details>

<details><summary>With enabling data race detector</summary>

```
==================
WARNING: DATA RACE
Read at 0x00c0009f80c0 by goroutine 44:
  runtime.mapiterinit()
      /usr/local/go/src/runtime/map.go:815 +0x0
  github.com/caddyserver/caddy/v2/modules/caddyhttp.computeApproximateRequestSize()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/metrics.go:164 +0x10d
  github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/metrics.go:149 +0x9e4
  github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/routes.go:272 +0x6e
  github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/caddyhttp.go:57 +0x4d
 github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/routes.go:244 +0x5ba
  github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/caddyhttp.go:57 +0x4d
  github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/routes.go:212 +0x4da
  github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/caddyhttp.go:57 +0x4d
  github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/subroute.go:74 +0x9a
  github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/metrics.go:132 +0x7c5
  github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/routes.go:272 +0x6e
  github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/caddyhttp.go:57 +0x4d
  github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/routes.go:244 +0x5ba
  github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/caddyhttp.go:57 +0x4d
  github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/routes.go:212 +0x4da
  github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/caddyhttp.go:57 +0x4d
  github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/routes.go:212 +0x4da
  github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/caddyhttp.go:57 +0x4d
  github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/routes.go:212 +0x4da
  github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/caddyhttp.go:57 +0x4d
  github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/routes.go:212 +0x4da
  github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/caddyhttp.go:57 +0x4d
  github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/routes.go:212 +0x4da
  github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/caddyhttp.go:57 +0x4d
  github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Subroute).ServeHTTP()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/subroute.go:74 +0x9a
  github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/metrics.go:132 +0x7c5
  github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/routes.go:272 +0x6e
  github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/caddyhttp.go:57 +0x4d
  github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/routes.go:244 +0x5ba
  github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/caddyhttp.go:57 +0x4d
  github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).enforcementHandler()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/server.go:318 +0x1fe
  github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).wrapPrimaryRoute.func1()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/server.go:294 +0x6e
  github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/caddyhttp.go:57 +0x4d
  github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/caddy/modules/caddyhttp/server.go:230 +0xee1
  net/http.serverHandler.ServeHTTP()
      /usr/local/go/src/net/http/server.go:2916 +0x896
  net/http.initALPNRequest.ServeHTTP()
      /usr/local/go/src/net/http/server.go:3523 +0x34d
  net/http.(*initALPNRequest).ServeHTTP()
      <autogenerated>:1 +0x85
  net/http.Handler.ServeHTTP-fm()
      <autogenerated>:1 +0x75
  golang.org/x/net/http2.(*serverConn).runHandler()
      /home/dionysius/go/pkg/mod/golang.org/x/net@v0.0.0-20220624214902-1bab6f366d9e/http2/server.go:2243 +0xd2
  golang.org/x/net/http2.(*serverConn).processHeaders.func1()
      /home/dionysius/go/pkg/mod/golang.org/x/net@v0.0.0-20220624214902-1bab6f366d9e/http2/server.go:1951 +0x64

Previous write at 0x00c0009f80c0 by goroutine 119:
  runtime.mapassign_faststr()
      /usr/local/go/src/runtime/map_faststr.go:203 +0x0
  net/textproto.MIMEHeader.Add()
      /usr/local/go/src/net/textproto/header.go:15 +0x6c6
  net/http.Header.Add()
      /usr/local/go/src/net/http/header.go:31 +0x5b6
  gitlab.com/activecdn/activecdn.(*Handler).fetchUpstream.func1()
      /home/dionysius/Документы/Исходники/go/gitlab.com/activecdn/activecdn/handler.go:315 +0x592

Goroutine 44 (running) created at:
  golang.org/x/net/http2.(*serverConn).processHeaders()
      /home/dionysius/go/pkg/mod/golang.org/x/net@v0.0.0-20220624214902-1bab6f366d9e/http2/server.go:1951 +0xc26
  golang.org/x/net/http2.(*serverConn).processFrame()
      /home/dionysius/go/pkg/mod/golang.org/x/net@v0.0.0-20220624214902-1bab6f366d9e/http2/server.go:1465 +0x306
  golang.org/x/net/http2.(*serverConn).processFrameFromReader()
      /home/dionysius/go/pkg/mod/golang.org/x/net@v0.0.0-20220624214902-1bab6f366d9e/http2/server.go:1423 +0x2ed
  golang.org/x/net/http2.(*serverConn).serve()
      /home/dionysius/go/pkg/mod/golang.org/x/net@v0.0.0-20220624214902-1bab6f366d9e/http2/server.go:919 +0x150a
  golang.org/x/net/http2.(*Server).ServeConn()
      /home/dionysius/go/pkg/mod/golang.org/x/net@v0.0.0-20220624214902-1bab6f366d9e/http2/server.go:504 +0x1711
  golang.org/x/net/http2.ConfigureServer.func1()
      /home/dionysius/go/pkg/mod/golang.org/x/net@v0.0.0-20220624214902-1bab6f366d9e/http2/server.go:294 +0x124
  net/http.(*conn).serve()
      /usr/local/go/src/net/http/server.go:1874 +0x1c56
  net/http.(*Server).Serve.func3()
      /usr/local/go/src/net/http/server.go:3071 +0x58
```

</details>

**Comment by lxhao61** [comment]
H2C Server and bind UDS error
```{
	admin off
	log {
		output file /var/log/caddy/access.log
		level ERROR
	}
	auto_https off
	servers unix//dev/shm/h1h2c.sock {
		listener_wrappers {
			proxy_protocol
		}
		protocols h2c  h1
	}
}

:80 { #http默认监听端口
	redir https://{host}{uri} permanent #http自动跳转https，让网站看起来更真实。
}

:88 { #绑定进程后此端口失效，仅做标记作用。
	bind unix//dev/shm/h1h2c.sock #http/1.1与h2c server监听进程

	@host {
		host xx.yy #限定域名访问（禁止以IP方式访问网站），修改为自己的域名。
	}
	route @host {
		header {
			Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" #启用HSTS
		}
		file_server {
			root /var/www/html #修改为自己存放的WEB文件路径
		}
	}
}
```

**Comment by mholt** [comment]
Thanks for the report @dtelyukh. @hairyhenderson you authored the metrics features; do you think you could help fix this?

@lxhao61 I'm not sure what your reply is about. If you have a question can you please ask it on our forums: https://caddy.community

**Comment by dtelyukh** [comment]
An addition: with this setting
```
    metrics /metrics {
        disable_openmetrics
    }
```
the error appears less often

**Comment by hairyhenderson** [comment]
Hi @dtelyukh,

From the stack trace it looks like you're embedding caddy with `gitlab.com/activecdn/activecdn` - https://gitlab.com/activecdn/activecdn 404s, so I can only assume it's private.

It seems to me that something in `gitlab.com/activecdn/activecdn.(*Handler).fetchUpstream` is modifying the `*http.Request`'s header, and that's what's causing the race. Can you paste the code that's modifying the header?

**Comment by hairyhenderson** [comment]
I'm betting there's some code like `go fetchUpstream(...)` in `gitlab.com/activecdn/activecdn.(*Handler)`, which is modifying the HTTP request in a separate goroutine. That'll never work out well. You should be modifying the request in the same goroutine as the handler's `ServeHTTP` method.

Since the race is not in core Caddy, I'm going to close this now. Please feel free to re-open if you can replicate this in Caddy itself.

**Comment by mholt** [comment]
Thanks Dave. I should have looked closer at the stack trace (it was late at the time).

Make sure the HTTP handlers run synchronously, that is needed in all Go programs.

**Comment by dtelyukh** [comment]
Hi @hairyhenderson, thanks for you replying

```
	responseWriter := NewCustomResponseWriter()
	req.Header.Add("X-Acdn-Request-Id", requestId) // <- this is a problem?
	err := next.ServeHTTP(responseWriter, req)
```

But I'd like to point to the fact, that disabling metrics not disable them completely, as I understand from race log.

**Comment by francislavoie** [comment]
Yeah, `disable_openmetrics` just turns off the openmetrics negotiation, but prometheus style metrics are still there.
