### ISSUE TITLE
Mixing strings and numbers in a map crashes in the request matcher

### ISSUE THREAD

**Issue by mao-shonen** [caddyserver/caddy#5035]
## Question description
This is a bug I encountered on my way to test another issue #5034,
Obviously this is another bug, so I submitted new issues separately.

After mixing regexp with string and number variables in map,
An error occurred in the request matcher match.

## Minimum example
```nginx
:8080 {
	map {host} {host_key} {num} {
		~example\.com	"example"	1
		default				"default"	0
	}

	@match_endpoint vars {num} 1
	handle @match_endpoint {
		respond "test endpoint"
	}

	handle {
		respond "default endpoint num={num}"
	}
}
```

## Test results
```bash
# httpie
http :8080 Host:example.com
```
Bug log
```
2022/09/11 15:45:07.268 DEBUG   http.stdlib     http: panic serving 127.0.0.1:60208: interface conversion: interface {} is float64, not string
goroutine 330 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1825 +0xbf
panic({0x179b120, 0xc000536d50})
        runtime/panic.go:844 +0x258
github.com/caddyserver/caddy/v2/modules/caddyhttp/map.Handler.ServeHTTP.func1({0xc000535261?, 0x3?})
        github.com/caddyserver/caddy/v2@v2.5.2/modules/caddyhttp/map/map.go:144 +0x416
github.com/caddyserver/caddy/v2.(*Replacer).Get(0xc000535260?, {0xc000535261, 0x3})
        github.com/caddyserver/caddy/v2@v2.5.2/replacer.go:74 +0x6d
github.com/caddyserver/caddy/v2.(*Replacer).replace(0xc000536c30?, {0xc000535260, 0x5}, {0x0, 0x0}, 0x1, 0x0, 0x0, 0x0)
        github.com/caddyserver/caddy/v2@v2.5.2/replacer.go:183 +0x528
github.com/caddyserver/caddy/v2.(*Replacer).ReplaceAll(...)
        github.com/caddyserver/caddy/v2@v2.5.2/replacer.go:120
github.com/caddyserver/caddy/v2/modules/caddyhttp.VarsMatcher.Match(0xc0005dcf90, 0xc000187900)
        github.com/caddyserver/caddy/v2@v2.5.2/modules/caddyhttp/vars.go:164 +0x1a9
github.com/caddyserver/caddy/v2/modules/caddyhttp.MatcherSet.Match(...)
        github.com/caddyserver/caddy/v2@v2.5.2/modules/caddyhttp/routes.go:286
github.com/caddyserver/caddy/v2/modules/caddyhttp.MatcherSets.AnyMatch({0xc0004c3e78?, 0x1, 0xc0000bceb0?}, 0x4a6b46?)
        github.com/caddyserver/caddy/v2@v2.5.2/modules/caddyhttp/routes.go:307 +0xc2
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x7f46183b0780, 0xc000536d20}, 0xc000187900)
        github.com/caddyserver/caddy/v2@v2.5.2/modules/caddyhttp/routes.go:202 +0x65
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000536c30?, {0x7f46183b0780?, 0xc000536d20?}, 0xc0000bcfa8?)
        github.com/caddyserver/caddy/v2@v2.5.2/modules/caddyhttp/caddyhttp.go:57 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp/map.Handler.ServeHTTP({{0xc000122ed0, 0x13}, {0xc0005d3980, 0x2, 0x4}, {0xc0000f3300, 0x1, 0x4}, {0xc0005d3940, 0x2, ...}}, ...)
        github.com/caddyserver/caddy/v2@v2.5.2/modules/caddyhttp/map/map.go:164 +0x1a9
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*metricsInstrumentedHandler).ServeHTTP(0xc0005f87e0, {0x1d05d20?, 0xc0005321c0}, 0xc000187900, {0x1cfbf80, 0xc0005f8ae0})
        github.com/caddyserver/caddy/v2@v2.5.2/modules/caddyhttp/metrics.go:132 +0x53b
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapMiddleware.func1.1({0x1d05d20?, 0xc0005321c0?}, 0x1cfbf80?)
        github.com/caddyserver/caddy/v2@v2.5.2/modules/caddyhttp/routes.go:272 +0x3b
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0x1cfbf80?, {0x1d05d20?, 0xc0005321c0?}, 0x0?)
        github.com/caddyserver/caddy/v2@v2.5.2/modules/caddyhttp/caddyhttp.go:57 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.wrapRoute.func1.1({0x1d05d20, 0xc0005321c0}, 0xc000187900)
        github.com/caddyserver/caddy/v2@v2.5.2/modules/caddyhttp/routes.go:244 +0x322
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc000544000?, {0x1d05d20?, 0xc0005321c0?}, 0x18fb8e0?)
        github.com/caddyserver/caddy/v2@v2.5.2/modules/caddyhttp/caddyhttp.go:57 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).enforcementHandler(0x0?, {0x1d05d20?, 0xc0005321c0?}, 0xc000049dc0?, {0x1cfbf80?, 0xc0005f8b00?})
        github.com/caddyserver/caddy/v2@v2.5.2/modules/caddyhttp/server.go:318 +0x252
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).wrapPrimaryRoute.func1({0x1d05d20?, 0xc0005321c0?}, 0x49b797?)
        github.com/caddyserver/caddy/v2@v2.5.2/modules/caddyhttp/server.go:294 +0x3b
github.com/caddyserver/caddy/v2/modules/caddyhttp.HandlerFunc.ServeHTTP(0xc00028d810?, {0x1d05d20?, 0xc0005321c0?}, 0xc000187900?)
        github.com/caddyserver/caddy/v2@v2.5.2/modules/caddyhttp/caddyhttp.go:57 +0x2f
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*Server).ServeHTTP(0xc0005b3680, {0x1d05d20, 0xc0005321c0}, 0xc000187900)
        github.com/caddyserver/caddy/v2@v2.5.2/modules/caddyhttp/server.go:230 +0xac6
net/http.serverHandler.ServeHTTP({0xc000536a20?}, {0x1d05d20, 0xc0005321c0}, 0xc000187700)
        net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0001a1040, {0x1d07670, 0xc000536840})
        net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        net/http/server.go:3071 +0x4db
```

## Context
caddy version: v2.5.2 h1:eCJdLyEyAGzuQTa5Mh3gETnYWDClo1LjtQm2q9RNZrs=

**Comment by mholt** [comment]
Already fixed on master, actually! :grin: https://github.com/caddyserver/caddy/issues/4987
