### ISSUE TITLE
Certificate renewal crash

### ISSUE THREAD

**Issue by ChrisLahaye** [caddyserver/caddy#5200]
Hello,

Caddy is crashing when attempting certificate renewal for our invalid domain name. We are running v2.6.1.

Our on-demand SSL ask endpoint had a bug which caused git.git.git.git.git.git.git.domain.com to be authorized. As a result Caddy is now trying to renew a certificate for this domain, leading to a few errors and full crash.

We understand this is a rare case and caused by our own doing. However, we would still like to report the issue as it is causing a full crash.

Best,

Chris

```
{"level":"info","ts":1668152784.9556403,"logger":"tls.on_demand","msg":"attempting certificate renewal","server_name":"git.git.git.git.git.git.git.domain.com","subjects":["git.git.git.git.git.git.git.domain.com"],"expiration":1669939200,"remaining":1786415.044504804,"revoked":false}
{"level":"info","ts":1668152784.9791846,"logger":"tls.renew","msg":"acquiring lock","identifier":"git.git.git.git.git.git.git.domain.com"}
{"level":"info","ts":1668152784.9946587,"logger":"tls.renew","msg":"lock acquired","identifier":"git.git.git.git.git.git.git.domain.com"}
{"level":"info","ts":1668152785.00016,"logger":"tls.renew","msg":"renewing certificate","identifier":"git.git.git.git.git.git.git.domain.com","remaining":1786414.999841369}
{"level":"info","ts":1668152785.0102832,"logger":"http","msg":"waiting on internal rate limiter","identifiers":["git.git.git.git.git.git.git.domain.com"],"ca":"https://acme-v02.api.letsencrypt.org/directory","account":"caddy@zerossl.com"}
{"level":"info","ts":1668152785.0103135,"logger":"http","msg":"done waiting on internal rate limiter","identifiers":["git.git.git.git.git.git.git.domain.com"],"ca":"https://acme-v02.api.letsencrypt.org/directory","account":"caddy@zerossl.com"}
{"level":"error","ts":1668152785.5526936,"logger":"tls.renew","msg":"could not get certificate from issuer","identifier":"git.git.git.git.git.git.git.domain.com","issuer":"acme-v02.api.letsencrypt.org-directory","error":"HTTP 400 urn:ietf:params:acme:error:rejectedIdentifier - Error creating new order :: Cannot issue for \"git.git.git.git.git.git.git.domain.com\": Domain name has more than 10 labels (parts)"}
{"level":"info","ts":1668152785.5609221,"logger":"http","msg":"waiting on internal rate limiter","identifiers":["git.git.git.git.git.git.git.domain.com"],"ca":"https://acme.zerossl.com/v2/DV90","account":"caddy@zerossl.com"}
{"level":"info","ts":1668152785.5611007,"logger":"http","msg":"done waiting on internal rate limiter","identifiers":["git.git.git.git.git.git.git.domain.com"],"ca":"https://acme.zerossl.com/v2/DV90","account":"caddy@zerossl.com"}
{"level":"error","ts":1668152793.169564,"logger":"tls.renew","msg":"could not get certificate from issuer","identifier":"git.git.git.git.git.git.git.domain.com","issuer":"acme.zerossl.com-v2-DV90","error":"HTTP 401 urn:ietf:params:acme:error:unauthorized - A requested identifier is not permitted [git.git.git.git.git.git.git.domain.com]"}
{"level":"info","ts":1668152793.169738,"logger":"tls.renew","msg":"releasing lock","identifier":"git.git.git.git.git.git.git.domain.com"}
panic: runtime error: invalid memory address or nil pointer dereference	
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8bd3f4]
	
goroutine 11082 [running]:
github.com/caddyserver/certmagic.(*Config).renewCert.func2({0x2906d58, 0xc000df8d80})
	github.com/caddyserver/certmagic@v0.17.1/config.go:821 +0xc14
github.com/caddyserver/certmagic.doWithRetry({0x2906d20, 0xc000bfede0}, 0xc000346e00, 0xc000a03720)
	github.com/caddyserver/certmagic@v0.17.1/async.go:106 +0x1cb
github.com/caddyserver/certmagic.(*Config).renewCert(0xc000a69e40, {0x2906d20, 0xc000bfede0}, {0xc000ffe240, 0x37}, 0x0, 0x0)
	github.com/caddyserver/certmagic@v0.17.1/config.go:860 +0x58b
github.com/caddyserver/certmagic.(*Config).RenewCertAsync(...)
	github.com/caddyserver/certmagic@v0.17.1/config.go:690
github.com/caddyserver/certmagic.(*Config).renewDynamicCertificate.func3({0x2906d20, 0xc000bfede0}, 0xc000fc7dd0?)
	github.com/caddyserver/certmagic@v0.17.1/handshake.go:664 +0x2ac
created by github.com/caddyserver/certmagic.(*Config).renewDynamicCertificate
	github.com/caddyserver/certmagic@v0.17.1/handshake.go:699 +0x1293
```

**Comment by francislavoie** [comment]
Please try with v2.6.2, there's been some changes to CertMagic since.

**Comment by ChrisLahaye** [comment]
@francislavoie Thank you for the suggestion. Unfortunately we can't because we have already fixed the bug and state, and we can't run v2.6.2 due to #5200.

Just leaving the stack trace here for review. Feel free to close the issue.

**Comment by francislavoie** [comment]
Can't you run with a build from master which includes that fix?

**Comment by ChrisLahaye** [comment]
@francislavoie Yes we could, but for us personally there is no direct need for such a fix. This issue appeared due to a bug in our ask endpoint which authorized the invalid domain for a certificate. This bug has now been fixed so we are not affected by this issue anymore. I still decided to report it so that the root cause itself can be fixed. If it is already fixed or not present in v2.6.2, please let me know and I will close the issue. If you are not certain, then I recommend to leave this issue open for further review.

**Comment by francislavoie** [comment]
Well that's the thing. If you can try 2.6.2 and confirm that it isn't a problem anymore, then it saves us time. We won't necessarily be able to reproduce the issue.

**Comment by mholt** [comment]
Confirmed fixed already: https://github.com/caddyserver/certmagic/pull/206

**Comment by ChrisLahaye** [comment]
@mholt Great! Thank you for this great piece of software.

**Comment by mholt** [comment]
You're welcome! Team effort 😉

**Comment by sriccio** [comment]
Hello,

I found this post while trying to figure out what is going on with our caddy instances.

They were quite crashing a lot and I found out in our logs that there are thousands of:

```
{"level":"error","ts":1667503454.8970551,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"git.gitlab.git.gitlab.gitlab.saas-fee.geneve-taxi.ch","issuer":"acme-v02.api.letsencrypt.org-directory","error":"HTTP 429 urn:ietf:params:acme:error:rateLimited - Error creating new order :: too many certificates already issued for: geneve-taxi.ch: see https://letsencrypt.org/docs/rate-limits/"}
{"level":"error","ts":1667503456.8333778,"logger":"tls.obtain","msg":"could not get certificate from issuer","identifier":"git.gitlab.git.gitlab.gitlab.saas-fee.geneve-taxi.ch","issuer":"acme.zerossl.com-v2-DV90","error":"HTTP 401 urn:ietf:params:acme:error:unauthorized - A requested identifier is not permitted [git.gitlab.git.gitlab.gitlab.saas-fee.geneve-taxi.ch]"}
{"level":"error","ts":1667503456.8334537,"logger":"tls.obtain","msg":"will retry","error":"[git.gitlab.git.gitlab.gitlab.saas-fee.geneve-taxi.ch] Obtain: [git.gitlab.git.gitlab.gitlab.saas-fee.geneve-taxi.ch] creating new order: attempt 1: https://acme.zerossl.com/v2/DV90/newOrder: HTTP 401 urn:ietf:params:acme:error:unauthorized - A requested identifier is not permitted [git.gitlab.git.gitlab.gitlab.saas-fee.geneve-taxi.ch] (ca=https://acme.zerossl.com/v2/DV90)","attempt":2,"retrying_in":120,"elapsed":69.185733581,"max_duration":2592000}
```

```
[root@web23 caddy]# grep git.git caddy.lo | wc -l
40612
```

It also looks like our ASK endpoint has a bug with subdomains as it returns a `200` for these entries.
It looks like it is for domains having a wildcard DNS entries (for example some domains that have DNSes on Cloudflare and accept to resolve *.domain.tld)

May I ask if once we fixed the ASK endpoint issue, is there a way to cleanup all bogus entries for caddy to stop trying renewing these entries ?

Thanks a lot for the help!

Sébastien

**Comment by francislavoie** [comment]
> May I ask if once we fixed the ASK endpoint issue, is there a way to cleanup all bogus entries for caddy to stop trying renewing these entries ?

Yes, you can delete all the certificates you don't want to keep from your storage.

**Comment by sriccio** [comment]
Hello Francis,

Thanks. Oh okay, sorry for this. I will do next time. It was the only thread/issue I found talking about the git.git.git.git domains issue that looked exactly like our issue :)

Kind regards
