### ISSUE TITLE
Removing on_demand rate_limit causes a configuration error

### ISSUE THREAD

**Issue by excid3** [caddyserver/caddy#5442]
This is related to #5368 

To fix the vulnerability warning, I added the on_demand ask and rate_limit options to our JSON config. Since that is fixed, I am trying to remove them from the Caddy config by updating the config using the API endpoint. This causes an error though.

Previously, I would update the Caddy config with a `POST /load` that included the following config generated by Ruby. The relevant snippet that is causing the issue:

```ruby
        tls: {
          automation: {
            policies: @tls_policies,
            on_demand: {
              ask: Rails.application.routes.url_helpers.api_v1_caddy_ask_url,
              rate_limit: {
                interval: "2m",
                burst: 5
              }
            }
          },
```

Now we're sending over the following with `POST /load`

```ruby
        tls: {
          automation: {
            policies: @tls_policies
            }
          },
```

I've also tried setting it to an empty hash or null to clear out the on_demand param but same result with those.

```
on_demand: {} // null
```

Caddy's internal updating of the config seems to be tripping on this removal as the POST request fails and we get this error in the Caddy logs from certmagic.

```
invalid configuration: maxEvents = 0 and window != 0 would not allow any events
goroutine 116 [running]:
net/http.(*conn).serve.func1()
net/http/server.go:1854 +0xbf
panic({0x1af0120, 0x234d3f0})
runtime/panic.go:890 +0x263
github.com/caddyserver/certmagic.(*RingBufferRateLimiter).SetMaxEvents(0xc0002dc780, 0x0)
github.com/caddyserver/certmagic@v0.17.2/ratelimiter.go:154 +0x218
github.com/caddyserver/caddy/v2/modules/caddytls.(*TLS).Provision(0xc0007d91e0, {{0x236a758, 0xc0004e41e0}, 0xc0005d7bf0, 0xc0004e4140, {0x0, 0x0, 0x0}, {0xc000646e60, 0x2, ...}})
```

This seems like a bug where Caddy's retaining that rate limit option internally when it should have been removed?

**Comment by excid3** [comment]
Whoops, I think I know what we're doing wrong. 

POST /config/ would merge the new config with the existing config.
POST /load is what we want which would _replace_ the existing config.

**Comment by excid3** [comment]
The `/load` endpoint claims to replace the existing config, but internally it is just calling `POST /config/` which merges the new config with the old.

https://github.com/caddyserver/caddy/blob/master/caddy.go#LL127C72

I bet that's why removing keys doesn't work?

**Comment by mholt** [comment]
@excid3 What does your resulting config look like? I'm having a hard time following with just snippets and such. We'll probably need the full config to diagnose and reproduce.

**Comment by excid3** [comment]
Sure thing! I meant to post it. 

To reproduce:

1. I added a config with the `rate_limit`

```bash
curl --max-time 5 -s --fail-with-body -X POST -H 'Content-Type: application/json' localhost:2019/load --data '{"apps":{"http":{"servers":{"srv0":{"listen":[":443",":80"],"routes":[{"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"vars","root":"/home/deploy/nameless-pond-2385/current/public"},{"handler":"encode","encodings":{"gzip":{},"zstd":{}}}]},{"handle":[{"handler":"reverse_proxy","upstreams":[{"dial":"127.0.0.1:9010"}],"trusted_proxies":["173.245.48.0/20","103.21.244.0/22","103.22.200.0/22","103.31.4.0/22","141.101.64.0/18","108.162.192.0/18","190.93.240.0/20","188.114.96.0/20","197.234.240.0/22","198.41.128.0/17","162.158.0.0/15","104.16.0.0/13","104.24.0.0/14","172.64.0.0/13","131.0.72.0/22","2400:cb00::/32","2606:4700::/32","2803:f800::/32","2405:b500::/32","2405:8100::/32","2a06:98c0::/29","2c0f:f248::/32"]}],"match":[{"not":[{"file":{"try_files":["{http.request.uri.path}","index.html"]}}]}]},{"handle":[{"handler":"file_server"}]}]}],"match":[{"host":["yvgpy.hatchboxdev.com","192.168.64.4"]}],"terminal":true},{"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"vars","root":"/home/deploy/solitary-snow-1183/current/public"},{"handler":"encode","encodings":{"gzip":{},"zstd":{}}}]},{"handle":[{"handler":"reverse_proxy","upstreams":[{"dial":"127.0.0.1:9000"}],"trusted_proxies":["173.245.48.0/20","103.21.244.0/22","103.22.200.0/22","103.31.4.0/22","141.101.64.0/18","108.162.192.0/18","190.93.240.0/20","188.114.96.0/20","197.234.240.0/22","198.41.128.0/17","162.158.0.0/15","104.16.0.0/13","104.24.0.0/14","172.64.0.0/13","131.0.72.0/22","2400:cb00::/32","2606:4700::/32","2803:f800::/32","2405:b500::/32","2405:8100::/32","2a06:98c0::/29","2c0f:f248::/32"]}],"match":[{"not":[{"file":{"try_files":["{http.request.uri.path}","index.html"]}}]}]},{"handle":[{"handler":"file_server"}]}]}],"match":[{"host":["6nv01.hatchboxdev.com","192.168.64.4"]}],"terminal":true}],"errors":{"routes":[{"match":[{"host":["yvgpy.hatchboxdev.com","6nv01.hatchboxdev.com"]}],"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"headers","response":{"add":{"Cache-Control":["no-cache"],"expires":["0"]}}}]},{"handle":[{"handler":"vars","root":"/home/deploy/.hatchbox/templates"}]},{"handle":[{"handler":"rewrite","uri":"/error.html"}]},{"handle":[{"handler":"file_server"}]}]}],"terminal":true}]},"tls_connection_policies":[{}]}}},"tls":{"automation":{"policies":[{"subjects":["yvgpy.hatchboxdev.com"],"on_demand":true},{"subjects":["6nv01.hatchboxdev.com"],"on_demand":true}],"on_demand":{"ask":"http://app.lvh.me:3000/api/v1/caddy/ask","rate_limit":{"interval":"2m","burst":5}}},"certificates":{"load_files":[]}}},"logging":{"logs":{"default":{"encoder":{"format":"console"},"level":"debug"}}}}'
```
2. Updating it to remove the `on_demand` key with rate limit (Fails)

```bash
curl --max-time 5 -s --fail-with-body -X POST -H 'Content-Type: application/json' localhost:2019/load --data '{"apps":{"http":{"servers":{"srv0":{"listen":[":443",":80"],"routes":[{"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"vars","root":"/home/deploy/nameless-pond-2385/current/public"},{"handler":"encode","encodings":{"gzip":{},"zstd":{}}}]},{"handle":[{"handler":"reverse_proxy","upstreams":[{"dial":"127.0.0.1:9010"}],"trusted_proxies":["173.245.48.0/20","103.21.244.0/22","103.22.200.0/22","103.31.4.0/22","141.101.64.0/18","108.162.192.0/18","190.93.240.0/20","188.114.96.0/20","197.234.240.0/22","198.41.128.0/17","162.158.0.0/15","104.16.0.0/13","104.24.0.0/14","172.64.0.0/13","131.0.72.0/22","2400:cb00::/32","2606:4700::/32","2803:f800::/32","2405:b500::/32","2405:8100::/32","2a06:98c0::/29","2c0f:f248::/32"]}],"match":[{"not":[{"file":{"try_files":["{http.request.uri.path}","index.html"]}}]}]},{"handle":[{"handler":"file_server"}]}]}],"match":[{"host":["yvgpy.hatchboxdev.com","192.168.64.4"]}],"terminal":true},{"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"vars","root":"/home/deploy/solitary-snow-1183/current/public"},{"handler":"encode","encodings":{"gzip":{},"zstd":{}}}]},{"handle":[{"handler":"reverse_proxy","upstreams":[{"dial":"127.0.0.1:9000"}],"trusted_proxies":["173.245.48.0/20","103.21.244.0/22","103.22.200.0/22","103.31.4.0/22","141.101.64.0/18","108.162.192.0/18","190.93.240.0/20","188.114.96.0/20","197.234.240.0/22","198.41.128.0/17","162.158.0.0/15","104.16.0.0/13","104.24.0.0/14","172.64.0.0/13","131.0.72.0/22","2400:cb00::/32","2606:4700::/32","2803:f800::/32","2405:b500::/32","2405:8100::/32","2a06:98c0::/29","2c0f:f248::/32"]}],"match":[{"not":[{"file":{"try_files":["{http.request.uri.path}","index.html"]}}]}]},{"handle":[{"handler":"file_server"}]}]}],"match":[{"host":["6nv01.hatchboxdev.com","192.168.64.4"]}],"terminal":true}],"errors":{"routes":[{"match":[{"host":["yvgpy.hatchboxdev.com","6nv01.hatchboxdev.com"]}],"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"headers","response":{"add":{"Cache-Control":["no-cache"],"expires":["0"]}}}]},{"handle":[{"handler":"vars","root":"/home/deploy/.hatchbox/templates"}]},{"handle":[{"handler":"rewrite","uri":"/error.html"}]},{"handle":[{"handler":"file_server"}]}]}],"terminal":true}]},"tls_connection_policies":[{}]}}},"tls":{"automation":{"policies":[{"subjects":["yvgpy.hatchboxdev.com"],"on_demand":true},{"subjects":["6nv01.hatchboxdev.com"],"on_demand":true}]},"certificates":{"load_files":[]}}},"logging":{"logs":{"default":{"encoder":{"format":"console"},"level":"debug"}}}}'
```

3. DELETE /config/apps/tls/automation/on_demand also fails

**Comment by mholt** [comment]
Ah right, thanks. So you're removing an on_demand configuration. I was thrown off because it turns out that panic message is emitted in 3 possible places in CertMagic, not just 1, so seeing the extra info is helpful.

Now I'm thinking it's because I have these 2 lines backwards:

https://github.com/caddyserver/caddy/blob/a7db0cfe55b524a34a310e852af6c9520134db10/modules/caddytls/tls.go#L185-L186

Simply reversing the order of those lines (setting window to 0 first) should fix it.

I'm would try it but my curl installation is currently broken and I haven't been able to fix it yet. I'm working on that -- would you be able to confirm whether the change in #5443 fixes it for you?

**Comment by excid3** [comment]
Thanks @mholt! That makes a lot of sense. I will give that a try.

**Comment by excid3** [comment]
Well, it changed the error at least:

```curl --max-time 5 -s --fail-with-body -X POST -H 'Content-Type: application/json' localhost:2019/load --data '{"apps":{"http":{"servers":{"srv0":{"listen":[":443",":80"],"routes":[{"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"vars","root":"/home/deploy/nameless-pond-2385/current/public"},{"handler":"encode","encodings":{"gzip":{},"zstd":{}}}]},{"handle":[{"handler":"reverse_proxy","upstreams":[{"dial":"127.0.0.1:9010"}],"trusted_proxies":["173.245.48.0/20","103.21.244.0/22","103.22.200.0/22","103.31.4.0/22","141.101.64.0/18","108.162.192.0/18","190.93.240.0/20","188.114.96.0/20","197.234.240.0/22","198.41.128.0/17","162.158.0.0/15","104.16.0.0/13","104.24.0.0/14","172.64.0.0/13","131.0.72.0/22","2400:cb00::/32","2606:4700::/32","2803:f800::/32","2405:b500::/32","2405:8100::/32","2a06:98c0::/29","2c0f:f248::/32"]}],"match":[{"not":[{"file":{"try_files":["{http.request.uri.path}","index.html"]}}]}]},{"handle":[{"handler":"file_server"}]}]}],"match":[{"host":["yvgpy.hatchboxdev.com","192.168.64.4"]}],"terminal":true},{"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"vars","root":"/home/deploy/solitary-snow-1183/current/public"},{"handler":"encode","encodings":{"gzip":{},"zstd":{}}}]},{"handle":[{"handler":"reverse_proxy","upstreams":[{"dial":"127.0.0.1:9000"}],"trusted_proxies":["173.245.48.0/20","103.21.244.0/22","103.22.200.0/22","103.31.4.0/22","141.101.64.0/18","108.162.192.0/18","190.93.240.0/20","188.114.96.0/20","197.234.240.0/22","198.41.128.0/17","162.158.0.0/15","104.16.0.0/13","104.24.0.0/14","172.64.0.0/13","131.0.72.0/22","2400:cb00::/32","2606:4700::/32","2803:f800::/32","2405:b500::/32","2405:8100::/32","2a06:98c0::/29","2c0f:f248::/32"]}],"match":[{"not":[{"file":{"try_files":["{http.request.uri.path}","index.html"]}}]}]},{"handle":[{"handler":"file_server"}]}]}],"match":[{"host":["6nv01.hatchboxdev.com","192.168.64.4"]}],"terminal":true}],"errors":{"routes":[{"match":[{"host":["yvgpy.hatchboxdev.com","6nv01.hatchboxdev.com"]}],"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"headers","response":{"add":{"Cache-Control":["no-cache"],"expires":["0"]}}}]},{"handle":[{"handler":"vars","root":"/home/deploy/.hatchbox/templates"}]},{"handle":[{"handler":"rewrite","uri":"/error.html"}]},{"handle":[{"handler":"file_server"}]}]}],"terminal":true}]},"tls_connection_policies":[{}]}}},"tls":{"automation":{"policies":[{"subjects":["yvgpy.hatchboxdev.com"],"on_demand":true},{"subjects":["6nv01.hatchboxdev.com"],"on_demand":true}]},"certificates":{"load_files":[]}}},"logging":{"logs":{"default":{"encoder":{"format":"console"},"level":"debug"}}}}'
{"error":"loading config: loading new config: loading http app module: provision http: getting tls app: loading tls app module: provision tls: provisioning automation policy 0: on-demand TLS cannot be enabled without an 'ask' endpoint to prevent abuse; please refer to documentation for details"}
```

**Comment by francislavoie** [comment]
That error is correct, we made a change to require `ask` in circumstances where the domain is not known. See https://github.com/caddyserver/caddy/commit/b97c76fb4789b8da0b80f5a2c1c1c5bebba163b5

We have to be more strict because some ACME CAs were seeing a lot of abuse and asked us to make it required to force users to only allow domains they actually trust.

**Comment by excid3** [comment]
I'm removing the entire `on_demand: {}`, so it shouldn't be requiring an ask.

**Comment by francislavoie** [comment]
You still have `"on_demand":true` in your config though.

**Comment by excid3** [comment]
I'm removing the on_demand tls automation, not those.

I want to lazy load the certs for domains, but not wildcards.

**Comment by mholt** [comment]
I'll take a closer look at this today or Monday

**Comment by francislavoie** [comment]
I pushed another commit to #5443 to fix it if you could try that @excid3
