### ISSUE TITLE
Caddy crash - quic protocol error since v2.7.2

### ISSUE THREAD

**Issue by RainmakerRaw** [caddyserver/caddy#5681]
Edit: Sorry this seems to be related to #5680 but I was looking for QUIC and protocol errors in the titles, so I missed it. Apologies, happy to have this moved and tacked onto the end of that Issue if that's better. 
---
Since upgrading to Caddy v2.7.2 I can only load some of my reverse proxied sites. Some, like SABNzbd and my Synology NAS webUI (DSM) load fine. Jellyfin and Plex both crash Caddy with the following, and it seems to be that http2 loads fine but http3/quic crashes the server. Caddy was installed from the cloudsmith repo (to get the service files) and then I used `sudo caddy add-package` to add Cloudflare DNS.  
  
I hesitated in leaving in the URLs and IP but I figured it may help troubleshooting. Please don't hesitate to let me know if I can provide any further (or better) information. This is probably PEBCAK because I'm fairly new to Caddy, but the SEGSEV memory errors made me think I'd better file an Issue. Thanks! 

```
░░ Subject: A start job for unit caddy.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit caddy.service has finished successfully.
░░
░░ The job identifier is 3517.
Aug 03 17:42:38 rock5b caddy[7679]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 03 17:42:38 rock5b caddy[7679]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x47b1dc]
Aug 03 17:42:38 rock5b caddy[7679]: goroutine 185 [running]:
Aug 03 17:42:38 rock5b caddy[7679]: github.com/caddyserver/certmagic.(*Config).getCertDuringHandshake(0x40002805b0, {0x1963158, 0x4000138008}, _, _)
Aug 03 17:42:38 rock5b caddy[7679]:         github.com/caddyserver/certmagic@v0.19.1/handshake.go:378 +0xf8c
Aug 03 17:42:38 rock5b caddy[7679]: github.com/caddyserver/certmagic.(*Config).GetCertificateWithContext(0x40002805b0, {0x1963158, 0x4000138008}, 0x40002804e0)
Aug 03 17:42:38 rock5b caddy[7679]:         github.com/caddyserver/certmagic@v0.19.1/handshake.go:84 +0x9c4
Aug 03 17:42:38 rock5b caddy[7679]: github.com/caddyserver/certmagic.(*Config).GetCertificate(0x40006e4ee0?, 0x4000726450?)
Aug 03 17:42:38 rock5b caddy[7679]:         github.com/caddyserver/certmagic@v0.19.1/handshake.go:50 +0x30
Aug 03 17:42:38 rock5b caddy[7679]: github.com/caddyserver/caddy/v2/modules/caddytls.(*ConnectionPolicy).buildStandardTLSConfig.func1(0x40002804e0)
Aug 03 17:42:38 rock5b caddy[7679]:         github.com/caddyserver/caddy/v2@v2.7.2/modules/caddytls/connpolicy.go:232 +0x144
Aug 03 17:42:38 rock5b caddy[7679]: github.com/quic-go/qtls-go1-20.(*config).getCertificate(0x40001e0300, 0x40002804e0)
Aug 03 17:42:38 rock5b caddy[7679]:         github.com/quic-go/qtls-go1-20@v0.3.0/common.go:1086 +0x44
Aug 03 17:42:38 rock5b caddy[7679]: github.com/quic-go/qtls-go1-20.(*serverHandshakeStateTLS13).pickCertificate(0x4000adfbb0)
Aug 03 17:42:38 rock5b caddy[7679]:         github.com/quic-go/qtls-go1-20@v0.3.0/handshake_server_tls13.go:415 +0x5c
Aug 03 17:42:38 rock5b caddy[7679]: github.com/quic-go/qtls-go1-20.(*serverHandshakeStateTLS13).handshake(0x4000adfbb0)
Aug 03 17:42:38 rock5b caddy[7679]:         github.com/quic-go/qtls-go1-20@v0.3.0/handshake_server_tls13.go:60 +0x40
Aug 03 17:42:38 rock5b caddy[7679]: github.com/quic-go/qtls-go1-20.(*Conn).serverHandshake(0x40006b6e00, {0x1963120, 0x40002a8690})
Aug 03 17:42:38 rock5b caddy[7679]:         github.com/quic-go/qtls-go1-20@v0.3.0/handshake_server.go:53 +0x138
Aug 03 17:42:38 rock5b caddy[7679]: github.com/quic-go/qtls-go1-20.(*Conn).handshakeContext(0x40006b6e00, {0x19631c8, 0x40009c7110})
Aug 03 17:42:38 rock5b caddy[7679]:         github.com/quic-go/qtls-go1-20@v0.3.0/conn.go:1540 +0x348
Aug 03 17:42:38 rock5b caddy[7679]: github.com/quic-go/qtls-go1-20.(*Conn).HandshakeContext(0x0?, {0x19631c8?, 0x40009c7110?})
Aug 03 17:42:38 rock5b caddy[7679]:         github.com/quic-go/qtls-go1-20@v0.3.0/conn.go:1480 +0x24
Aug 03 17:42:38 rock5b caddy[7679]: created by github.com/quic-go/qtls-go1-20.(*QUICConn).Start
Aug 03 17:42:38 rock5b caddy[7679]:         github.com/quic-go/qtls-go1-20@v0.3.0/quic.go:179 +0xc8
Aug 03 17:42:38 rock5b systemd[1]: caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ An ExecStart= process belonging to unit caddy.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 2.
Aug 03 17:42:38 rock5b systemd[1]: caddy.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit caddy.service has entered the 'failed' state with result 'exit-code'.
```
  
The web browser (Brave v1.56.14) reports `ERR_QUIC_PROTOCOL_ERROR`. The Caddy server is running on a ROCK5B arm64 SBC with Debian 11.7 Bullseye with kernel Linux rock5b 5.10.110-11-rockchip #8c4e8d205 SMP. My Caddyfile is as follows: 

```
{
        email redacted@protonmail.com
        acme_dns cloudflare 123456REDACTED
        cert_issuer zerossl 123456REDACTED
        key_type p256
}

#####
# This variable, alongside calling it with 'import admin_redir' in the Vaultwarden section, only allows LAN access to VW's admin page.
(admin_redir) {
        @admin {
                path /admin*
                not remote_ip private_ranges
        }
        redir @admin /
}
#####

*.oursecure.network {
        @oursecure host oursecure.network
        handle @oursecure {
                reverse_proxy 80.194.134.39:443
                encode zstd gzip
                header {
                        Strict-Transport-Security "max-age=31536000;"
                        X-Content-Type-Options "nosniff"
                        X-XSS-Protection "1; mode=block"
                        X-Frame-Options "SAMEORIGIN"
                        X-Robots-Tag "none"
                        Referrer-Policy "strict-origin-when-cross-origin"
                        Content-Security-Policy "frame-src 'self'; frame-ancestors 'self'; object-src 'none';"
                }
        }

        @agh host agh.oursecure.network
        handle @agh {
                reverse_proxy :3000
                encode zstd gzip
                header {
                        Strict-Transport-Security "max-age=31536000;"
                        X-Content-Type-Options "nosniff"
                        X-XSS-Protection "1; mode=block"
                        X-Frame-Options "SAMEORIGIN"
                        X-Robots-Tag "none"
                        Referrer-Policy "strict-origin-when-cross-origin"
                        Content-Security-Policy "frame-src 'self'; frame-ancestors 'self'; object-src 'none';"
                }
        @cctv host cctv.oursecure.network
        handle @cctv {
                reverse_proxy * {
                        to 10.100.0.150:9901
                        transport http {
                                tls
                                tls_insecure_skip_verify
                                read_buffer 8192
                        }
                }
                encode zstd gzip
                header {
                        Strict-Transport-Security "max-age=31536000;"
                        X-Content-Type-Options "nosniff"
                        X-XSS-Protection "1; mode=block"
                        X-Frame-Options "SAMEORIGIN"
                        X-Robots-Tag "none"
                        Referrer-Policy "strict-origin-when-cross-origin"
                        Content-Security-Policy "frame-src 'self'; frame-ancestors 'self'; object-src 'none';"
                }
        }

        @diskstation host diskstation.oursecure.network
        handle @diskstation {
                reverse_proxy * {
                        to 10.100.0.150:5001
                        transport http {
                                tls
                                tls_insecure_skip_verify
                                read_buffer 8192
                        }
                }
                encode zstd gzip
                header {
                        Strict-Transport-Security "max-age=31536000;"
                        X-Content-Type-Options "nosniff"
                        X-XSS-Protection "1; mode=block"
                        X-Frame-Options "SAMEORIGIN"
                        X-Robots-Tag "none"
                        Referrer-Policy "strict-origin-when-cross-origin"
                        Content-Security-Policy "frame-src 'self'; frame-ancestors 'self'; object-src 'none';"
                }
        }
        @homepage host homepage.oursecure.network
        handle @homepage {
                reverse_proxy 10.100.0.150:3300
                encode zstd gzip
                header {
                        Strict-Transport-Security "max-age=31536000;"
                        X-Content-Type-Options "nosniff"
                        X-XSS-Protection "1; mode=block"
                        X-Frame-Options "SAMEORIGIN"
                        X-Robots-Tag "none"
                        Referrer-Policy "strict-origin-when-cross-origin"
                        Content-Security-Policy "frame-src 'self'; frame-ancestors 'self'; object-src 'none';"
                }
        }

        @jellyfin host jellyfin.oursecure.network
        handle @jellyfin {
                reverse_proxy 10.100.0.150:8096
                encode zstd gzip
                header {
                        Strict-Transport-Security "max-age=31536000;"
                        X-Content-Type-Options "nosniff"
                        X-XSS-Protection "1; mode=block"
                        X-Frame-Options "SAMEORIGIN"
                        X-Robots-Tag "none"
                        Referrer-Policy "strict-origin-when-cross-origin"
                        Content-Security-Policy "frame-src 'self'; frame-ancestors 'self'; object-src 'none';"
                }
        }

        @nzbget host nzbget.oursecure.network
        handle @nzbget {
                reverse_proxy 10.100.0.150:6789
                encode zstd gzip
                header {
                        Strict-Transport-Security "max-age=31536000;"
                        X-Content-Type-Options "nosniff"
                        X-XSS-Protection "1; mode=block"
                        X-Frame-Options "SAMEORIGIN"
                        X-Robots-Tag "none"
                        Referrer-Policy "strict-origin-when-cross-origin"
                        Content-Security-Policy "frame-src 'self'; frame-ancestors 'self'; object-src 'none';"
                }
        }

        @ombi host requests.oursecure.network
        handle @ombi {
                reverse_proxy 10.100.0.150:3579
                encode zstd gzip
                header {
                        Strict-Transport-Security "max-age=31536000;"
                        X-Content-Type-Options "nosniff"
                        X-XSS-Protection "1; mode=block"
                        X-Frame-Options "SAMEORIGIN"
                        X-Robots-Tag "none"
                        Referrer-Policy "strict-origin-when-cross-origin"
                        Content-Security-Policy "frame-src 'self'; frame-ancestors 'self'; object-src 'none';"
                }
        }

        @plex host plex.oursecure.network
        handle @plex {
                reverse_proxy * 10.100.0.150:32400
                encode zstd gzip
                header {
                        Strict-Transport-Security "max-age=31536000;"
                        X-Content-Type-Options "nosniff"
                        X-XSS-Protection "1; mode=block"
                        X-Frame-Options "SAMEORIGIN"
                        X-Robots-Tag "none"
                        Referrer-Policy "strict-origin-when-cross-origin"
                        Content-Security-Policy "frame-src 'self'; frame-ancestors 'self'; object-src 'none';"
                }
        }

        @portainer host portainer.oursecure.network
        handle @portainer {
                reverse_proxy 10.100.0.150:9000
                encode zstd gzip
                header {
                        Strict-Transport-Security "max-age=31536000;"
                        X-Content-Type-Options "nosniff"
                        X-XSS-Protection "1; mode=block"
                        X-Frame-Options "SAMEORIGIN"
                        X-Robots-Tag "none"
                        Referrer-Policy "strict-origin-when-cross-origin"
                        Content-Security-Policy "frame-src 'self'; frame-ancestors 'self'; object-src 'none';"
                }
        }
        @qbt host qbt.oursecure.network
        handle @qbt {
                reverse_proxy 10.100.0.150:8380
                encode zstd gzip
                header {
                        Strict-Transport-Security "max-age=31536000;"
                        X-Content-Type-Options "nosniff"
                        X-XSS-Protection "1; mode=block"
                        X-Frame-Options "SAMEORIGIN"
                        X-Robots-Tag "none"
                        Referrer-Policy "strict-origin-when-cross-origin"
                        Content-Security-Policy "frame-src 'self'; frame-ancestors 'self'; object-src 'none';"
                }
        }

        @radarr host radarr.oursecure.network
        handle @radarr {
                reverse_proxy 10.100.0.150:7878
                encode zstd gzip
                header {
                        Strict-Transport-Security "max-age=31536000;"
                        X-Content-Type-Options "nosniff"
                        X-XSS-Protection "1; mode=block"
                        X-Frame-Options "SAMEORIGIN"
                        X-Robots-Tag "none"
                        Referrer-Policy "strict-origin-when-cross-origin"
                        Content-Security-Policy "frame-src 'self'; frame-ancestors 'self'; object-src 'none';"
                }
        }

        @sab host sab.oursecure.network
        handle @sab {
                reverse_proxy 10.100.0.150:8080
                encode zstd gzip
                header {
                        Strict-Transport-Security "max-age=31536000;"
                        X-Content-Type-Options "nosniff"
                        X-XSS-Protection "1; mode=block"
                        X-Frame-Options "SAMEORIGIN"
                        X-Robots-Tag "none"
                        Referrer-Policy "strict-origin-when-cross-origin"
                        Content-Security-Policy "frame-src 'self'; frame-ancestors 'self'; object-src 'none';"
                }
        }
        @search host search.oursecure.network
        handle @search {
                reverse_proxy 10.100.0.150:9017
                encode zstd gzip
                header {
                        Strict-Transport-Security "max-age=31536000;"
                        X-Content-Type-Options "nosniff"
                        X-XSS-Protection "1; mode=block"
                        X-Frame-Options "SAMEORIGIN"
                        X-Robots-Tag "none"
                        Referrer-Policy "strict-origin-when-cross-origin"
                        Content-Security-Policy "frame-src 'self'; frame-ancestors 'self'; object-src 'none';"
                }
        }

        @sonarr host sonarr.oursecure.network
        handle @sonarr {
                reverse_proxy 10.100.0.150:8989
                encode zstd gzip
                header {
                        Strict-Transport-Security "max-age=31536000;"
                        X-Content-Type-Options "nosniff"
                        X-XSS-Protection "1; mode=block"
                        X-Frame-Options "SAMEORIGIN"
                        X-Robots-Tag "none"
                        Referrer-Policy "strict-origin-when-cross-origin"
                        Content-Security-Policy "frame-src 'self'; frame-ancestors 'self'; object-src 'none';"
                }
        }

        @tautulli host tautulli.oursecure.network
        handle @tautulli {
                reverse_proxy 10.100.0.150:8181
                encode zstd gzip
                header {
                        Strict-Transport-Security "max-age=31536000;"
                        X-Content-Type-Options "nosniff"
                        X-XSS-Protection "1; mode=block"
                        X-Frame-Options "SAMEORIGIN"
                        X-Robots-Tag "none"
                        Referrer-Policy "strict-origin-when-cross-origin"
                        Content-Security-Policy "frame-src 'self'; frame-ancestors 'self'; object-src 'none';"
                }
        }
        @vaultwarden host bw.oursecure.network
        handle @vaultwarden {
                encode zstd gzip
                header / {
                        # Enable HTTP Strict Transport Security (HSTS)
                        Strict-Transport-Security "max-age=31536000;"
                        # Enable cross-site filter (XSS) and tell browser to block detected attacks
                        X-XSS-Protection "1; mode=block"
                        # Disallow the site to be rendered within a frame (clickjacking protection)
                        X-Frame-Options "DENY"
                        # Prevent search engines from indexing (optional)
                        X-Robots-Tag "none"
                        # Server name removing
                        -Server
                }
                # Only allow admin access from LAN
                import admin_redir
                # The negotiation endpoint is also proxied to Rocket
                reverse_proxy /notifications/hub/negotiate 10.100.0.150:8228

                # Notifications redirected to the websockets server
                reverse_proxy /notifications/hub 10.100.0.150:3012

                # Proxy the Root directory to Rocket
                reverse_proxy 10.100.0.150:8228 {
                        # Send the true remote IP to Rocket, so that vaultwarden can put this in the
                        # log, so that fail2ban can ban the correct IP.
                        header_up X-Real-IP {remote_host}
                }
        }

        # Fallback for otherwise unhandled domains
        handle {
                abort
        }
}

```

**Comment by mholt** [comment]
Thanks for the report. We need help reproducing the issue though. If you can help us reproduce it we can debug it. Please participate in the existing issue. Thanks!

**Comment by mholt** [comment]
@RainmakerRaw I'll delete it, but it's too late for that, as surely bots / archival services have already snapshotted this page.
