### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by belohnung** [caddyserver/caddy#5690]
After running caddy for a while it exits with a segmentation fault and this stacktrace:
```
Aug 04 13:14:04 hostname caddy[2316314]: panic: runtime error: invalid memory address or nil pointer dereference
Aug 04 13:14:04 hostname caddy[2316314]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x903cd0]
Aug 04 13:14:04 hostname caddy[2316314]: goroutine 52357 [running]:
Aug 04 13:14:04 hostname caddy[2316314]: github.com/caddyserver/certmagic.(*Config).getCertDuringHandshake(0xc0009baa90, {0x203cd68, 0xc000138008}, _, _)
Aug 04 13:14:04 hostname caddy[2316314]:         github.com/caddyserver/certmagic@v0.19.1/handshake.go:378 +0x1390
Aug 04 13:14:04 hostname caddy[2316314]: github.com/caddyserver/certmagic.(*Config).GetCertificateWithContext(0xc0009baa90, {0x203cd68, 0xc000138008}, 0xc0009ba9c0)
Aug 04 13:14:04 hostname caddy[2316314]:         github.com/caddyserver/certmagic@v0.19.1/handshake.go:84 +0xbff
Aug 04 13:14:04 hostname caddy[2316314]: github.com/caddyserver/certmagic.(*Config).GetCertificate(0xc00064e000?, 0xc0011d5630?)
Aug 04 13:14:04 hostname caddy[2316314]:         github.com/caddyserver/certmagic@v0.19.1/handshake.go:50 +0x2a
Aug 04 13:14:04 hostname caddy[2316314]: github.com/caddyserver/caddy/v2/modules/caddytls.(*ConnectionPolicy).buildStandardTLSConfig.func1(0xc0009ba9c0)
Aug 04 13:14:04 hostname caddy[2316314]:         github.com/caddyserver/caddy/v2@v2.7.2/modules/caddytls/connpolicy.go:232 +0x14f
Aug 04 13:14:04 hostname caddy[2316314]: github.com/quic-go/qtls-go1-20.(*config).getCertificate(0xc000800480, 0xc0009ba9c0)
Aug 04 13:14:04 hostname caddy[2316314]:         github.com/quic-go/qtls-go1-20@v0.3.0/common.go:1086 +0x42
Aug 04 13:14:04 hostname caddy[2316314]: github.com/quic-go/qtls-go1-20.(*serverHandshakeStateTLS13).pickCertificate(0xc00067dbe8)
Aug 04 13:14:04 hostname caddy[2316314]:         github.com/quic-go/qtls-go1-20@v0.3.0/handshake_server_tls13.go:415 +0x66
Aug 04 13:14:04 hostname caddy[2316314]: github.com/quic-go/qtls-go1-20.(*serverHandshakeStateTLS13).handshake(0xc00067dbe8)
Aug 04 13:14:04 hostname caddy[2316314]:         github.com/quic-go/qtls-go1-20@v0.3.0/handshake_server_tls13.go:60 +0x53
Aug 04 13:14:04 hostname caddy[2316314]: github.com/quic-go/qtls-go1-20.(*Conn).serverHandshake(0xc00044ce00, {0x203cd30, 0xc000c50af0})
Aug 04 13:14:04 hostname caddy[2316314]:         github.com/quic-go/qtls-go1-20@v0.3.0/handshake_server.go:53 +0x188
Aug 04 13:14:04 hostname caddy[2316314]: github.com/quic-go/qtls-go1-20.(*Conn).handshakeContext(0xc00044ce00, {0x203cdd8, 0xc000dc1f20})
Aug 04 13:14:04 hostname caddy[2316314]:         github.com/quic-go/qtls-go1-20@v0.3.0/conn.go:1540 +0x3ce
Aug 04 13:14:04 hostname caddy[2316314]: github.com/quic-go/qtls-go1-20.(*Conn).HandshakeContext(0xc000873fd0?, {0x203cdd8?, 0xc000dc1f20?})
Aug 04 13:14:04 hostname caddy[2316314]:         github.com/quic-go/qtls-go1-20@v0.3.0/conn.go:1480 +0x25
Aug 04 13:14:04 hostname caddy[2316314]: created by github.com/quic-go/qtls-go1-20.(*QUICConn).Start
Aug 04 13:14:04 hostname caddy[2316314]:         github.com/quic-go/qtls-go1-20@v0.3.0/quic.go:179 +0xcf
Aug 04 13:14:04 hostname systemd[1]: caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

caddy version outputs:
`v2.7.2 h1:QqThyoyUFAv1B7A2NMeaWlz7xmgKqU49PXBX08A+6xg=`

**Comment by indy-singh** [comment]
I had a very similar stack trace [here](https://github.com/caddyserver/caddy/issues/5684). But I was on `2.7.0`, just upgraded to `2.7.2`...
