### ISSUE TITLE
[bug] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by DJTOMATO** [caddyserver/caddy#5710]
Since last update (caddy.Version=v2.7.2 h1:QqThyoyUFAv1B7A2NMeaWlz7xmgKqU49PXBX08A+6xg=)

This error started to popup in my logs and kill the daemon.
I have no steps to reproduce it, it just happens at any time

``` caddy[92146]: panic: runtime error: invalid memory address or nil pointer dereference
 caddy[92146]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x47aefc]
 caddy[92146]: goroutine 104750 [running]:
 caddy[92146]: github.com/caddyserver/certmagic.(*Config).getCertDuringHandshake(0x4000447860, {0x195fbd8, 0x40000          

 caddy[92146]:         github.com/caddyserver/certmagic@v0.19.1/handshake.go:378 +0xf8c
 caddy[92146]: github.com/caddyserver/certmagic.(*Config).GetCertificateWithContext(0x4000447860, {0x195fbd8, 0x40          
790)
 caddy[92146]:         github.com/caddyserver/certmagic@v0.19.1/handshake.go:84 +0x9c4
 caddy[92146]: github.com/caddyserver/certmagic.(*Config).GetCertificate(0x400043aee0?, 0x4000030c98?)
 caddy[92146]:         github.com/caddyserver/certmagic@v0.19.1/handshake.go:50 +0x30
 caddy[92146]: github.com/caddyserver/caddy/v2/modules/caddytls.(*ConnectionPolicy).buildStandardTLSConfig.func1(0          

 caddy[92146]:         github.com/caddyserver/caddy/v2@v2.7.2/modules/caddytls/connpolicy.go:232 +0x144
 caddy[92146]: github.com/quic-go/qtls-go1-20.(*config).getCertificate(0x40001d6000, 0x4000447790)
 caddy[92146]:         github.com/quic-go/qtls-go1-20@v0.3.0/common.go:1086 +0x44
 caddy[92146]: github.com/quic-go/qtls-go1-20.(*serverHandshakeStateTLS13).pickCertificate(0x400053fbb0)
 caddy[92146]:         github.com/quic-go/qtls-go1-20@v0.3.0/handshake_server_tls13.go:415 +0x5c
 caddy[92146]: github.com/quic-go/qtls-go1-20.(*serverHandshakeStateTLS13).handshake(0x400053fbb0)
 caddy[92146]:         github.com/quic-go/qtls-go1-20@v0.3.0/handshake_server_tls13.go:60 +0x40
 caddy[92146]: github.com/quic-go/qtls-go1-20.(*Conn).serverHandshake(0x40003ffc00, {0x195fba0, 0x40018d0370})
 caddy[92146]:         github.com/quic-go/qtls-go1-20@v0.3.0/handshake_server.go:53 +0x138
 caddy[92146]: github.com/quic-go/qtls-go1-20.(*Conn).handshakeContext(0x40003ffc00, {0x195fc48, 0x40007812c0})
 caddy[92146]:         github.com/quic-go/qtls-go1-20@v0.3.0/conn.go:1540 +0x348
 caddy[92146]: github.com/quic-go/qtls-go1-20.(*Conn).HandshakeContext(0x25cfd20?, {0x195fc48?, 0x40007812c0?})
 caddy[92146]:         github.com/quic-go/qtls-go1-20@v0.3.0/conn.go:1480 +0x24
 caddy[92146]: created by github.com/quic-go/qtls-go1-20.(*QUICConn).Start
 caddy[92146]:         github.com/quic-go/qtls-go1-20@v0.3.0/quic.go:179 +0xc8
 systemd[1]: caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
 systemd[1]: caddy.service: Failed with result 'exit-code'.```

**Comment by francislavoie** [comment]
Please use v2.7.3
