### ISSUE TITLE
Use of `--change-host-headers` along with `--header-down` causes `SIGSEGV` but `--header-up` works.

### ISSUE THREAD

**Issue by Y3K** [caddyserver/caddy#6464]
Mixing `--change-host-headers` and `--header-down` causes a panic, thankfully `--header-up` works fine, examples:

This fails.

```bash
$ caddy reverse-proxy \
  --from "https://foo.com:8080" \
  --to "https://bar.com" \
  --change-host-header \
  --internal-certs \
  --disable-redirects \
  --header-down "Access-Control-Allow-Origin: *"

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1420747]
goroutine 1 [running]:
github.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.cmdReverseProxy({0x0?})
        github.com/caddyserver/caddy/v2@v2.8.4/modules/caddyhttp/reverseproxy/command.go:238 +0xda7
github.com/caddyserver/caddy/v2/modules/caddyhttp/reverseproxy.init.2.func1.WrapCommandFuncForCobra.1(0xc000584c08, {0x193f671?, 0x4?, 0x193f645?})
        github.com/caddyserver/caddy/v2@v2.8.4/cmd/cobra.go:137 +0x2f
github.com/spf13/cobra.(*Command).execute(0xc000584c08, {0xc0005861b0, 0x9, 0x9})
        github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0x2ab0ca0)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/caddyserver/caddy/v2/cmd.Main()
        github.com/caddyserver/caddy/v2@v2.8.4/cmd/main.go:75 +0x1d8
main.main()
        caddy/main.go:11 +0xf
```

This works.

```bash
$ caddy reverse-proxy \
  --from "https://foo.com:8080" \
  --to "https://bar.com" \
  --internal-certs \
  --disable-redirects \
  --header-up "Host: {http.reverse_proxy.upstream.hostport}" \
  --header-down "Access-Control-Allow-Origin: *"

2024/07/19 00:31:52.146 WARN    admin   admin endpoint disabled
2024/07/19 00:31:52.146 INFO    http.auto_https automatic HTTP->HTTPS redirects are disabled    {"server_name": "proxy"}
2024/07/19 00:31:52.147 INFO    pki.ca.local    root certificate is already trusted by system   {"path": "storage:pki/authorities/local/root.crt"}
2024/07/19 00:31:52.147 INFO    http    enabling HTTP/3 listener        {"addr": ":8080"}
2024/07/19 00:31:52.147 INFO    failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2024/07/19 00:31:52.147 INFO    tls.cache.maintenance   started background certificate maintenance      {"cache": "0xc0000cbe00"}
2024/07/19 00:31:52.147 INFO    http.log        server running  {"name": "proxy", "protocols": ["h1", "h2", "h3"]}
2024/07/19 00:31:52.147 INFO    http    enabling automatic TLS certificate management   {"domains": ["foo.com"]}
2024/07/19 00:31:52.147 WARN    tls     stapling OCSP   {"error": "no OCSP stapling for [foo.com]: no OCSP server specified in certificate", "identifiers": ["foo.com"]}
2024/07/19 00:31:52.148 INFO    caddy proxying  {"from": "https://foo.com:8080", "to": ["bar.com:443"]}
2024/07/19 00:31:52.150 INFO    tls     storage cleaning happened too recently; skipping for now        {"storage": "FileStorage:/home/y3k/.local/share/caddy", "instance": "6792d0b7-4738-41cb-b32a-0bd7a488baa7", "try_again": "2024/07/20 00:31:52.150", "try_again_in": 86399.999999709}
2024/07/19 00:31:52.150 INFO    tls     finished cleaning storage units
```

I have 0 Go experience, otherwise I'd love to help fixing this myself.

Thank you for your amazing effort and even more amazing software.

Godspeed.

**Comment by mholt** [comment]
Ohh nice catch! Thanks for the report. Fixed :)

**Comment by Y3K** [comment]
That was FAST ⚡ !

Thank you so much, wish you a great day.
