### ISSUE TITLE
ARI causing panic with Buypass and On Demand TLS

### ISSUE THREAD

**Issue by user16920** [caddyserver/caddy#6561]
Buypass recently seems to have added ARI support (https://community.buypass.com/t/60y86wy/changelog) which started triggering a panic in caddy when using On-Demand-TLS.
The server keeps on running, but the connection is terminated

## caddy version
v2.8.4 h1:q3pe0wpBj1OcHFZ3n/1nl4V4bxBrYoSoab7rL9BMYNk=

## Config to reproduce

```
{
  debug
  email example@example.com
  acme_ca https://api.test4.buypass.no/acme/directory # also panics with prod ca https://api.buypass.com/acme/directory
  on_demand_tls {
    ask http://127.0.0.1:8080/
  }
}

http://127.0.0.1:8080 {
  @ok_domain query domain=example.com
  respond @ok_domain 200
  respond 404
}

:80, :443 {
  tls {
    on_demand
  }
  respond "OK" 200
}
```
## Panic message
```
http: panic serving 192.168.0.4:46104: runtime error: invalid memory address or nil pointer dereference
goroutine 35 [running]:
net/http.(*conn).serve.func1()
        /usr/lib/golang/src/net/http/server.go:1868 +0xb9
panic({0x5618b61e35e0?, 0x5618b6fce7e0?})
        /usr/lib/golang/src/runtime/panic.go:920 +0x270
github.com/caddyserver/certmagic.(*Config).storageHasNewerARI(_, {_, _}, {{{0xc0006e2240, 0x2, 0x2}, {0x5618b634ede0, 0xc0006e2450}, {0x0, 0x0, ...}, ...}, ...})
        /builddir/go/pkg/mod/github.com/caddyserver/certmagic@v0.21.3/maintain.go:430 +0x208
github.com/caddyserver/certmagic.(*Config).updateARI(_, {_, _}, {{{0xc0006e2240, 0x2, 0x2}, {0x5618b634ede0, 0xc0006e2450}, {0x0, 0x0, ...}, ...}, ...}, ...)
        /builddir/go/pkg/mod/github.com/caddyserver/certmagic@v0.21.3/maintain.go:473 +0x55c
github.com/caddyserver/certmagic.(*Config).handshakeMaintenance(_, {_, _}, _, {{{0xc0006e2240, 0x2, 0x2}, {0x5618b634ede0, 0xc0006e2450}, {0x0, ...}, ...}, ...})
        /builddir/go/pkg/mod/github.com/caddyserver/certmagic@v0.21.3/handshake.go:588 +0xe25
github.com/caddyserver/certmagic.(*Config).loadCertFromStorage(_, {_, _}, _, _)
        /builddir/go/pkg/mod/github.com/caddyserver/certmagic@v0.21.3/handshake.go:415 +0x7e5
github.com/caddyserver/certmagic.(*Config).obtainOnDemandCertificate(_, {_, _}, _)
        /builddir/go/pkg/mod/github.com/caddyserver/certmagic@v0.21.3/handshake.go:534 +0x745
github.com/caddyserver/certmagic.(*Config).getCertDuringHandshake(_, {_, _}, _, _)
        /builddir/go/pkg/mod/github.com/caddyserver/certmagic@v0.21.3/handshake.go:369 +0x111c
github.com/caddyserver/certmagic.(*Config).GetCertificateWithContext(0xc000907b20, {0x5618b6447368, 0xc00033f770}, 0xc0004add40)
        /builddir/go/pkg/mod/github.com/caddyserver/certmagic@v0.21.3/handshake.go:92 +0xc7d
github.com/caddyserver/certmagic.(*Config).GetCertificate(...)
        /builddir/go/pkg/mod/github.com/caddyserver/certmagic@v0.21.3/handshake.go:49
github.com/caddyserver/caddy/v2/modules/caddytls.(*ConnectionPolicy).buildStandardTLSConfig.func1(0xc0004add40)
        /builddir/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.8.4/modules/caddytls/connpolicy.go:242 +0x170
crypto/tls.(*Config).getCertificate(0xc0004cb6c0, 0xc0004add40)
        /usr/lib/golang/src/crypto/tls/common.go:1120 +0x3b
crypto/tls.(*serverHandshakeStateTLS13).pickCertificate(0xc0005fd7e0)
        /usr/lib/golang/src/crypto/tls/handshake_server_tls13.go:431 +0x314
crypto/tls.(*serverHandshakeStateTLS13).handshake(0xc0005fd7e0)
        /usr/lib/golang/src/crypto/tls/handshake_server_tls13.go:55 +0x53
crypto/tls.(*Conn).serverHandshake(0xc0004d5880, {0x5618b6447368, 0xc00033f770})
        /usr/lib/golang/src/crypto/tls/handshake_server.go:53 +0x185
crypto/tls.(*Conn).handshakeContext(0xc0004d5880, {0x5618b6447330, 0xc00002cfc0})
        /usr/lib/golang/src/crypto/tls/conn.go:1552 +0x3d3
crypto/tls.(*Conn).HandshakeContext(...)
        /usr/lib/golang/src/crypto/tls/conn.go:1492
net/http.(*conn).serve(0xc0004daa20, {0x5618b6447330, 0xc00002cf60})
        /usr/lib/golang/src/net/http/server.go:1891 +0xd8a
created by net/http.(*Server).Serve in goroutine 29
        /usr/lib/golang/src/net/http/server.go:3086 +0x5cb
```

**Comment by mholt** [comment]
Interesting. I think this should patch it right up: https://github.com/caddyserver/certmagic/commit/aad674cda5ba191b4ffce509f05bea5ef8534da9

The panic only happens when the loaded cert has an ARI window or the stored cert does NOT have one; now we check to make sure the stored cert ARI has a RetryAfter at all before seeing if it's after the loaded cert's RetryAfter.

Are you able to build and test with that version of certmagic? `xcaddy build --replace github.com/caddyserver/certmagic=github.com/caddyserver/certmagic@master`

**Comment by mholt** [comment]
Wonderful! Thanks for verifying. It will go out with the next release.
