### ISSUE TITLE
panic: certificate worker: runtime error invalid memory address or nil pointer dereference from certmagic

### ISSUE THREAD

**Issue by omertahaoztop** [caddyserver/caddy#6609]
I am facing with some error on our some Caddy Servers

```
{"level":"info","ts":1728241147.0235646,"msg":"panic: certificate worker: runtime error: invalid memory address or nil pointer dereference\ngoroutine 2376 [running]:\ngithub.com/caddyserver/certmagic.(*jobManager).worker.func1()\n\tgithub.com/caddyserver/certmagic@v0.21.3/async.go:58 +0x65\npanic({0x1b15f00?, 0x3f0d9a0?})\n\truntime/panic.go:770 +0x132\ngithub.com/caddyserver/certmagic.(*Config).storageHasNewerARI(_, {_, _}, {{{0xc0014f9da0, 0x2, 0x2}, {0x1cb99c0, 0xc001408150}, {0x0, 0x0, ...}, ...}, ...})\n\tgithub.com/caddyserver/certmagic@v0.21.3/maintain.go:430 +0x208\ngithub.com/caddyserver/certmagic.(*Config).updateARI(_, {_, _}, {{{0xc0014f9da0, 0x2, 0x2}, {0x1cb99c0, 0xc001408150}, {0x0, 0x0, ...}, ...}, ...}, ...)\n\tgithub.com/caddyserver/certmagic@v0.21.3/maintain.go:473 +0x55c\ngithub.com/caddyserver/certmagic.(*Config).manageOne.func2()\n\tgithub.com/caddyserver/certmagic@v0.21.3/config.go:453 +0x28b\ngithub.com/caddyserver/certmagic.(*jobManager).worker(0x3f34a80)\n\tgithub.com/caddyserver/certmagic@v0.21.3/async.go:73 +0x11b\ncreated by github.com/caddyserver/certmagic.(*jobManager).Submit in goroutine 1\n\tgithub.com/caddyserver/certmagic@v0.21.3/async.go:50 +0x279"}
```

We are using Redis Storage module

```
caddy.storage.redis
dns.providers.cloudflare
http.authentication.providers.authorizer
http.handlers.authenticator
http.ip_sources.cloudflare
http.matchers.maxmind_geolocation
security
```

But i don't think is the problem about storage.redis, i also encountered this error in places that use local disk for storage.

**Comment by mholt** [comment]
Ah, this is already fixed in 0.21.4: https://github.com/caddyserver/certmagic/compare/v0.21.3...v0.21.4

Thanks for the report!

**Comment by aa-shalin** [comment]
I saw the same error message today and I'm on Caddy 2.9.1 which uses certmagic 0.21.6.

```
2025-06-23T13:45:50.254-07:00{"level":"debug","ts":1750711550.254067,"logger":"http.handlers.reverse_proxy","msg":"upstream roundtrip","upstream":"<redacted>","duration":0.007926562,"request":{"remote_ip":"<redacted>","remote_port":"39646","client_ip":"<redacted>","proto":"HTTP/2.0","method":"GET","host":"<redacted>","uri":"<redacted>","headers":{"Priority":["u=1"],"Sec-Ch-Ua-Platform":["\"Linux\""],"Sec-Ch-Ua":["\"Google Chrome\";v=\"137\", \"Chromium\";v=\"137\", \"Not/A)Brand\";v=\"24\""],"Accept":["*/*"],"Referer":["<redacted>"],"User-Agent":["<redacted>"],"Origin":["<redacted>"],"Sec-Fetch-Site":["same-origin"],"X-Forwarded-For":["<redacted>"],"X-Forwarded-Proto":["https"],"Sec-Fetch-Mode":["cors"],"Accept-Encoding":["gzip, deflate, br, zstd"],"Accept-Language":["en-US,en;q=0.9"],"Sec-Fetch-Dest":["font"],"Sec-Ch-Ua-Mobile":["?0"],"X-Forwarded-Host":["<redacted>"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"<redacted>"}},"headers":{"Alt-Svc":["h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"],"Content-Length":["330908"],"Last-Modified":["Mon, 23 Jun 2025 20:30:10 GMT"],"Strict-Transport-Security":["max-age=31536000; includeSubDomains"],"Accept-Ranges":["bytes"],"Cache-Control":["max-age=3600,public"],"Date":["Mon, 23 Jun 2025 20:45:50 GMT"],"Content-Type":["font/woff2"],"Etag":["\"6859b952-50c9c\""],"Via":["1.1 google"]},"status":200}
2025-06-23T13:45:50.264-07:00{"level":"info","ts":1750711550.2639613,"logger":"tls.on_demand","msg":"reloaded ARI with newer one in storage","identifiers":["<redacted>"],"server_name":"<redacted>","identifiers":["<redacted>"],"cert_hash":"<redacted>","cert_expiry":1753168901,"next_refresh":1750733138.9372587,"renewal_time":1755929646}
2025-06-23T13:45:50.264-07:00{"level":"warn","ts":1750711550.2640033,"logger":"tls.on_demand","msg":"ARI window or selected renewal time changed","identifiers":["<redacted>"],"server_name":"<redacted>","identifiers":["<redacted>"],"cert_hash":"<redacted>","cert_expiry":1753168901,"prev_start":1750500346,"next_start":1755815472,"prev_end":1750655795,"next_end":1755970921,"prev_selected_time":1750611544,"next_selected_time":1755929646,"explanation_url":""}
2025-06-23T13:45:50.333-07:00panic: runtime error: invalid memory address or nil pointer dereference
2025-06-23T13:45:50.333-07:00[signal SIGSEGV: segmentation violation code=0x1 addr=0x3d8 pc=0x909491]
2025-06-23T13:45:50.333-07:00
2025-06-23T13:45:50.333-07:00goroutine 21111225 [running]:
2025-06-23T13:45:50.347-07:00github.com/caddyserver/certmagic.(*Config).certNeedsRenewal(0xc0028529a0, 0x0, {{{0x0, 0xee0399530, 0x0}, {0x0, 0xee03bf469, 0x0}}, {0x0, 0x0}, ...}, ...)
2025-06-23T13:45:50.347-07:00	github.com/caddyserver/certmagic@v0.21.6/certificates.go:95 +0x91
2025-06-23T13:45:50.347-07:00github.com/caddyserver/certmagic.(*Config).handshakeMaintenance.func1({_, _}, _, {{{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...})
2025-06-23T13:45:50.347-07:00	github.com/caddyserver/certmagic@v0.21.6/handshake.go:564 +0xa5
2025-06-23T13:45:50.347-07:00github.com/caddyserver/certmagic.(*Config).handshakeMaintenance.func2(_, {{{0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, ...}, ...}, ...}, ...)
2025-06-23T13:45:50.348-07:00	github.com/caddyserver/certmagic@v0.21.6/handshake.go:625 +0x34e
2025-06-23T13:45:50.348-07:00created by github.com/caddyserver/certmagic.(*Config).handshakeMaintenance in goroutine 21111200
```

Building Caddy with this Dockerfile
```
FROM golang:1.24.1 AS builder

RUN go install github.com/caddyserver/xcaddy/cmd/xcaddy@v0.4.2 \
    && xcaddy build v2.9.1 \
       --with github.com/caddy-dns/googleclouddns@v1.0.4 \
       --with github.com/mholt/caddy-ratelimit@v0.1.0 \
       --with github.com/jasonlovesdoggo/caddy-defender@v0.7.0

FROM caddy:2.9.1

RUN rm -rf /usr/bin/caddy

COPY --from=builder /go/caddy /usr/bin/caddy

RUN chmod +x /usr/bin/caddy

RUN apk add jq

ADD Caddyfile /etc/caddy/Caddyfile

CMD ["/usr/bin/caddy", "run", "--config", "/etc/caddy/Caddyfile"]

```

And I use filesystem for storing the certificates. The error causes Kubernetes to restart the Caddy container.

**Comment by mholt** [comment]
@aa-shalin Your error is different -- can you please open a new issue with enough details to reproduce the error? (esp. config and full logs)

**Comment by aa-shalin** [comment]
@mholt Thanks for the feedback. I created a new issue: https://github.com/caddyserver/certmagic/issues/344
