### ISSUE TITLE
panic: close of closed channel after running caddy stop

### ISSUE THREAD

**Issue by voltagex** [caddyserver/caddy#6707]
v2.8.4 h1:q3pe0wpBj1OcHFZ3n/1nl4V4bxBrYoSoab7rL9BMYNk= on aarch64 - cross compiled with xcaddy
```
panic: close of closed channel

goroutine 21 [running]:
github.com/caddyserver/caddy/v2/modules/caddytls.(*TLS).Stop(0x40002ff2c0)
        github.com/caddyserver/caddy/v2@v2.8.4/modules/caddytls/tls.go:338 +0x2c
github.com/caddyserver/caddy/v2.unsyncedStop({{0x1970cc0, 0x4000557b30}, 0x40002b0270, 0x40003c2780, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, ...})                                                                                                            github.com/caddyserver/caddy/v2@v2.8.4/caddy.go:677 +0xcc
github.com/caddyserver/caddy/v2.Stop()
        github.com/caddyserver/caddy/v2@v2.8.4/caddy.go:646 +0x138
github.com/caddyserver/caddy/v2.exitProcess({0x1970c50, 0x26037c0}, 0x4000982300)
        github.com/caddyserver/caddy/v2@v2.8.4/caddy.go:721 +0x248
github.com/caddyserver/caddy/v2.exitProcessFromSignal({0x1443925, 0x7})                                                         github.com/caddyserver/caddy/v2@v2.8.4/sigtrap.go:59 +0xe4
github.com/caddyserver/caddy/v2.trapSignalsPosix.func1()
        github.com/caddyserver/caddy/v2@v2.8.4/sigtrap_posix.go:44 +0x4f8
created by github.com/caddyserver/caddy/v2.trapSignalsPosix in goroutine 1
        github.com/caddyserver/caddy/v2@v2.8.4/sigtrap_posix.go:31 +0x24
```

I'm not sure I can reproduce this but I don't think I've seen it before.

**Comment by mholt** [comment]
Thanks for the report. Sorry I have not replied until now.

Do you have any further details about reproducing it? It's almost like the server was stopped twice somehow.

**Comment by voltagex** [comment]
It was on an OpenWrt system, all /etc/init.d/caddy stop did was run 'caddy stop'! The only thing I can think of is that the system sent a SIGTERM or similar while Caddy was in the middle of stopping.

**Comment by mholt** [comment]
Hm, I guess that's possible. Turns out I wasn't doing an atomic CompareAndSwap for exiting. Thanks, hopefully that commit fixes it!

**Comment by Devilisrabits** [comment]
You good
