### ISSUE TITLE
Invalid memory address

### ISSUE THREAD

**Issue by Justman100** [caddyserver/caddy#6755]
Get only this:

> panic: certificate worker: runtime error: invalid memory address or nil pointer dereference

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Add a nil check before accessing the OnDemand field of the Automation struct to prevent a panic caused by a nil pointer dereference in the certificate worker.

You can review changes in this commit: https://github.com/mark-addams001881/caddyserver-caddy-6755/commit/d7048a05bd22dabb02be9e051233754b4a9286d6.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by mohammed90** [comment]
Ideally, we need to be able to reproduce the bug _in the most minimal way possible_. This allows us to write regression tests to verify the fix is working. If we can't reproduce it, then you'll have to test our changes for us until it's fixed -- and then we can't add test cases, either.

I've attached a template below that will help make this easier and faster! **This will require some effort on your part -- please understand that we will be dedicating time to fix the bug you are reporting if you can just help us understand it and reproduce it easily.**

This template will ask for some information you've already provided; that's OK, just fill it out the best you can. :+1: I've also included some helpful tips below the template. Feel free to let me know if you have any questions!

Thank you again for your report, we look forward to resolving it!

## Template

<pre><code>## 1. Environment

### 1a. Operating system and version

```
paste here
```


### 1b. Caddy version (run `caddy version` or paste commit SHA)

```
paste here
```


### 1c. Go version (if building Caddy from source; run `go version`)

```
paste here
```


## 2. Description

### 2a. What happens (briefly explain what is wrong)




### 2b. Why it's a bug (if it's not obvious)




### 2c. Log output

```
paste terminal output or logs here
```



### 2d. Workaround(s)




### 2e. Relevant links




## 3. Tutorial (minimal steps to reproduce the bug)




</code></pre>

## Helpful tips

1. **Environment**: Please fill out your OS and Caddy versions, even if you don't think they are relevant. (They are _always_ relevant.) If you built Caddy from source, provide the commit SHA and specify your exact Go version.

2. **Description:** Describe at a high level what the bug is. What happens? Why is it a bug? Not all bugs are obvious, so convince readers that it's actually a bug.
	- **2c) Log output:** Paste terminal output and/or complete logs in a code block. [DO NOT REDACT INFORMATION except for credentials.](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)
	- **2d) Workaround:** What are you doing to work around the problem in the meantime? This can help others who encounter the same problem, until we implement a fix.
	- **2e) Relevant links:** Please link to any related issues, pull requests, docs, and/or discussion. This can add crucial context to your report.

3. **Tutorial:** What are the _minimum required specific steps_ someone needs to take in order to experience the same bug? Your goal here is to make sure that anyone else can have the same experience with the bug as you do. You are writing a tutorial, so make sure to carry it out yourself before posting it. Please:
	- Start with an empty config. Add _only_ the lines/parameters that are _absolutely required_ to reproduce the bug.
	- Do not run Caddy inside containers.
	- Run Caddy manually in your terminal; do not use systemd or other init systems.
	- If making HTTP requests, avoid web browsers. Use a simpler HTTP client instead, like `curl`.
	- Do not redact any information from your config (except credentials). Domain names are public knowledge and [often necessary for quick resolution of an issue](https://caddy.community/t/how-to-get-help-with-caddy-more-effectively/5222)!
	- Note that ignoring this advice may result in delays, or even in your issue being closed. 😞 Only actionable issues are kept open, and if there is not enough information or clarity to reproduce the bug, then the report is not actionable.

Example of a tutorial:

<blockquote>Create a config file:

```
{ ... }
```

Open terminal and run Caddy:

```
$ caddy ...
```

Make an HTTP request:

```
$ curl ...
```

Notice that the result is ___ but it should be ___.</blockquote>

**Comment by mxpimp5323** [comment]
## 1. Environment

**Comment by mohammed90** [comment]
Closing due to inactivity. Feel free to reopen once you have the details. Try wih the latest version.

**Comment by mkibp** [comment]
@mohammed90 

```
Feb 26 15:19:34 koha systemd[1]: Stopped caddy.service - Caddy.
Feb 26 15:19:34 koha systemd[1]: Starting caddy.service - Caddy...
Feb 26 15:19:34 koha caddy[406896]: caddy.HomeDir=/var/lib/caddy
Feb 26 15:19:34 koha caddy[406896]: caddy.AppDataDir=/var/lib/caddy/.local/share/caddy
Feb 26 15:19:34 koha caddy[406896]: caddy.AppConfigDir=/var/lib/caddy/.config/caddy
Feb 26 15:19:34 koha caddy[406896]: caddy.ConfigAutosavePath=/var/lib/caddy/.config/caddy/autosave.json
Feb 26 15:19:34 koha caddy[406896]: caddy.Version=v2.9.1 h1:OEYiZ7DbCzAWVb6TNEkjRcSCRGHVoZsJinoDR/n9oaY=
Feb 26 15:19:34 koha caddy[406896]: runtime.GOOS=linux
Feb 26 15:19:34 koha caddy[406896]: runtime.GOARCH=amd64
Feb 26 15:19:34 koha caddy[406896]: runtime.Compiler=gc
Feb 26 15:19:34 koha caddy[406896]: runtime.NumCPU=32
Feb 26 15:19:34 koha caddy[406896]: runtime.GOMAXPROCS=32
Feb 26 15:19:34 koha caddy[406896]: runtime.Version=go1.23.4
Feb 26 15:19:34 koha caddy[406896]: os.Getwd=/
Feb 26 15:19:34 koha caddy[406896]: LANG=en_US.UTF-8
Feb 26 15:19:34 koha caddy[406896]: LANGUAGE=en_US:en
Feb 26 15:19:34 koha caddy[406896]: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Feb 26 15:19:34 koha caddy[406896]: NOTIFY_SOCKET=/run/systemd/notify
Feb 26 15:19:34 koha caddy[406896]: HOME=/var/lib/caddy
Feb 26 15:19:34 koha caddy[406896]: LOGNAME=caddy
Feb 26 15:19:34 koha caddy[406896]: USER=caddy
Feb 26 15:19:34 koha caddy[406896]: INVOCATION_ID=2bbc1056fb19465b9090ae29eecbadd7
Feb 26 15:19:34 koha caddy[406896]: JOURNAL_STREAM=8:12660504
Feb 26 15:19:34 koha caddy[406896]: SYSTEMD_EXEC_PID=406896
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.170833,"msg":"using config from file","file":"/etc/caddy/Caddyfile"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1739964,"msg":"adapted config to JSON","adapter":"caddyfile"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"warn","ts":1740579574.1740112,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":14}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.175929,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1762757,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000733a80"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1765018,"logger":"http.auto_https","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.176525,"logger":"http.auto_https","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1765442,"logger":"http.auto_https","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv1"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1765711,"logger":"http.auto_https","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv2"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"warn","ts":1740579574.1771157,"logger":"http","msg":"enabling strict SNI-Host enforcement because TLS client auth is configured","server_id":"srv1"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"warn","ts":1740579574.1776319,"logger":"http","msg":"enabling strict SNI-Host enforcement because TLS client auth is configured","server_id":"srv2"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1781704,"logger":"http","msg":"enabling HTTP/3 listener","addr":":443"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1783583,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1784155,"logger":"http","msg":"enabling HTTP/3 listener","addr":":4444"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1785595,"logger":"http.log","msg":"server running","name":"srv1","protocols":["h1","h2","h3"]}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1786194,"logger":"http","msg":"enabling HTTP/3 listener","addr":":4445"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1788,"logger":"http.log","msg":"server running","name":"srv2","protocols":["h1","h2","h3"]}
Feb 26 15:19:34 koha caddy[406896]: {"level":"warn","ts":1740579574.178862,"logger":"http","msg":"HTTP/2 skipped because it requires TLS","network":"tcp","addr":":80"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"warn","ts":1740579574.1788719,"logger":"http","msg":"HTTP/3 skipped because it requires TLS","network":"tcp","addr":":80"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.178877,"logger":"http.log","msg":"server running","name":"remaining_auto_https_redirects","protocols":["h1","h2","h3"]}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.178883,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["subdomain2.mydomain.com","subdomain1.mydomain.com"]}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1791015,"msg":"autosaved config (load with --resume flag)","file":"/var/lib/caddy/.config/caddy/autosave.json"}
Feb 26 15:19:34 koha systemd[1]: Started caddy.service - Caddy.
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1795528,"msg":"serving initial configuration"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1894019,"logger":"tls","msg":"storage cleaning happened too recently; skipping for now","storage":"FileStorage:/var/lib/caddy/.local/share/caddy","instance":"8c6318c4-c4d7-47d7-9b46-12f8db1ac0f7","try_again":1740665974.1893983,"try_again_in":86399.99999836}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.189521,"logger":"tls","msg":"finished cleaning storage units"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.189772,"logger":"tls.obtain","msg":"acquiring lock","identifier":"subdomain2.mydomain.com"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.189802,"logger":"tls.obtain","msg":"acquiring lock","identifier":"subdomain1.mydomain.com"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1929193,"logger":"tls.obtain","msg":"lock acquired","identifier":"subdomain1.mydomain.com"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1929417,"logger":"tls.obtain","msg":"lock acquired","identifier":"subdomain2.mydomain.com"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1929982,"logger":"tls.obtain","msg":"obtaining certificate","identifier":"subdomain1.mydomain.com"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1930225,"logger":"tls.obtain","msg":"obtaining certificate","identifier":"subdomain2.mydomain.com"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1937265,"logger":"tls.issuance.acme","msg":"waiting on internal rate limiter","identifiers":["subdomain1.mydomain.com"],"ca":"https://api.buypass.com/acme/directory","account":"my@email.com"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.193748,"logger":"tls.issuance.acme","msg":"done waiting on internal rate limiter","identifiers":["subdomain1.mydomain.com"],"ca":"https://api.buypass.com/acme/directory","account":"my@email.com"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1937659,"logger":"tls.issuance.acme","msg":"using ACME account","account_id":"https://api.buypass.com/acme/acct/...","account_contact":["mailto:my@email.com"]}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.193774,"logger":"tls.issuance.acme","msg":"waiting on internal rate limiter","identifiers":["subdomain2.mydomain.com"],"ca":"https://api.buypass.com/acme/directory","account":"my@email.com"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1937978,"logger":"tls.issuance.acme","msg":"done waiting on internal rate limiter","identifiers":["subdomain2.mydomain.com"],"ca":"https://api.buypass.com/acme/directory","account":"my@email.com"}
Feb 26 15:19:34 koha caddy[406896]: {"level":"info","ts":1740579574.1938148,"logger":"tls.issuance.acme","msg":"using ACME account","account_id":"https://api.buypass.com/acme/acct/...","account_contact":["mailto:my@email.com"]}
Feb 26 15:19:36 koha caddy[406896]: {"level":"info","ts":1740579576.4028327,"msg":"authorization finalized","identifier":"subdomain2.mydomain.com","authz_status":"valid"}
Feb 26 15:19:36 koha caddy[406896]: {"level":"info","ts":1740579576.40289,"msg":"validations succeeded; finalizing order","order":"https://api.buypass.com/acme/order/..."}
Feb 26 15:19:36 koha caddy[406896]: {"level":"info","ts":1740579576.5039544,"msg":"authorization finalized","identifier":"subdomain1.mydomain.com","authz_status":"valid"}
Feb 26 15:19:36 koha caddy[406896]: {"level":"info","ts":1740579576.5039868,"msg":"validations succeeded; finalizing order","order":"https://api.buypass.com/acme/order/..."}
Feb 26 15:19:40 koha caddy[406896]: {"level":"info","ts":1740579580.6198866,"logger":"tls.obtain","msg":"releasing lock","identifier":"subdomain2.mydomain.com"}
Feb 26 15:19:40 koha caddy[406896]: {"level":"info","ts":1740579580.6202471,"msg":"panic: certificate worker: runtime error: invalid memory address or nil pointer dereference\ngoroutine 103 [running]:\ngithub.com/caddyserver/certmagic.(*jobManager).worker.func1()\n\tgithub.com/caddyserver/certmagic@v0.21.6/async.go:58 +0x65\npanic({0x16bd960?, 0x29c0c20?})\n\truntime/panic.go:785 +0x132\ngithub.com/mholt/acmez/v3/acme.(*Client).GetRenewalInfo(0xc00054f450, {0x1daa088, 0xc0002de120}, 0xc00066e008)\n\tgithub.com/mholt/acmez/v3@v3.0.0/acme/ari.go:221 +0xf9c\ngithub.com/mholt/acmez/v3/acme.(*Client).GetCertificateChain.func1({0xc000018d20, 0x2d})\n\tgithub.com/mholt/acmez/v3@v3.0.0/acme/certificate.go:121 +0x338\ngithub.com/mholt/acmez/v3/acme.(*Client).GetCertificateChain(0xc00054f450, {0x1daa088, 0xc0002de120}, {{0xc0008980e8, 0x5}, {0xc000992200, 0x1, 0x1}, 0x1, {0x0, ...}, ...}, ...)\n\tgithub.com/mholt/acmez/v3@v3.0.0/acme/certificate.go:151 +0x11c\ngithub.com/mholt/acmez/v3.(*Client).ObtainCertificate(0xc0009921a0, {0x1daa088, 0xc0002de120}, {{{0xc0008980e8, 0x5}, {0xc000992200, 0x1, 0x1}, 0x1, {0x0, ...}, ...}, ...})\n\tgithub.com/mholt/acmez/v3@v3.0.0/client.go:197 +0x1199\ngithub.com/caddyserver/certmagic.(*ACMEIssuer).doIssue(0xc0009a2a00, {0x1daa088, 0xc0002de120}, 0xc00067aa08, 0x0)\n\tgithub.com/caddyserver/certmagic@v0.21.6/acmeissuer.go:477 +0x668\ngithub.com/caddyserver/certmagic.(*ACMEIssuer).Issue(0xc0009a2a00, {0x1daa088, 0xc0002de120}, 0xc00067aa08)\n\tgithub.com/caddyserver/certmagic@v0.21.6/acmeissuer.go:371 +0xa7\ngithub.com/caddyserver/caddy/v2/modules/caddytls.(*ACMEIssuer).Issue(0x29c6fa0?, {0x1daa088?, 0xc0002de120?}, 0xc000992180?)\n\tgithub.com/caddyserver/caddy/v2@v2.9.1/modules/caddytls/acmeissuer.go:249 +0x25\ngithub.com/caddyserver/certmagic.(*Config).obtainCert.func2({0x1daa088, 0xc0002de120})\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:626 +0xc98\ngithub.com/caddyserver/certmagic.doWithRetry({0x1daa0c0, 0xc000999040}, 0xc0001ac180, 0xc0008c9998)\n\tgithub.com/caddyserver/certmagic@v0.21.6/async.go:104 +0x218\ngithub.com/caddyserver/certmagic.(*Config).obtainCert(0xc000574fc0, {0x1daa0c0, 0xc000999040}, {0xc0003e0e40, 0x1a}, 0x0)\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:700 +0x718\ngithub.com/caddyserver/certmagic.(*Config).ObtainCertAsync(...)\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:505\ngithub.com/caddyserver/certmagic.(*Config).manageOne.func1()\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:415 +0x73\ngithub.com/caddyserver/certmagic.(*jobManager).worker(0x29e5800)\n\tgithub.com/caddyserver/certmagic@v0.21.6/async.go:73 +0x11b\ncreated by github.com/caddyserver/certmagic.(*jobManager).Submit in goroutine 1\n\tgithub.com/caddyserver/certmagic@v0.21.6/async.go:50 +0x279"}
Feb 26 15:19:41 koha caddy[406896]: {"level":"info","ts":1740579581.2733536,"logger":"tls.obtain","msg":"releasing lock","identifier":"subdomain1.mydomain.com"}
Feb 26 15:19:41 koha caddy[406896]: {"level":"info","ts":1740579581.273832,"msg":"panic: certificate worker: runtime error: invalid memory address or nil pointer dereference\ngoroutine 104 [running]:\ngithub.com/caddyserver/certmagic.(*jobManager).worker.func1()\n\tgithub.com/caddyserver/certmagic@v0.21.6/async.go:58 +0x65\npanic({0x16bd960?, 0x29c0c20?})\n\truntime/panic.go:785 +0x132\ngithub.com/mholt/acmez/v3/acme.(*Client).GetRenewalInfo(0xc00001a8f0, {0x1daa088, 0xc0003aa330}, 0xc0001b8b08)\n\tgithub.com/mholt/acmez/v3@v3.0.0/acme/ari.go:221 +0xf9c\ngithub.com/mholt/acmez/v3/acme.(*Client).GetCertificateChain.func1({0xc000c125a0, 0x2d})\n\tgithub.com/mholt/acmez/v3@v3.0.0/acme/certificate.go:121 +0x338\ngithub.com/mholt/acmez/v3/acme.(*Client).GetCertificateChain(0xc00001a8f0, {0x1daa088, 0xc0003aa330}, {{0xc0007a6b00, 0x5}, {0xc000a161f0, 0x1, 0x1}, 0x1, {0x0, ...}, ...}, ...)\n\tgithub.com/mholt/acmez/v3@v3.0.0/acme/certificate.go:151 +0x11c\ngithub.com/mholt/acmez/v3.(*Client).ObtainCertificate(0xc000a161a0, {0x1daa088, 0xc0003aa330}, {{{0xc0007a6b00, 0x5}, {0xc000a161f0, 0x1, 0x1}, 0x1, {0x0, ...}, ...}, ...})\n\tgithub.com/mholt/acmez/v3@v3.0.0/client.go:197 +0x1199\ngithub.com/caddyserver/certmagic.(*ACMEIssuer).doIssue(0xc0009a2a00, {0x1daa088, 0xc0003aa330}, 0xc00078c508, 0x0)\n\tgithub.com/caddyserver/certmagic@v0.21.6/acmeissuer.go:477 +0x668\ngithub.com/caddyserver/certmagic.(*ACMEIssuer).Issue(0xc0009a2a00, {0x1daa088, 0xc0003aa330}, 0xc00078c508)\n\tgithub.com/caddyserver/certmagic@v0.21.6/acmeissuer.go:371 +0xa7\ngithub.com/caddyserver/caddy/v2/modules/caddytls.(*ACMEIssuer).Issue(0x29c6fa0?, {0x1daa088?, 0xc0003aa330?}, 0xc000a16180?)\n\tgithub.com/caddyserver/caddy/v2@v2.9.1/modules/caddytls/acmeissuer.go:249 +0x25\ngithub.com/caddyserver/certmagic.(*Config).obtainCert.func2({0x1daa088, 0xc0003aa330})\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:626 +0xc98\ngithub.com/caddyserver/certmagic.doWithRetry({0x1daa0c0, 0xc000999040}, 0xc000894100, 0xc00075b998)\n\tgithub.com/caddyserver/certmagic@v0.21.6/async.go:104 +0x218\ngithub.com/caddyserver/certmagic.(*Config).obtainCert(0xc000574fc0, {0x1daa0c0, 0xc000999040}, {0xc000717980, 0x14}, 0x0)\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:700 +0x718\ngithub.com/caddyserver/certmagic.(*Config).ObtainCertAsync(...)\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:505\ngithub.com/caddyserver/certmagic.(*Config).manageOne.func1()\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:415 +0x73\ngithub.com/caddyserver/certmagic.(*jobManager).worker(0x29e5800)\n\tgithub.com/caddyserver/certmagic@v0.21.6/async.go:73 +0x11b\ncreated by github.com/caddyserver/certmagic.(*jobManager).Submit in goroutine 1\n\tgithub.com/caddyserver/certmagic@v0.21.6/async.go:50 +0x279"}
```

**Comment by mkibp** [comment]
Similar to: #6561 

To reproduce it's enough to put at the top of Caddyfile, even if having just one simple HTTPS site entered there on a single domain and default port:
```
{
       acme_ca https://api.buypass.com/acme/directory
       email mymail+buypass@mail.com
}
```
After removing above global config, it works with the default Let's Encrypt...

**Comment by mkibp** [comment]
For posterity, I confirm that it works with Caddy compiled with xcaddy

**Comment by devkamiki** [comment]
It doesn't work for me, the issue persists even after i compile it with xcaddy, using certmagic@master...

**Comment by mohammed90** [comment]
> It doesn't work for me, the issue persists even after i compile it with xcaddy, using certmagic@master...

You need the latest of github.com/mholt/acmez, not certmagic.

**Comment by devkamiki** [comment]
> > It doesn't work for me, the issue persists even after i compile it with xcaddy, using certmagic@master...
> 
> You need the latest of github.com/mholt/acmez, not certmagic.

Oh my bad..! I'm trying again. sorry for the incovenience
